### ISSUE TITLE
[Possible contribution] Gaussian process hyper-parameters tuning.

### ISSUE THREAD

**Issue by LucaCappelletti94** [keras-team/keras-tuner#1]
I've been working for a bit now on tuning the hyper-parameters of a keras NN using a gaussian process, and I've wrapped quite a bit of the complexity with [this](https://github.com/LucaCappelletti94/gaussian_process) python package.

If needed, I would love to help out with the project.

Luca

**Comment by omalleyt12** [comment]
@LucaCappelletti94 Thank you for the interest! We've added a [BayesianOptimization Oracle](https://github.com/keras-team/keras-tuner/blob/master/kerastuner/tuners/bayesian.py), if you'd like to contribute, please take a look at the implementation there. We need to keep a native solution, but if you see improvements that can be made to the implementation, please open a PR!
