### ISSUE TITLE
tuner.search with model.fit_generator

### ISSUE THREAD

**Issue by luvwinnie** [keras-team/keras-tuner#104]
In tensorflow we often use tf.data pipeline to generate some data, i hope that we can use the model.fit_generator to fit the model with provided steps_per_epoch.

**Comment by omalleyt12** [comment]
@luvwinnie since TF.14 or so, `model.fit` is able to support all the same usecases as `model.fit_generator`. You can pass generators as well as `tf.data.Dataset`s to `model.fit`

In 2.0, I'd suggest using `model.fit` rather than `model.fit_generator` for all cases

Please reopen and let me know if you run into any issues

**Comment by phobrain** [comment]
Is there example code of searching with DataGenerators? Else more baldly, how would this transform?

        model.fit_generator(
            myGen('train', tr_data, tr_y, batch_size, True),
            int((len(tr_data)-1) / batch_size), # steps per epoch
            epochs=epochs,
            validation_data=
                    myGen('valid', te_data, te_y, batch_size, True),
            validation_steps=1,
            max_queue_size=2,
            workers=1)

**Comment by omalleyt12** [comment]
Yep! The code you provided should work with:

```python
tuner = ...
tuner.search(myGen('train', tr_data, tr_y, batch_size, True),
        steps_per_epoch=int((len(tr_data)-1) / batch_size), # steps per epoch
        epochs=epochs,
        validation_data=
                myGen('valid', te_data, te_y, batch_size, True),
        validation_steps=1,
        max_queue_size=2,
        workers=1)
```

Please let me know if that doesn't work for you

**Comment by Kamran-Afzali** [comment]
I have a similar situation but with data augmentation and flow from directory as follows:

```
train_datagen = ImageDataGenerator( 
	rescale=1. / 255, 
	shear_range=0.2, 
	zoom_range=0.2, 
	horizontal_flip=True) 

test_datagen = ImageDataGenerator(rescale=1. / 255) 

train_generator = train_datagen.flow_from_directory( 
	train_data_dir, 
	target_size=(img_width, img_height), 
	batch_size=batch_size, 
	class_mode='binary') 

validation_generator = test_datagen.flow_from_directory( 
	validation_data_dir, 
	target_size=(img_width, img_height), 
	batch_size=batch_size, 
	class_mode='binary') 

model.fit_generator( 
	train_generator, 
	steps_per_epoch=nb_train_samples // batch_size, 
	epochs=epochs, 
	validation_data=validation_generator, 
	validation_steps=nb_validation_samples // batch_size) 
```
I wonder how it is possible to integrate this to tuner.search!

**Comment by ASRodrigo1** [comment]
@Kamran-Afzali You can do it like that:
`tuner.search(train_generator, steps_per_epoch=200, epochs=60, validation_data=validation_generator)`

**Comment by Vibhugupta10616** [comment]
@ASRodrigo1 this did not work it showed error:

NotFoundError:  No algorithm worked!
	 [[node sequential/conv2d/Conv2D (defined at c:\users\hp\anaconda3\envs\tf_env\lib\site-packages\kerastuner\engine\multi_execution_tuner.py:96) ]] [Op:__inference_train_function_1147]

Function call stack:
train_function

**Comment by ASRodrigo1** [comment]
@Vibhugupta10616 
Check this issue https://github.com/keras-team/keras/issues/7226
and this one https://github.com/tensorflow/tensorflow/issues/41987
This error is not due to the code https://github.com/keras-team/keras-tuner/issues/104#issuecomment-636399986

**Comment by Vibhugupta10616** [comment]
@ASRodrigo1 You were right 
 I just had to reduce the batch size and target size and it worked.
Thanks !!

**Comment by rajatalpha** [comment]
Hi Guys 
I am too trying to implement CNN model from scratch using Keras Tuner & Image Generator approach. I have used 
padding='same ' everywhere yet I am getting the error-
NotFoundError:  No algorithm worked!
	 [[node sequential/conv2d/Conv2D (defined at /opt/conda/lib/python3.7/site-packages/kerastuner/engine/tuner.py:141) ]] [Op:__inference_train_function_9020]

Function call stack:
train_function_
Here is my code-
def build_model(hp):
    model = keras.Sequential([
    # Block A                         
    keras.layers.Conv2D(
        filters=hp.Int('conv_1.1_filter', min_value=32, max_value=128, step=16),
        kernel_size=hp.Choice('conv_1.1_kernel', values = [3,5,7]),padding='same',
        activation='relu', kernel_initializer = glorot_uniform(seed=0),
        input_shape=(224,224,1)
    ),
    keras.layers.BatchNormalization(name = 'BatchN1.1'),
    keras.layers.Conv2D(
        filters=hp.Int('conv_1.2_filter', min_value=32, max_value=128, step=16),
        kernel_size=hp.Choice('conv_1.1_kernel', values = [3,5,7]),padding='same',
        activation='relu', kernel_initializer = glorot_uniform(seed=0)
    ),
    keras.layers.BatchNormalization(name='BatchN-1.2'),
    keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2,2),padding='same'),
    # Block B                         
    keras.layers.Conv2D(
        filters=hp.Int('conv_2.1_filter', min_value=32, max_value=128, step=32),
        kernel_size=hp.Choice('conv_2.1_kernel', values = [3,5,7]),padding='same',
        activation='relu', kernel_initializer = glorot_uniform(seed=0)
    ),
    keras.layers.BatchNormalization(name = 'BatchN2.1'),
    keras.layers.Conv2D(
        filters=hp.Int('conv_2.2_filter', min_value=32, max_value=128, step=32),
        kernel_size=hp.Choice('conv_2.2_kernel', values = [3,5,7]),padding='same',
        activation='relu', kernel_initializer = glorot_uniform(seed=0)
    ),
    keras.layers.BatchNormalization(name='BatchN-2.2'),
    keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2,2),padding='same'),
    keras.layers.Dropout(0.25),
    # Block C 
    keras.layers.Conv2D(
        filters=hp.Int('conv_3.1_filter', min_value=64, max_value=256, step=64),
        kernel_size=hp.Choice('conv_3.1_kernel', values = [3,5,7]),padding='same',
        activation='relu', kernel_initializer = glorot_uniform(seed=0)
    ),
    keras.layers.BatchNormalization(name = 'BatchN3.1'),
    keras.layers.Conv2D(
        filters=hp.Int('conv_3.2_filter', min_value=64, max_value=256, step=64),
        kernel_size=hp.Choice('conv_3.2_kernel', values = [3,5,7]),padding='same',
        activation='relu', kernel_initializer = glorot_uniform(seed=0)
    ),
    keras.layers.BatchNormalization(name='BatchN-3.2'),
    keras.layers.Conv2D(
        filters=hp.Int('conv_3.3_filter', min_value=64, max_value=256, step=64),
        kernel_size=hp.Choice('conv_3.3_kernel', values = [3,5,7]),padding='same',
        activation='relu', kernel_initializer = glorot_uniform(seed=0)
    ),
    keras.layers.BatchNormalization(name='BatchN-3.3'),
    keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2,2),padding='same'),
    keras.layers.Dropout(0.5),
    # Block D
    keras.layers.Conv2D(
        filters=hp.Int('conv_4.1_filter', min_value=256, max_value=2048, step=256),
        kernel_size=hp.Choice('conv_4.1_kernel', values = [3,5,7]),padding='same',
        activation='relu', kernel_initializer = glorot_uniform(seed=0)
    ),
    keras.layers.BatchNormalization(name = 'BatchN4.1'),
    keras.layers.Conv2D(
        filters=hp.Int('conv_4.2_filter', min_value=256, max_value=2048, step=256),
        kernel_size=hp.Choice('conv_4.2_kernel', values = [3,5,7]),padding='same',
        activation='relu', kernel_initializer = glorot_uniform(seed=0)
    ),
    keras.layers.BatchNormalization(name='BatchN-4.2'),
    keras.layers.Conv2D(
        filters=hp.Int('conv_4.3_filter', min_value=256, max_value=2048, step=256),
        kernel_size=hp.Choice('conv_4.3_kernel', values = [3,5,7]),padding='same',
        activation='relu', kernel_initializer = glorot_uniform(seed=0)
    ),
    keras.layers.BatchNormalization(name='BatchN-4.3'),
    keras.layers.AveragePooling2D((2, 2), name='avg_pool_last'),
    keras.layers.Flatten(),
    keras.layers.Dropout(0.25),
    keras.layers.Dense(
        units=hp.Int('dense_1_units', min_value=32, max_value=512, step=32),
        activation='relu',kernel_initializer=glorot_uniform(seed=0)
    ),
    keras.layers.Dropout(0.25),
    keras.layers.Dense(2, activation='softmax')
    ])
    model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate', values=[1e-2, 1e-3,1e-4,1e-5])),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
    return model  

tuner_search=RandomSearch(build_model,
                          objective='val_accuracy',
                          max_trials=5,directory='/content/output',project_name="EVC")

tuner_search.search(training_set,steps_per_epoch=10,epochs=10,validation_data=test_set)

Please help me with the changes if any required to run it
