### ISSUE TITLE
results_summary() not showing hyperparameter values

### ISSUE THREAD

**Issue by curiousily** [keras-team/keras-tuner#121]
Hi,

I am using keras-tuner at commit [7f6b00f45c6e0b0debaf183fa5f9dcef824fb02f](https://github.com/keras-team/keras-tuner/commit/7f6b00f45c6e0b0debaf183fa5f9dcef824fb02f). 

I run RandomSearch tuner in Google Colab Notebook. Calling `results_summary()` gives me the following output:

```bash
|-Results in test_dir/tune_nn
|-Showing 10 best trials
|-Objective: Objective(name='val_accuracy', direction='max') Score: 0.8007448315620422
|-Objective: Objective(name='val_accuracy', direction='max') Score: 0.7988826632499695
|-Objective: Objective(name='val_accuracy', direction='max') Score: 0.774674117565155
|-Objective: Objective(name='val_accuracy', direction='max') Score: 0.77094966173172
|-Objective: Objective(name='val_accuracy', direction='max') Score: 0.5977653861045837
```

[This comment](https://github.com/keras-team/keras-tuner/blob/master/tutorials/helloworld/helloworld.py#L94) suggests that this should also display the hyperparameters along with their values. Is this expected?

Currently, I have to extract the hyperparameters and their values with:

```py
tuner.oracle.get_best_trials(num_trials=1)[0].hyperparameters.values
```

Thanks!

**Comment by omalleyt12** [comment]
@curiousily Thanks for the issue (and also great blog post by the way!)

For display, what do you think about something like this?

```
|-Results in test_dir/tune_nn
|-Showing 10 best trials
|-Trial ac344: Objective(name='val_accuracy', direction='max') Score: 0.8007448315620422
| -- learning_rate: 0.001
| -- layers: 3
| -- units: 100
```

Also we should probably expose a convenience function for ```tuner.oracle.get_best_trials(num_trials=1)[0].hyperparameters.values```, maybe `tuner.get_best_hyperparameters(num_trials=1)`. Then users could recreate (from scratch) their best model by calling:

```python
hps = tuner.get_best_hyperparameters()[0]
# Weights not trained here, as opposed to `tuner.get_best_models()` which includes weights
best_model = tuner.hypermodel.build(hps)
best_model.fit(...)
```

What do you think?

**Comment by MinuteswithMetrics** [comment]
@omalleyt12 I think the display and calling the best model is right on track.

**Comment by omalleyt12** [comment]
@curiousily @MinuteswithMetrics great, sounds good.

I added a convenience method `tuner.get_best_hyperparameters`. Will work on updating the display
