### ISSUE TITLE
Choice is limited to int, float, str, or bool

### ISSUE THREAD

**Issue by hollowgalaxy** [keras-team/keras-tuner#128]
```TypeError: A `Choice` can contain only `int`, `float`, `str`, or `bool`, found values: [None]with types: {<class 'NoneType'>}```

I wish I could use other types, for example I may have a list for choice like `[None, Path(model_path), Path(model_path2)]`.
or another case where `[{},{},{}]`
Is there a reason for restricting to these specific types?

**Comment by omalleyt12** [comment]
@hollowgalaxy Thanks for the issue!

The reason for this limitation is that we have to be able to serialize and deserialize the arguments to `Choice` when running in distributed mode. 

Could you elaborate on what `Path` is in your example?

**Comment by Anton-Velikodnyy** [comment]
from pathlib import Path. https://docs.python.org/3/library/pathlib.html
I was using it as a dummy case, to show as an example which using not-so-default objects. In this case I know I can just pass in the `str(Path())`. But there are scenarios where the basic types don't solve our dilemma.

**Comment by omalleyt12** [comment]
@Anton-Velikodnyy we could potentially switch to just serializing the index of the `Choice` parameter. There are a few issues with doing this though, like the actual value of the HyperParameter not being displayed in result summaries and not being able to fully encapsulate the HyperParameters state in a serialized way.

If this is the behavior that you want though, you could do the below to create this behavior yourself:

```python
def AddChoice(hps, name, values):
    index = hps.Choice(name, list(range(len(values))))
    return values[index]

# Example
import kerastuner as kt
import tensorflow as tf

hps = kt.HyperParameters()
layer = AddChoice(hps, 'a', [tf.keras.layers.Dense(10), tf.keras.layers.Flatten()])
assert isinstance(layer, tf.keras.layers.Layer)
```
 
Hope that helps!

**Comment by omalleyt12** [comment]
Going to close this out as I looked into it and our strong requirements to be able to serialize / deserialize the `HyperParameters` class in a self-contained way make it impossible for us to extend support here

The `AddChoice` method should work for most use cases though
