### ISSUE TITLE
tf < 2.0 compatibility

### ISSUE THREAD

**Issue by srozov** [keras-team/keras-tuner#132]
Are there any specific issues with keras-tuner on tf < 2.0 ?
I previously used it with the latest tf but had to downgrade due to many compatibility issues...
It seems to be working on tf 1.14, would it be safe to continue using it?

**Comment by omalleyt12** [comment]
@srozov Thanks for the issue! We only officially support tf 2.0, but we expect *most* features should work for recent versions of tf like tf 1.14. If you're not seeing errors when running your code then it should be safe for your use case, there shouldn't be any hidden numerical / convergence differences
