### ISSUE TITLE
RuntimeError: Model-building function did not return a valid Keras Model instance

### ISSUE THREAD

**Issue by Vaunorage** [keras-team/keras-tuner#141]
Hi,

I followed exactly the tutorial and I got this error ...

Input :
```
import keras
from keras import layers
from kerastuner.tuners import RandomSearch

def build_model(hp):
    model = keras.Sequential()
    model.add(layers.Dense(units=hp.Int('units',
                                        min_value=32,
                                        max_value=512,
                                        step=32),
                           activation='relu'))
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(
        optimizer=keras.optimizers.Adam(
            hp.Choice('learning_rate',
                      values=[1e-2, 1e-3, 1e-4])),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy'])
    return model

tuner = RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    executions_per_trial=3,
    directory='my_dir',
    project_name='helloworld')
```
Output : 

```
RuntimeError: Model-building function did not return a valid Keras Model instance, found <keras.engine.sequential.Sequential object at 0x7f7209a72950>

```

Help please ?

**Comment by Vaunorage** [comment]
OKay sorry I got it on my own...

Just needed to change the import from 

```import keras ``` 
to 
```from tensorflow import keras```

Now it works !

**Comment by rao208** [comment]
Hello, I've imported keras from tensorflow i.e. from tensorflow import keras, but it still isn't working. 
I am getting the same error message.

My function looks like this:


`def global_average_pooling(x):
    return k.mean(x, axis = (1, 2))


def global_average_pooling_shape(input_shape):
    return tuple((input_shape[0], input_shape[-1]))


def build_model(hp):

    model = Sequential()
    model.add(Conv2D(filters = 64, kernel_size = (3, 3), input_shape = (None, None, 3), activation = "relu"))
    model.add(Conv2D(filters = 64, kernel_size = (3, 3), activation = "relu"))

    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(rate=hp.Float('dropout', min_value=0.0, max_value=0.5, default=0.25, step=0.05,)))
    model.add(BatchNormalization())

##    for i in range(hp.Int("n_layers", 1, 4)):
##        
##        model.add(Conv2D(filters=hp.Int(f"conv_{i}_units", min_value=64, max_value = 256, step = 32,), kernel_size = (3, 3), activation = 'relu'))
##        model.add(Conv2D(filters=hp.Int(f"conv_{i}_units", min_value=64, max_value = 256, step = 32,), kernel_size = (3, 3), activation = 'relu'))
##
##
##        model.add(MaxPooling2D(pool_size = (2, 2)))
##        model.add(Dropout(rate=hp.Float(f'dropout_{i}', min_value=0.0, max_value=0.5, default=0.25, step=0.05,)))
##        model.add(BatchNormalization())
        
    model.add(Conv2D(filters=hp.Choice('num_filters1', values=[64, 128], default=128,), kernel_size = (3, 3), activation = 'relu', name = "convolution_layer_3"))
    model.add(Conv2D(filters=hp.Choice('num_filters2', values=[64, 128], default=128,), kernel_size = (3, 3), activation = 'relu', name = "convolution_layer_4"))
    model.add(MaxPooling2D(pool_size = (2, 2), name = "max_pooling_2"))
    model.add(Dropout(rate=hp.Float('dropout_1', min_value=0.0, max_value=0.5, default=0.25, step=0.05,)))
    model.add(BatchNormalization())


    model.add(Conv2D(filters = 512, kernel_size = (3, 3), activation = 'relu', name = "convolution_layer_6"))
    model.add(Lambda(global_average_pooling, output_shape = global_average_pooling_shape))

    model.add(Dense(10, activation = 'softmax', name = "output_layer"))
    model.compile(optimizer= hp.Choice('optimizer', values=['adam', 'adadelta', 'RMSprop'], default='adam') , loss='categorical_crossentropy', metrics=['accuracy'])
    
    return model
`

I don't quite get what @omalleyt12 is trying to say in the link https://github.com/keras-team/keras-tuner/issues/200

Please help. Thank you

**Comment by ben-arnao** [comment]
He was saying your model building function is supposed to return one model
and in the code you provided you were returning two (encoder, classifier)

Can you please supply and the entire code and error message.

**Comment by rao208** [comment]
Hi, @ben-arnao Thank you for your reply. It is the normal code with my own model as given as in the build_model function. This code seems to work fine for others, but unfortunately, it is giving me this error

```
from tensorflow import keras
from tensorflow.keras import layers
from kerastuner.tuners import RandomSearch
from kerastuner import HyperModel
from kerastuner.engine.hyperparameters import HyperParameters

from keras.datasets import cifar10
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Lambda, Flatten, Dropout, BatchNormalization
from keras.preprocessing.image import ImageDataGenerator
import tensorflow.keras.backend as k
from tensorflow.keras.optimizers import Adam, Adadelta
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping

def global_average_pooling(x):
    return k.mean(x, axis = (1, 2))

def global_average_pooling_shape(input_shape):
    return tuple((input_shape[0], input_shape[-1]))

def build_model(hp):

    model = Sequential()
    model.add(Conv2D(filters = 64, kernel_size = (3, 3), input_shape = (None, None, 3), activation = "relu"))
    model.add(Conv2D(filters = 64, kernel_size = (3, 3), activation = "relu"))

    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(rate=hp.Float('dropout', min_value=0.0, max_value=0.5, default=0.25, step=0.05,)))
    model.add(BatchNormalization())

    model.add(Conv2D(filters=hp.Choice('num_filters1', values=[64, 128], default=128,), kernel_size = (3, 3), activation = 'relu', name = "convolution_layer_3"))
    model.add(Conv2D(filters=hp.Choice('num_filters2', values=[64, 128], default=128,), kernel_size = (3, 3), activation = 'relu', name = "convolution_layer_4"))
    model.add(MaxPooling2D(pool_size = (2, 2), name = "max_pooling_2"))
    model.add(Dropout(rate=hp.Float('dropout_1', min_value=0.0, max_value=0.5, default=0.25, step=0.05,)))
    model.add(BatchNormalization())

    model.add(Conv2D(filters = 512, kernel_size = (3, 3), activation = 'relu', name = "convolution_layer_6"))
    model.add(Lambda(global_average_pooling, output_shape = global_average_pooling_shape))

    model.add(Dense(10, activation = 'softmax', name = "output_layer"))
    model.compile(optimizer= keras.optimizers.Adam(hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])) , loss='categorical_crossentropy', metrics=['accuracy'])
    
    return model

 k.clear_session()

# load dataset
(trainX, trainY), (testX, testY) = cifar10.load_data()

# one hot encode target values
trainY = to_categorical(trainY)
testY = to_categorical(testY)

# create generator to standardize images: preprocessing 
datagen = ImageDataGenerator(featurewise_center=True, featurewise_std_normalization=True)

# calculate mean on training dataset
datagen.fit(trainX)

# prepare an iterators to scale images
train_iterator = datagen.flow(trainX, trainY, batch_size=batch_size)
test_iterator = datagen.flow(testX, testY, batch_size=batch_size)

print('Batches train=%d, test=%d' % (len(train_iterator), len(test_iterator)))

MAX_TRIALS = 1
EXECUTION_PER_TRIAL = 1

tuner = RandomSearch(build_model, objective='val_accuracy', max_trials=MAX_TRIALS, executions_per_trial=EXECUTION_PER_TRIAL, directory='bayesian_optimization', project_name='cifar10')
tuner.search_space_summary()

N_EPOCH_SEARCH = 1
tuner.search(trainX, trainY, epochs=N_EPOCH_SEARCH, validation_split=0.1)

# Show a summary of the search
tuner.results_summary()

# Retrieve the best model.
best_model = tuner.get_best_models(num_models=1)[0]

# Evaluate the best model.
loss, accuracy = best_model.evaluate(testX, testY)
```

**Comment by ben-arnao** [comment]
@rao208 looks like you need the tensorflow version

`from tensorflow.keras.models import Sequential`

**Comment by rao208** [comment]
Oh! It was such a silly mistake on my end. It is working now. Thank you! @ben-arnao

**Comment by NavinMundhra** [comment]
> Oh! It was such a silly mistake on my end. It is working now. Thank you! @ben-arnao

can you please share it? i am getting the same error and I don't understand where am I going wrong.

**Comment by rao208** [comment]
> > Oh! It was such a silly mistake on my end. It is working now. Thank you! @ben-arnao
> 
> can you please share it? i am getting the same error and I don't understand where am I going wrong.

My layers and optimizers were imported from tensorflow.keras like this

```
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam, Adadelta
```
whereas Sequential and layers like Conv2D, MaxPooling etc were imported from keras like this:

```
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Lambda, Flatten, Dropout, BatchNormalization
```
Also, doing this `from tensorflow import keras` doesn't help, because I had both, tensorflow 2.0 and keras installed. 

So, all I had to do was change all `from keras. import .....` to `from tensorflow.keras. import ....` to get rid of the error.

**Comment by rezaeisamiraa** [comment]
Hi all,
I get the same error; here is my code 

rom tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import Conv2DTranspose
from tensorflow.keras.layers import LeakyReLU
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Reshape
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dropout

from tensorflow.keras import backend as K
import tensorflow as tf
#from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers.legacy import Adam
import numpy as np
import keras_tuner
from tensorflow import keras
from keras_tuner import RandomSearch, Hyperband
from tensorflow.keras import backend as K


class MyHyperModel(keras_tuner.HyperModel) :
    
    def __init__(self, width, height, depth):
        self.width = width
        self.height = height
        self.depth=depth
        
    def build(self,  hp) : 
        myfilters=[]
        mykernel=[]
        
        inputShape = (self.height, self.width, self.depth)
        chanDim = -1
        # define the input to the encoder
        inputs = Input(shape=inputShape)
        x = inputs

        
        #model = keras.Sequential()
        #model.add(layers.Input( (width, height, depth)))
        #model.add(layers.Resizing(128, 128, interpolation='bilinear'))
        # Whether to include normalization layer
        #if hp.Boolean("normalize"):
            #model.add(layers.Normalization())
        
        drop_rate = hp.Float("drop_rate", min_value=0.05, max_value=0.45, step=0.10)
        num_conv=hp.Int("num_conv", min_value=2, max_value=8, step=1)
        # Number of Conv Layers is up to tuning
        for i in range( num_conv) :
            # Tune hyperparams of each conv layer separately by using f"...{i}"
            
            tmpfilter=hp.Int(name=f"filters_{i}", min_value=16, max_value=128, step=16)
            myfilters.append(tmpfilter)
            
            tmpkernel=hp.Int(name=f"kernel_{i}", min_value=3, max_value=7, step=2)
            mykernel.append(tmpkernel)
            
            tmpactiv=hp.Choice(name=f"act_{i}", values=['sigmoid', 'relu', "leaky_relu"]) #hp.Choice(['relu','leaky_relu', 'sigmoid'],)
            
            print (tmpfilter, tmpkernel, tmpactiv)
            x=Conv2D(filters=tmpfilter,kernel_size= tmpkernel , strides=1, padding='valid',
                                    activation=tmpactiv)(x)
            
            
            # Batch Norm and Dropout layers as hyperparameters to be searched
            if hp.Boolean("batch_norm1"):
                x=BatchNormalization()(x)
            if hp.Boolean("dropout1"):
                x=Dropout(drop_rate)(x)
            print (x.shape)
            
        volumeSize = K.int_shape(x)
        x=Flatten()(x)
        latentDim=hp.Int("latentDim", min_value=16, max_value=248, step=16)
        num_dense=hp.Int("num_dense", min_value=1, max_value=4, step=1)
        print ('after conv')
        
        for i in range(num_dense) :
            x=Dense(units=hp.Int("neurons",  min_value=64, max_value=300, step=25),
                                       activation=hp.Choice("mlp_activ",values=['sigmoid', 'relu', "leaky_relu"]))(x)
            if hp.Boolean("batch_norm2"):
                   x=BatchNormalization()(x)
            if hp.Boolean("dropout2"):
                    x=Dropout(drop_rate)(x)
            print (x.shape)
            
        
        # Last layer
        latent=Dense(latentDim, activation=hp.Choice("latent_activ", values=['sigmoid', 'relu', "leaky_relu"]))(x)
        print ('latent',latent.shape)
        
        encoder = Model(inputs, latent, name="encoder")
        
        latentInputs = Input(shape=(latentDim,))
        x = Dense(np.prod(volumeSize[1:]))(latentInputs)
        x = Reshape((volumeSize[1], volumeSize[2], volumeSize[3]))(x)
        
        for f,k in zip(reversed(myfilters), reversed(mykernel)):
            x=Conv2DTranspose(filters=f,kernel_size= k , strides=1, padding='valid',
                             activation=hp.Choice( name=f"act2_{i}",values=["relu","leaky_relu", "sigmoid"] ))(x)
            if hp.Boolean("batch_norm3"):
                x=BatchNormalization()(x)
            if hp.Boolean("dropout3"):
                x=Dropout(drop_rate)(x)
                
            print (x.shape)
        outputs= Conv2DTranspose(self.depth, hp.Int(name=f"kernel_{i}", min_value=3, max_value=7, step=2),
                                padding="same")(x)
        print (x.shape)
        #outputs = Activation("sigmoid")(x)
        print (outputs.shape)
        
        decoder = Model(latentInputs, outputs, name="decoder")
        
        autoencoder = Model(inputs, decoder(encoder(inputs)), name="autoencoder")
        opt = Adam(learning_rate=1e-3)
  
        # Picking an opimizer and a loss function
        autoencoder.compile(optimizer=opt ,#hp.Choice('optim',['adam','adamax']),
                      loss=hp.Choice("loss",["mse","bce"]),
                      metrics = ['accuracy'])
        
        # A way to optimize the learning rate while also trying different optimizers
        learning_rate = hp.Choice('lr', [ 0.03, 0.01, 0.003])
        K.set_value(autoencoder.optimizer.learning_rate, learning_rate)
        
        return encoder, decoder, autoencoder
    
    
    def fit(self, hp, encoder, decoder, autoencoder,x, *args, **kwargs) :
        return autoencoder.fit(decoder(encoder(x.reshape(x.shape[0],28,28,1))),x.reshape(x.shape[0],28,28,1), *args,
                         shuffle=hp.Boolean("shuffle"),
                         **kwargs)
      

tuner = keras_tuner.BayesianOptimization(
                        hypermodel=MyHyperModel(28,28,1),
                        objective = "val_accuracy",
                        max_trials =10, #max candidates to test
                        overwrite=True,
                        directory='BO_search_dir',
                        project_name='sign_language_cnn')

tuner.search(x_train ,x_train , epochs=10, validation_data=(x_test, x_test))

**Comment by rezaeisamiraa** [comment]
> Hi all, I get the same error; here is my code
> 
> rom tensorflow.keras.datasets import fashion_mnist from tensorflow.keras.layers import BatchNormalization from tensorflow.keras.layers import Conv2D from tensorflow.keras.layers import Conv2DTranspose from tensorflow.keras.layers import LeakyReLU from tensorflow.keras.layers import Activation from tensorflow.keras.layers import Flatten from tensorflow.keras.layers import Dense from tensorflow.keras.layers import Reshape from tensorflow.keras.layers import Input from tensorflow.keras.models import Model from tensorflow.keras.layers import Dropout
> 
> from tensorflow.keras import backend as K import tensorflow as tf #from tensorflow.keras.optimizers import Adam import matplotlib.pyplot as plt from tensorflow.keras.optimizers.legacy import Adam import numpy as np import keras_tuner from tensorflow import keras from keras_tuner import RandomSearch, Hyperband from tensorflow.keras import backend as K
> 
> class MyHyperModel(keras_tuner.HyperModel) :
> 
> ```
> def __init__(self, width, height, depth):
>     self.width = width
>     self.height = height
>     self.depth=depth
>     
> def build(self,  hp) : 
>     myfilters=[]
>     mykernel=[]
>     
>     inputShape = (self.height, self.width, self.depth)
>     chanDim = -1
>     # define the input to the encoder
>     inputs = Input(shape=inputShape)
>     x = inputs
> 
>     
>     #model = keras.Sequential()
>     #model.add(layers.Input( (width, height, depth)))
>     #model.add(layers.Resizing(128, 128, interpolation='bilinear'))
>     # Whether to include normalization layer
>     #if hp.Boolean("normalize"):
>         #model.add(layers.Normalization())
>     
>     drop_rate = hp.Float("drop_rate", min_value=0.05, max_value=0.45, step=0.10)
>     num_conv=hp.Int("num_conv", min_value=2, max_value=8, step=1)
>     # Number of Conv Layers is up to tuning
>     for i in range( num_conv) :
>         # Tune hyperparams of each conv layer separately by using f"...{i}"
>         
>         tmpfilter=hp.Int(name=f"filters_{i}", min_value=16, max_value=128, step=16)
>         myfilters.append(tmpfilter)
>         
>         tmpkernel=hp.Int(name=f"kernel_{i}", min_value=3, max_value=7, step=2)
>         mykernel.append(tmpkernel)
>         
>         tmpactiv=hp.Choice(name=f"act_{i}", values=['sigmoid', 'relu', "leaky_relu"]) #hp.Choice(['relu','leaky_relu', 'sigmoid'],)
>         
>         print (tmpfilter, tmpkernel, tmpactiv)
>         x=Conv2D(filters=tmpfilter,kernel_size= tmpkernel , strides=1, padding='valid',
>                                 activation=tmpactiv)(x)
>         
>         
>         # Batch Norm and Dropout layers as hyperparameters to be searched
>         if hp.Boolean("batch_norm1"):
>             x=BatchNormalization()(x)
>         if hp.Boolean("dropout1"):
>             x=Dropout(drop_rate)(x)
>         print (x.shape)
>         
>     volumeSize = K.int_shape(x)
>     x=Flatten()(x)
>     latentDim=hp.Int("latentDim", min_value=16, max_value=248, step=16)
>     num_dense=hp.Int("num_dense", min_value=1, max_value=4, step=1)
>     print ('after conv')
>     
>     for i in range(num_dense) :
>         x=Dense(units=hp.Int("neurons",  min_value=64, max_value=300, step=25),
>                                    activation=hp.Choice("mlp_activ",values=['sigmoid', 'relu', "leaky_relu"]))(x)
>         if hp.Boolean("batch_norm2"):
>                x=BatchNormalization()(x)
>         if hp.Boolean("dropout2"):
>                 x=Dropout(drop_rate)(x)
>         print (x.shape)
>         
>     
>     # Last layer
>     latent=Dense(latentDim, activation=hp.Choice("latent_activ", values=['sigmoid', 'relu', "leaky_relu"]))(x)
>     print ('latent',latent.shape)
>     
>     encoder = Model(inputs, latent, name="encoder")
>     
>     latentInputs = Input(shape=(latentDim,))
>     x = Dense(np.prod(volumeSize[1:]))(latentInputs)
>     x = Reshape((volumeSize[1], volumeSize[2], volumeSize[3]))(x)
>     
>     for f,k in zip(reversed(myfilters), reversed(mykernel)):
>         x=Conv2DTranspose(filters=f,kernel_size= k , strides=1, padding='valid',
>                          activation=hp.Choice( name=f"act2_{i}",values=["relu","leaky_relu", "sigmoid"] ))(x)
>         if hp.Boolean("batch_norm3"):
>             x=BatchNormalization()(x)
>         if hp.Boolean("dropout3"):
>             x=Dropout(drop_rate)(x)
>             
>         print (x.shape)
>     outputs= Conv2DTranspose(self.depth, hp.Int(name=f"kernel_{i}", min_value=3, max_value=7, step=2),
>                             padding="same")(x)
>     print (x.shape)
>     #outputs = Activation("sigmoid")(x)
>     print (outputs.shape)
>     
>     decoder = Model(latentInputs, outputs, name="decoder")
>     
>     autoencoder = Model(inputs, decoder(encoder(inputs)), name="autoencoder")
>     opt = Adam(learning_rate=1e-3)
> 
>     # Picking an opimizer and a loss function
>     autoencoder.compile(optimizer=opt ,#hp.Choice('optim',['adam','adamax']),
>                   loss=hp.Choice("loss",["mse","bce"]),
>                   metrics = ['accuracy'])
>     
>     # A way to optimize the learning rate while also trying different optimizers
>     learning_rate = hp.Choice('lr', [ 0.03, 0.01, 0.003])
>     K.set_value(autoencoder.optimizer.learning_rate, learning_rate)
>     
>     return encoder, decoder, autoencoder
> 
> 
> def fit(self, hp, encoder, decoder, autoencoder,x, *args, **kwargs) :
>     return autoencoder.fit(decoder(encoder(x.reshape(x.shape[0],28,28,1))),x.reshape(x.shape[0],28,28,1), *args,
>                      shuffle=hp.Boolean("shuffle"),
>                      **kwargs)
> ```
> 
> tuner = keras_tuner.BayesianOptimization( hypermodel=MyHyperModel(28,28,1), objective = "val_accuracy", max_trials =10, #max candidates to test overwrite=True, directory='BO_search_dir', project_name='sign_language_cnn')
> 
> tuner.search(x_train ,x_train , epochs=10, validation_data=(x_test, x_test))

This is my error message:

File ~/miniconda3/lib/python3.10/site-packages/keras_tuner/engine/base_tuner.py:183, in BaseTuner.search(self, *fit_args, **fit_kwargs)
    180     continue
    182 self.on_trial_begin(trial)
--> 183 results = self.run_trial(trial, *fit_args, **fit_kwargs)
    184 # `results` is None indicates user updated oracle in `run_trial()`.
    185 if results is None:

File ~/miniconda3/lib/python3.10/site-packages/keras_tuner/engine/tuner.py:295, in Tuner.run_trial(self, trial, *args, **kwargs)
    293     callbacks.append(model_checkpoint)
    294     copied_kwargs["callbacks"] = callbacks
--> 295     obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)
    297     histories.append(obj_value)
    298 return histories

File ~/miniconda3/lib/python3.10/site-packages/keras_tuner/engine/tuner.py:221, in Tuner._build_and_fit_model(self, trial, *args, **kwargs)
    203 """For AutoKeras to override.
    204 
    205 DO NOT REMOVE this function. AutoKeras overrides the function to tune
   (...)
    218     The fit history.
    219 """
    220 hp = trial.hyperparameters
--> 221 model = self._try_build(hp)
    222 results = self.hypermodel.fit(hp, model, *args, **kwargs)
    223 tuner_utils.validate_trial_results(
    224     results, self.oracle.objective, "HyperModel.fit()"
    225 )

File ~/miniconda3/lib/python3.10/site-packages/keras_tuner/engine/tuner.py:171, in Tuner._try_build(self, hp)
    169 # Stop if `build()` does not return a valid model.
    170 if not isinstance(model, keras.models.Model):
--> 171     raise RuntimeError(
    172         "Model-building function did not return "
    173         "a valid Keras Model instance, found {}".format(model)
    174     )
    176 # Check model size.
    177 size = maybe_compute_model_size(model)

RuntimeError: Model-building function did not return a valid Keras Model instance, found (<keras.engine.functional.Functional object at 0x16c45c8b0>, <keras.engine.functional.Functional object at 0x169005f30>, <keras.engine.functional.Functional object at 0x2b5430ac0>)
