### ISSUE TITLE
Feature Request: Using tensorboard hparams.

### ISSUE THREAD

**Issue by hollowgalaxy** [keras-team/keras-tuner#142]
Curently I didn't see a good way to save and load the hyperparameters to files.
Additionally, there is already an HParams thing in tensorflow see [here](https://www.tensorflow.org/tensorboard/hyperparameter_tuning_with_hparams)

Would be nice if both were integrated or a function to convert between both. 
I would post some coding examples, but the link above speaks in volumes.

**Comment by omalleyt12** [comment]
@hollowgalaxy Yep, we're in discussion with TensorBoard to have them use Keras Tuner's HyperParameters proto format as Keras Tuner's format will be used internally with TF2.0. We hope to have full native support for Keras Tuner in TensorBoard down the road

You can save to / load from files using the `get_config` `from_config` methods, or the `to_proto` `from_proto` methods:

```python
hp = kt.HyperParameters()
hp.Int('a', 0, 10)

# Returns a dict which can be saved to .json
hp.get_config()

# Load from a dict
kt.HyperParameters.from_config(my_dict)

# Returns a proto which can saved
hp.to_proto()

# Load from a deserialized proto
kt.HyperParameters.from_proto(my_proto)
```

**Comment by hollowgalaxy** [comment]
Sweet. The above posted code would be helpful to have in the Read Me as a subsection.

**Comment by P3GLEG** [comment]
This is a quick hack to get it working with Tensorboard hparams. This was done on tensorflow-gpu-2.1.0

```python
from kerastuner.tuners import RandomSearch
from tensorboard.plugins.hparams import api as hp

#Your model here
model = tf.keras.Sequential([
tf.keras.layers.Dense(units=hp.Int('num_units',
                                        min_value=32,
                                        max_value=512,
                                        step=32), activation='relu'),
HP_NUM_UNITS = hp.HParam('num_units', hp.Discrete([32, 512]))
])

METRIC_ACCURACY = 'Accuracy'
count = 0

class MyTuner(RandomSearch):
    def on_trial_end(self, trial):
        super().on_trial_end(trial)
        global HP_NUM_UNITS, METRIC_ACCURACY,count
        units = trial.hyperparameters.get_config()['values']['units']
        with tf.summary.create_file_writer('logs/hparam_tuning/run-'+str(count)).as_default():
            accuracy = trial.score
            hparams = {
                HP_NUM_UNITS: units
            }
            hp.hparams(hparams)
            tf.summary.scalar(METRIC_ACCURACY, accuracy, step=1)
        count+=1


tuner = MyTuner(
    build_model,
    objective='accuracy',
    max_trials=5,
    executions_per_trial=3,
    directory='my_dir',
    project_name='helloworld')

tuner.search(x, y,
             epochs=5,
             validation_data=(val_x, val_y))
```
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/25095513/74855958-37cf8200-52f6-11ea-976f-c3f60bcc203b.png">

**Comment by srilman** [comment]
@omalleyt12 Whats the status on integrating Keras-Tuner's HyperParameters with Tensorboard?

In the meantime, it doesn't seem particularly difficult to add support for Tensorboard and it would make it much easier to understand the results of a run. I'd presume that it would look somewhat like the previous code snippet. Happy to contribute!

**Comment by vbschettino** [comment]
I would like to second the request to make Keras Tuner natively supported in TensorBoard; it would make this (awesome) tool that much more useful.

In the meantime (and because this issue is one of the first hits for people searching "keras tuner visualization/tensorboard"), I created a small script that reads the output project of a Tuner and generates a CSV file that can be used for visualization with HiPlot. Find it [here](https://github.com/vbschettino/keras-tuner-hiplot).

![sample-result](https://user-images.githubusercontent.com/34548207/79565606-f7e40b80-80a8-11ea-828d-af6d73e37053.png)

**Comment by JonathanDZiegler** [comment]
+1 on native support.

**Comment by carlthome** [comment]
Any official news/plans on this from Google? @omalleyt12's [blog post](https://blog.tensorflow.org/2020/01/hyperparameter-tuning-with-keras-tuner.html) is a great start but any ETA on native support?
