### ISSUE TITLE
RL Example

### ISSUE THREAD

**Issue by greg234234** [keras-team/keras-tuner#146]
Hi everyone,

First, my compliments to everyone working on the project and congratulations on the release.

Studying the documentation, I'm trying to adapt the end-to-end example to fit a simple CartPole-v1 example, [for example this one](https://github.com/keon/deep-q-learning/blob/master/dqn.py) . The end-to-end example defines a **build_model(hp)** function, and a **MyTuner(kt.Tuner)** class with a **run_trial(self, trial, train_ds)** function.

I'm struggling for how to convert [this example](https://github.com/keon/deep-q-learning/blob/master/dqn.py) to use the beautiful magic of keras-tuner.  Should I try to combine the agent class with the tuner class?  Or should the tuner class call the agent?  All input is very welcome, thanks!

**Comment by omalleyt12** [comment]
@greg234234 Thank you!

It looks like you could extend the `DQNAgent` class something like this:

```python
class TunableDQNAgent(DQNAgent):
  def __init__(self, state_size, action_size):
        # Don't build the model here.
        self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.95    # discount rate
        self.epsilon = 1.0  # exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.learning_rate = 0.001

  def set_model(self, model):
    self.model = model
```
Then you could define the `build_model` function:

```python
def build_model(self, hp):
  num_layers = hp.Int('num_layers', 1, 5)
  ...
 return model
```

And then you could have the `Tuner` call the agent:

```python
class DQNTuner(kt.Tuner):
  def __init__(self,
                      hypermodel,
                      agent,
                      oracle,
                      **kwargs):
    super(DQNTuner, self).__init__(
      hypermodel=hypermodel,
      oracle=oracle,
      **kwargs)
    self.agent = agent

  def run_trial(trial):
    model = self.hypermodel.build(trial.hyperparameters)
    self.agent.set_model(model)

    done = False
    batch_size = 32
    for e in range(EPISODES):
        state = env.reset()
        state = np.reshape(state, [1, state_size])
        for time in range(500):
            action = self.agent.act(state)
            next_state, reward, done, _ = env.step(action)
            reward = reward if not done else -10
            next_state = np.reshape(next_state, [1, state_size])
            self.agent.remember(state, action, reward, next_state, done)
            state = next_state
            if done:
                print("episode: {}/{}, score: {}, e: {:.2}"
                      .format(e, EPISODES, time, agent.epsilon))
                # Report the results of each episode to the Oracle.
                self.oracle.update_trial(trial.trial_id, {'time': time}, step=e)
                # Save the model (you could also optionally only save at the end of training).
                self.save_model(trial.trial_id, model, step=e)
                break
            if len(agent.memory) > batch_size:
                agent.replay(batch_size)
```

Putting it all together would look like:

```python
env = gym.make('CartPole-v1')
state_size = env.observation_space.shape[0]
action_size = env.action_space.n

tuner = DQNTuner(
  hypermodel=build_model,
  oracle=kt.oracles.BayesianOptimization(
    objective=kt.Objective('time', 'max'),
    max_trials=40),
  agent=TunableDQNAgent(state_size, action_size),
  project_name='cartpole')

tuner.search()

tuner.results_summary()
```

I haven't tried running this code, there's likely some bugs but if I understand the code you shared correctly then that is the general idea. Please let me know if you run into any issues

**Comment by omalleyt12** [comment]
We should also definitely add an RL example, I'll look into adding a tutorial along these lines

**Comment by omalleyt12** [comment]
Oh also note that you should use `tf.keras` rather than `keras-team/keras` (`tf.keras` is a full superset of `keras-team/keras`). The example you shared is using `keras-team/keras`

```python
from tensorflow import keras
```

**Comment by greg234234** [comment]
This is so cool, thank you for sharing the example. What an awesome project you all have here, congratulations again.
