### ISSUE TITLE
IndexError: list index out of range when using BayesianOptimization 

### ISSUE THREAD

**Issue by PyDataBlog** [keras-team/keras-tuner#151]
I'm currently having issues trying to `BayesianOptimization` for the tuning process for a binary classifier. This issue doesn't appear with `RandomSearch` and `Hyperband`. Here's how the hyper model is constructed:

```py
class MyHyperModel(HyperModel):

    def __init__(self, num_classes):
        self.num_classes = num_classes

    def build(self, hp):

        model = keras.Sequential()

        
        for i in range(hp.Int('num_layers', 2, 20)):

            model.add(keras.layers.Dense(units=hp.Int('units_' + str(i),
                                                min_value=32,
                                                max_value=512, 
                                                step=32),
                                   activation='relu'))

        model.add(keras.layers.Dense(self.num_classes, activation='sigmoid'))

        model.compile(
            optimizer=keras.optimizers.Adam(
                hp.Choice('learning_rate',
                          values=[1e-2, 1e-3, 1e-4])),
            loss='binary_crossentropy',
            metrics=['accuracy'])

        return model


hypermodel = MyHyperModel(num_classes=1)

tuner = BayesianOptimization(
    hypermodel,
    objective='accuracy',
    max_trials=10,
    project_name='test')

tuner.search(X_train.values, y_train.values.flatten(),
             epochs=10,
             validation_data=(X_test.values, y_test.values.flatten()))

```

The search works well for a while and crashes sometimes with this traceback error. It is worthwhile mentioning that the search even completes without this error but most of the time it crashes to this.

```py
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-21-d78d7772b203> in <module>()
      1 tuner.search(X_train.values, y_train.values.flatten(),
      2              epochs=10,
----> 3              validation_data=(X_test.values, y_test.values.flatten()))

4 frames
/usr/local/lib/python3.6/dist-packages/kerastuner/engine/hyperparameters.py in cumulative_prob_to_value(prob, hp)
    842         ele_prob = 1 / len(hp.values)
    843         index = math.floor(prob / ele_prob)
--> 844         return hp.values[index]
    845     elif isinstance(hp, (Int, Float)):
    846         sampling = hp.sampling or 'linear'

IndexError: list index out of range
```

Am I doing something wrong? If yes, how can I correct this?

**Comment by omalleyt12** [comment]
@PyDataBlog Thanks for the issue!

This seems to be an error with how the optimization boundaries were being converted to values, please find the fix in this PR: https://github.com/keras-team/keras-tuner/pull/152/ which should be merged in shortly

**Comment by omalleyt12** [comment]
@PyDataBlog the fix is now merged into master, could you please confirm this fixes the issue you saw, and if not please reopen?

**Comment by PyDataBlog** [comment]
> @PyDataBlog the fix is now merged into master, could you please confirm this fixes the issue you saw, and if not please reopen?

I will test and report.

**Comment by PyDataBlog** [comment]
> @PyDataBlog the fix is now merged into master, could you please confirm this fixes the issue you saw, and if not please reopen?

Tested locally and the issue is gone! Thanks for the quick fix!

**Comment by rafaelstevenson** [comment]
I also have a confusion in using keras tuner for loop for determining hidden layers as search space, if there are anyone willing to help. Thank you
https://stackoverflow.com/questions/66783048/keras-tuner-uses-for-i-in-rangehp-intn-layers-1-3-but-does-not-show-agre
