### ISSUE TITLE
search_generator function does not exist

### ISSUE THREAD

**Issue by TrifonT** [keras-team/keras-tuner#154]
This function is mentioned as a V0.5 feature but it does not exist. I have searched in the source code as well and I couldn't find anything related to it.

**Comment by omalleyt12** [comment]
@TrifonT Thanks for the issue!

`model.fit` now accepts generator data, so there is no need for a separate `search_generator` in Keras Tuner. You can take a look at the [fit documentation](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit) for info on how to pass a generator to it. `tuner.search` accepts the same signature

Do you know where in our documentation you found mention of `search_generator`? We should update that

**Comment by TrifonT** [comment]
It is mentioned in the changelog file under the V0.5 - Major features
https://github.com/keras-team/keras-tuner/blob/master/CHANGELOG.md#major-features-3

**Comment by wangyexiang** [comment]
Dear sir, do you solve the issue？@TrifonT

**Comment by omalleyt12** [comment]
@wangyexiang Please see the documentation for `tf.keras.Model.fit`, which now accepts generators

**Comment by omalleyt12** [comment]
@TrifonT thanks, we'll work on an update of the CHANGELOG to reflect the 1.0 release
