### ISSUE TITLE
New features about parallel processing for tuner?

### ISSUE THREAD

**Issue by Davidsirui** [keras-team/keras-tuner#160]
Dear KerasTuner team:
Do you have a plan for making the tuner parallel run on distribution machine? I think many people may need this feature? If you don't, can I implement a a version and pull a request?

**Comment by omalleyt12** [comment]
@Davidsirui Thanks for the issue!

Yes it is now currently possible to run distributed tuning, please see our tutorial here: https://keras-team.github.io/keras-tuner/tutorials/distributed-tuning/

**Comment by omalleyt12** [comment]
The implementation is mostly here: https://github.com/keras-team/keras-tuner/tree/master/kerastuner/distribute

Please give distributed tuning a try and feel free to open a PR if you see any need for improvements / bug fixes!

**Comment by pocketmax** [comment]
what about parallel processing? Instead of multiple machines, it's one machine but multiple CPU cores
