### ISSUE TITLE
meaning of "best_step"

### ISSUE THREAD

**Issue by srozov** [keras-team/keras-tuner#164]
What is the meaning of `best_step` displayed in the trial summary and why is it 0 ? Is it somehow related to `executions_per_trial` ?

**Comment by omalleyt12** [comment]
@srozov Thanks for the issue!

In our current built-in tuners this will always be `0` (it's essentially unused). The only exception is in the `kt.Tuner` class we use this to correspond to the best epoch of training. It serves as a hint for which checkpoint to reload. When doing multiple `executions_per_trial`, this is not used and instead the best execution is tracked separately and always reloaded. 

In general it's an internal detail that you can ignore unless you are writing your own Tuner subclass
