### ISSUE TITLE
Multi-GPU Support

### ISSUE THREAD

**Issue by ibabbar** [keras-team/keras-tuner#166]
Is there a way to utilize all available GPUs for this hyperparameter optimisation process?

For example, keras.utils has a multi_gpu_model that can allow multithreading for training purposes. Is there an equivalent tool that we can use?

**Comment by omalleyt12** [comment]
@ibabbar Thanks for the issue!

Yes, every `Tuner` class we have accepts a `distribution_strategy` argument. If you pass `distribution_strategy=tf.distribute.MirroredStrategy()` then the model will train in a data-parallel way on all GPUs on your machine

Note another user has had a problem with the tensorflow-gpu version being uninstalled, if you see that no GPUs are being used you may have to follow the process they outlined here https://github.com/keras-team/keras-tuner/issues/168 until we get the fix in

**Comment by omalleyt12** [comment]
I just uploaded a new release on PyPI, version 1.0.1, to fix this. Keras Tuner doesn't explicitly depend on TensorFlow now, so you'll have to make sure TensorFlow is installed separately:

https://pypi.org/project/keras-tuner/

Please let me know and reopen if you're still running into any issues
