### ISSUE TITLE
pip install keras-tuner ignores tensorflow-gpu and installs unwanted tensorflow (cpu version) instead

### ISSUE THREAD

**Issue by svdHero** [keras-team/keras-tuner#168]
# Poblem description
I am using Tensorflow on an Nvidia GPU by means of the PyPi-package "tensorflow-gpu" on Ubuntu 18.04.

When I install keras-tuner, the PyPi-package "tensorflow" is unnecessarily pulled in. As a result, my machine learning scripts are not executed on the GPU anymore, but on the CPU instead.

# Steps to reproduce
```
mkdir my_test
cd my_test
python3 -m venv my_env
source my_env/bin/activate
pip install -U pip setuptools wheel
pip install tensorflow-gpu
pip install keras-tuner
python -c "import tensorflow as tf; print(tf.__version__); print(tf.reduce_sum(tf.random.normal((1000, 1000))))"
```

# Expected behaviour
GPU-version of Tensorflow is used.

# Actual behaviour
CPU-version of Tensorflow is used.

# Workaround
After installation, execute
```
pip uninstall -y tensorflow
pip install -U --ignore-installed tensorflow-gpu
```
This results in the error message
```
ERROR: keras-tuner 1.0.0 requires tensorflow>=2.0.0-beta1, which is not installed.
```
which (hopefully) can be ignored, since tensorflow-gpu is installed. In fact,
```
python -c "import tensorflow as tf; print(tf.__version__); print(tf.reduce_sum(tf.random.normal((1000, 1000))))"
```
is executed on the GPU successfully now.

# Questions
- Is this a bug?
- Can the error message for the above workaround be ignored safely?
- Is it possible to remove the need for the above workaround?

**Comment by omalleyt12** [comment]
@svdHero Thanks for the issue! Looking into this now

**Comment by svdHero** [comment]
Just to clarify further regarding your comment in #166 :

In my case the package "tensorflow-gpu" is not uninstalled, but the additional package "tensorflow" is installed alongside "tensorflow-gpu". During runtime the cpu-version is picked instead if the gpu-version.

**Comment by ajaceves** [comment]
This issue has been happening to me too. As you'd expect the work around is to uninstall the cpu version:
`pip uninstall tensorflow`
then install the gpu version again
` pip install tensorflow-gpu --ignore-installed`

**Comment by daviherc** [comment]
Same thing happens with me, but I am using tensorflow docker (tensorflow/tensorflow:nightly-gpu-py3-jupyter). My tf dependencies are:

tf-estimator-nightly==2.0.0.dev2019110709
tf-nightly-gpu==2.1.0.dev20191106

**Comment by omalleyt12** [comment]
I just uploaded a new release on PyPI, version 1.0.1, to fix this. Keras Tuner doesn't explicitly depend on TensorFlow now, so you'll have to make sure TensorFlow is installed separately:

https://pypi.org/project/keras-tuner/

Please let me know and reopen if you're still running into any issues
