### ISSUE TITLE
Questions: choice between tensorboard plugins and keras-tuner

### ISSUE THREAD

**Issue by TreeKat71** [keras-team/keras-tuner#169]
Hi all,
I want to know the difference between tensorboard plugins and keras-tuner.
I read both documents, and I think the syntax is quite similar.
Currently I use keras with tf2, is it better to use keras-tuner?
Need some advice, thanks !

**Comment by omalleyt12** [comment]
@TreeKat71 Thanks for the issue!

We recommend using Keras Tuner's HyperParameters class, the tensorboard plugin currently uses tf.contrib.HParams, which is no longer available in TF2.

We are working with the TensorBoard team on a native plugin for Keras Tuner's HyperParameters class. That being said, you can currently visualize your tuning results by passing the `tf.keras.callbacks.TensorBoard` callback to `Tuner.search`.
