### ISSUE TITLE
Callbacks in the tuner

### ISSUE THREAD

**Issue by TreeKat71** [keras-team/keras-tuner#170]
I use keras callbacks with keras-tuner, I am not sure if it is the right way

```
tensorboard = TensorBoard( ... )

early_stop = EarlyStopping( ... )

tuner = RandomSearch( ..., executions_per_trial=2)

tuner.search( ..., callbacks=[early_stop, tensorboard])
```

The results above turn out, callbacks only work on the first execution (each trial).

Is it the correct way to use it? and does the behavior act like maintainers think?

**Comment by omalleyt12** [comment]
@TreeKat71 Thanks for the issue!

You are using the callbacks correctly. The callbacks should work for all executions, I'll take a look

**Comment by TreeKat71** [comment]
Here is what I test
```
In [13]: def run_trial(**fit_kwargs):
    ...:     for execution in range(2):
    ...:         fit_kwargs = copy.copy(fit_kwargs)
    ...:         callbacks = fit_kwargs.pop('callbacks', [])
    ...:         print(callbacks)
    ...:

In [14]: run_trial(callbacks = ['callback_1','callback_2'])
['callback_1', 'callback_2']
[]
```

**Comment by omalleyt12** [comment]
PR here to fix: https://github.com/keras-team/keras-tuner/pull/176
