### ISSUE TITLE
Check Points unnecessarily large?

### ISSUE THREAD

**Issue by TashaSkyUp** [keras-team/keras-tuner#172]
This is a feature request.

The size of checkpoints quickly reaches a terabyte, for many this will prohibit the use of keras-tuner. Some feature is needed to limit the growth of the working directory, or to set a limit on how large it can become.

**Comment by yurisa2** [comment]
Second that.
The checkpoint system is really heavy. Can't use keras-tuner for now. All machines spec with SSD limited....

**Comment by omalleyt12** [comment]
@TashaSkyUp Thanks for the issue!

Could you share a simple example of the code you're running?

**Comment by TashaSkyUp** [comment]
I have sense deleted the code and have been concentrating on very small models.  This problem is really only for large models and I'm actually not so sure fixing the checkpoint size or a way to manage total working directory size is within the scope of this project.

**Comment by omalleyt12** [comment]
@TashaSkyUp Ok, sounds good. We could possibly make the number of checkpoints to keep configurable, which would solve some of this. We could also scrub the checkpoints for Trials that were unsuccessful. We'll have to think more about this

**Comment by btharper** [comment]
This also affects smaller environments as well, like Colab. Particularly when exploring a large space where some models are overly large. Worse when compounded large models when skipping max size due to #175

**Comment by srilman** [comment]
After looking into the checkpoints folder, it seems like most of the space is being consumed by these really large checkpoint.data files. What's also weird is that these files can range from 15MB to 3GB for the same run (my space is composed of 4 terms if that happens to matter). 

@omalleyt12 I'm curious as to what exactly is stored in these files that make them so big in the first place.

**Comment by jrhorne** [comment]
Were there any updates to keeping the size of the checkpoints under control?

**Comment by haifeng-jin** [comment]
I believe this has been improved once already.
For further improvements.
We will use #481 to track.

Thanks.
