### ISSUE TITLE
Unexpected hp.int behavior

### ISSUE THREAD

**Issue by DavidBSauer** [keras-team/keras-tuner#173]
Hi all,
I am trying out keras-tuner and am seeing some unexpected behavior. The selected hyperparameter values is selecting values beyond the given range. Here is some dummy code to recreate the issue. 

```
def modelbuilder(hp):
    model = keras.Sequential()
    for y in range(1,5,1):
        max_width = random.randint(2,50)
        print('Max width: '+str(max_width))
        width = hp.Int('width_layer_'+str(y),2,max_width,step=1,sampling='linear')
        print('Width: '+str(width))
    model.add(keras.layers.Dense(width,activation='linear',name='Dense_'+str(y)))
    model.add(keras.layers.Dense(1,activation='linear',name='output'))
    optimizer = keras.optimizers.Adam(lr=0.01,beta_1=0.9,beta_2=0.999,epsilon= 1e-8)
    model.compile(loss='mse',optimizer=optimizer,metrics=['mse'])
    print(model.summary)
    return model
```

Which gives the output:

> Max width: 8
Width: 3
Max width: 24
Width: 25
Max width: 2
Width: 12
Max width: 12
Width: 40
<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f6cb973e240>>
[Trial complete]
[Trial summary]
 > Hp values:
 |-width_layer_1: 3
 |-width_layer_2: 25
 |-width_layer_3: 12
 |-width_layer_4: 40
 |-Score: 0.0873036989569664
 |-Best step: 0

>
Any advice would be greatly appreciated. Thanks!

**Comment by TreeKat71** [comment]
Hi David,
I can't reproduce your situation, could you provide your environment and package version.

Here is the result I ran your code:
> Max width: 3
> Width: 2
> Max width: 24
> Width: 2
> Max width: 50
> Width: 2
> Max width: 46
Is it what you expect?
> Width: 2

**Comment by DavidBSauer** [comment]
Hi @TreeKat71 
Yes it seems to initially print the minimum values, though these do not appear to be used in a model used for training. But when screening multiple models using BayesianOptimization or RandomSearch, the chosen values appear greater than the limits.

I am running Ubuntu, TF 2.0.0-beta1, and keras-tuner 1.0.0 (both kt and tf are from pip3, so should be master branch).

The full results of training 5 models using RandomSearch(modelbuilder,objective='val_loss',max_trials=5,overwrite=True):

Max width: 35
Width: 2
Max width: 5
Width: 2
Max width: 6
Width: 2
Max width: 49
Width: 2
<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f2883862fd0>>
Max width: 6
Width: 23
Max width: 7
Width: 4
Max width: 34
Width: 4
Max width: 27
Width: 30
<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f28a02f6320>>
2019-11-26 11:23:48.881836: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-11-26 11:23:48.890230: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2807995000 Hz
2019-11-26 11:23:48.890566: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x37315a0 executing computations on platform Host. Devices:
2019-11-26 11:23:48.890597: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-11-26 11:23:49.358171: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1483] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
[Trial complete]
[Trial summary]
 > Hp values:
 |-width_layer_1: 23
 |-width_layer_2: 4
 |-width_layer_3: 4
 |-width_layer_4: 30
 |-Score: 0.1029179573059082
 |-Best step: 0
Max width: 10
Width: 12
Max width: 12
Width: 4
Max width: 36
Width: 3
Max width: 35
Width: 6
<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f28684d7390>>
[Trial complete]
[Trial summary]
 > Hp values:
 |-width_layer_1: 12
 |-width_layer_2: 4
 |-width_layer_3: 3
 |-width_layer_4: 6
 |-Score: 0.09573328912258149
 |-Best step: 0
Max width: 44
Width: 19
Max width: 21
Width: 4
Max width: 30
Width: 2
Max width: 36
Width: 21
<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f2882e15400>>
[Trial complete]
[Trial summary]
 > Hp values:
 |-width_layer_1: 19
 |-width_layer_2: 4
 |-width_layer_3: 2
 |-width_layer_4: 21
 |-Score: 0.09826902449131011
 |-Best step: 0
Max width: 29
Width: 27
Max width: 31
Width: 3
Max width: 17
Width: 4
Max width: 3
Width: 26
<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f28805e13c8>>
[Trial complete]
[Trial summary]
 > Hp values:
 |-width_layer_1: 27
 |-width_layer_2: 3
 |-width_layer_3: 4
 |-width_layer_4: 26
 |-Score: 0.09856331646442414
 |-Best step: 0
Max width: 13
Width: 22
Max width: 22
Width: 4
Max width: 27
Width: 3
Max width: 48
Width: 34
<bound method Network.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x7f2880387fd0>>
[Trial complete]
[Trial summary]
 > Hp values:
 |-width_layer_1: 22
 |-width_layer_2: 4
 |-width_layer_3: 3
 |-width_layer_4: 34
 |-Score: 0.09901275753974914
 |-Best step: 0

**Comment by TreeKat71** [comment]
When you initiate it
> Max width: 35
> Width: 2
> Max width: 5
> Width: 2
> Max width: 6
> Width: 2
> Max width: 49
> Width: 2
Do you notice the second and third max_width is 5 and 6.
And then every trial you run, the second and third are less than 5 and 6 respectively.
I didn't trace the code to find out what is really going on.

I think the original code will be like these, otherwise it doesn't make sense to me.
```
def modelbuilder(hp):
    model = keras.Sequential()
    for y in range(1,5,1):
        max_width = random.randint(2,50)
        print('Max width: '+str(max_width))
        width = hp.Int('width_layer_'+str(y),2,max_width,step=1,sampling='linear')
        print('Width: '+str(width))
        model.add(keras.layers.Dense(width,activation='linear',name='Dense_'+str(y)))
        model.add(keras.layers.Dense(1,activation='linear',name='output'))
    optimizer = keras.optimizers.Adam(lr=0.01,beta_1=0.9,beta_2=0.999,epsilon= 1e-8)
    model.compile(loss='mse',optimizer=optimizer,metrics=['mse'])
    print(model.summary)
    return model
```
And you can write like this
```
def modelbuilder(hp):
    model = keras.Sequential()
    for y in range(1, 5):
        # max_width = random.randint(2,50)
        # print('Max width: '+str(max_width))
        # width = hp.Int('width_layer_'+str(y),2,max_width,step=1,sampling='linear')
        # print('Width: '+str(width))
        model.add(
            keras.layers.Dense(
                hp.Int('width_layer_' + str(y), 2, 50, step=1, sampling='linear'),
                activation='linear',
                name='Dense_' + str(y)
            )
        )
        model.add(keras.layers.Dense(1, activation='linear', name='output'))
        
    optimizer = keras.optimizers.Adam(lr=0.01, beta_1=0.9, beta_2=0.999, epsilon=1e-8)
    model.compile(loss='mse', optimizer=optimizer, metrics=['mse'])
    print(model.summary)
    return model
```

**Comment by DavidBSauer** [comment]
@TreeKat71 That version does work, but I don't think it actually addresses my problem. 

The code I wrote was dummy code to illustrate a point. In my specific case I have a function to determine the maximum number of nodes in the layer, based on the preceding layers and known depth, in order to only train over-determined networks. (I realize max_model_size exists, but it simply causes an error. This is not really a great solution.) 

The problem remains that hp.Int does not seem to be obeying the max value when it is determined by a function.

**Comment by omalleyt12** [comment]
@DavidBSauer Thanks for the issue!

I think I see the confusion; the search space gets defined the *first* time `modelbuilder` gets called. `max_width` is a random number that is changing with every trial, but this does not affect the search space once it is set. Once a search parameter with the name 'width_layer_1' has been set, all other calls to `hp.Int('width_layer_1', ...)` sample from the existing parameter's search space. This is intended behavior
