### ISSUE TITLE
how to print and save best model?

### ISSUE THREAD

**Issue by croshong** [keras-team/keras-tuner#181]
Hi 

I'm using Keras tuner to tune the hyperparameter in my model.

It seems to work. but I want to see the detail about the model which is selected by tuner.get_best_models

In model generation without Keras tuner, I could see the detail about model with model.summary()

and save model with model.save().

But it doesn't work in keras tuner.

How can I see the model detail or hyperparameter of selected best model ?

Thanks 

regards

**Comment by omalleyt12** [comment]
@croshong Thanks for the issue!

Could you share a minimal reproduction of the error you are seeing when calling `model.summary()` or `model.save()`? These should work as normal, as the returned Model is a regular tf.keras Model

**Comment by croshong** [comment]
Thanks for your reply omalley

  Attached files are my python code which run a keras tuner and full log file 

  
[keras_tuner.py.txt](https://github.com/keras-team/keras-tuner/files/3947909/keras_tuner.py.txt)
[keras_tuner_log.txt](https://github.com/keras-team/keras-tuner/files/3947910/keras_tuner_log.txt)

Simply filnal part of error log was

Using TensorFlow backend.
Traceback (most recent call last):
  File "gen_chem_model_v2_beta.py", line 169, in <module>
    model.summary()
  File "/lwork01/miniconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1257, in summary
    raise ValueError('This model has not yet been built. '
ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.

It means that model was not generated at all. but using the selected model I could predict the target value with unknown data. So I don't know what's going inside the code.

Thanks

Regards

**Comment by omalleyt12** [comment]
@croshong Ah yes, this is a known limitation in tf.keras. This happens with Sequential or subclassed Models. For these Model types, the topology isn't created until it's been called on some data. You have to run some data through it before calling `model.summary()`. The saved weights will still be restored. The Model should still work with `fit`, `predict`, etc

**Comment by rafaelstevenson** [comment]
@omalleyt12 Hi, i am currently using keras tuner but there are confusions in using it, if you are available to advice or help is much appreciated, i am confused by the model result and the usage of for loop inside my hypermodel to set the hidden layer as a search space variable, i have followed code examples but the result shows disagreement on the model intended . Here is my issue in more detail:  https://stackoverflow.com/questions/66783048/keras-tuner-uses-for-i-in-rangehp-intn-layers-1-3-but-does-not-show-agre
