### ISSUE TITLE
How can keras-tuner work together with TensorFlow canned estimators?

### ISSUE THREAD

**Issue by shendiaomo** [keras-team/keras-tuner#182]
The canned estimators are widely used by many people who want just an out-of-the-box machine learning tool. If `keras-tuner` works for these people, both estimators and `keras-tuner` will be more widely used.

**Comment by omalleyt12** [comment]
@shendiaomo Thanks for the issue!

It's possible to create a subclass of `kerastuner.engine.base_tuner.BaseTuner` that will work for `Estimator`s.  The methods that would need to be overridden are:

`BaseTuner.__init__`
`BaseTuner.run_trial`
`BaseTuner.save_model`
`BaseTuner.load_model`

The [documentation of BaseTuner](https://github.com/keras-team/keras-tuner/blob/master/kerastuner/engine/base_tuner.py) should include enough info to be able to do this for `Estimator`s, however we do not plan at adding support for `Estimator` or canned `Estimator` at this time
