### ISSUE TITLE
Please document how to fetch available measurements

### ISSUE THREAD

**Issue by LanceNorskog** [keras-team/keras-tuner#183]
How do you fetch a sparse dataframe of measurements out of a finished tuning run?
My use case is to run keras-tuner on Colab, fetch the numbers into a dataframe, upload the dataframe to Google Sheet, and examine them there.

**Comment by omalleyt12** [comment]
@LanceNorskog Thanks for the issue!

Could you please elaborate on what you'd like to be able to do? I'm not sure I understand. Maybe you could provide some pseudo-code or idealized code that you'd like to see. 

Is it that you want to see and export all the reported measurements for each Trial?

If so, probably the best option is to use `Oracle.get_best_trials` with the number set to return all the trials:

```python
for trial in tuner.oracle.get_best_trials(20):
  metrics = trial.metrics
  hps = trial.hyperparameters
  ...
```

We should prob make it easier to return all trials by allowing `Oracle.get_best_trials` by setting `num_trials=-1`, filed a feature request here for that: https://github.com/keras-team/keras-tuner/issues/204
