### ISSUE TITLE
Is there a way to perform multiple fit()'s per trial?

### ISSUE THREAD

**Issue by yogi-dmt** [keras-team/keras-tuner#184]
For a single model test i would like to perform multiple runs, and the score for this model should be the worst loss of these runs to mitigate randomness in training and try to get a more stable number to represent a particular model's score.

Also is there any function to provide a get_score() method so we can define how many trials should be ran for a particular model, also this will give us a way to optimize on training params as well.

Is there an easy way to do this?

**Comment by omalleyt12** [comment]
@yogi-dmt Thanks for the issue!

Yes, please take a look at the [code](https://github.com/keras-team/keras-tuner/blob/master/kerastuner/engine/multi_execution_tuner.py#L74) in `run_trial` for the `MultiExecutionTuner`.

That code scores each trial by averaging across runs, but you could copy and paste that into your own `Tuner` subclass and change the logic to score based on the worst run

**Comment by omalleyt12** [comment]
Please reopen if that doesn't work
