### ISSUE TITLE
RandomSearch tuner uses the best score across epochs for each set of hyperparameters

### ISSUE THREAD

**Issue by pedro-ponte** [keras-team/keras-tuner#185]
Is this behaviour expected? It would make more sense to me to use the score after the last epoch.

**Comment by omalleyt12** [comment]
@pedro-ponte Thanks for the issue!

Yes this is expected. We also checkpoint the best score across epochs, and this is what gets reloaded when you call `tuner.get_best_models()`

If you want to only score based on the last epoch, you can override `Tuner.run_trial` to only report the last epoch
