### ISSUE TITLE
tuner.search to use self-implemented yield data generator which can be used by fit_generator?

### ISSUE THREAD

**Issue by ZYHZ100** [keras-team/keras-tuner#188]
Hi,
I am trying to use tuner.search to use my own data generator which is implemented by yield.
but I got the following error.

`

Traceback (most recent call last):
  File "hp_tunning.py", line 297, in <module>
    tunning()
  File "hp_tunning.py", line 206, in tunning
    train_weight=train_weight)
  File "/home/i/i0000013/EmoPain2020-FinalVersion/train_tunning.py", line 96, in train_tunning
    class_weight=class_weight)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/kerastuner/engine/base_tuner.py", line 122, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/kerastuner/engine/multi_execution_tuner.py", line 95, in run_trial
    history = model.fit(*fit_args, **fit_kwargs, callbacks=callbacks)
  File "/home/i/i0000013/miniconda3/envs/emopain-tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 795, in fit
    raise TypeError('Unrecognized keyword arguments: ' + str(kwargs))
TypeError: Unrecognized keyword arguments: {'generator': <generator object DataHandler.prepare_feature_generator at 0x7fc073c7c1d0>}
 
`
DataHandler.prepare_feature_generator is a function that returns train_generator, val_generator...
Thank you so much~

**Comment by ZYHZ100** [comment]
`            tuner.search_generator(generator=generator,
                         steps_per_epoch=train_steps,
                         epochs=args.nb_epochs,
                         callbacks=[early_stopping, checkpointer, tensor_board],
                         validation_data=val_generator,
                         validation_steps=val_steps,
                         verbose=1,
                         workers=args.nb_workers,
                         class_weight=class_weight)`
`

    def prepare_feature_generator(self, files_list,label_files, data_type, train, val, test, evaluate, weight,shuffle):
        """
        Prepare the frames into labeled train and test sets, with help from the
        DataFrame with .jpg-paths and labels for train and pain.
        :param df: pd.DataFrame
        :param data_type: str ['rgb' || 'of']
        :param train: Boolean
        :param val: Boolean
        :param test: Boolean
        :return: np.ndarray, np.ndarray, np.ndarray, np.ndarray
        """
        while True:
            # Shuffle blocks between epochs.
            if train:
                files_list,label_files = self.shuffle_single_files(files_list,label_files)
                         ......#many lines of code here
                        yield (x_array, y_array)
`
My Code is like this.

**Comment by ZYHZ100** [comment]
@omalleyt12 
Thank you~!

**Comment by ZYHZ100** [comment]
Can I overwrite the run_trial of tuner to handle this?

**Comment by omalleyt12** [comment]
@ZYHZ100 thanks for the issue!

You'll have to pass `generator` as the first argument, as a positional argument rather than a keyword argument:

```python
tuner.search(generator,
steps_per_epoch=train_steps,
epochs=args.nb_epochs,
callbacks=[early_stopping, checkpointer, tensor_board],
validation_data=val_generator,
validation_steps=val_steps,
verbose=1,
workers=args.nb_workers,
class_weight=class_weight)
```

Check out the signature of `tf.keras.Model.fit` (which now supports generators :)) here: https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=stable#fit

**Comment by ZYHZ100** [comment]
@omalleyt12 
Hi，thank you for your reply, but after passing the generator as a first positional argument, I still got the same error. It indicates that yield method of data generator is not supported by tf.keras?
Thank you.

**Comment by ZYHZ100** [comment]
Ok, I have solved this issue, but there is another issue coming up. I will try to solve it or open another issue!! Thank you for your help!

**Comment by RomainCendre** [comment]
> Ok, I have solved this issue, but there is another issue coming up. I will try to solve it or open another issue!! Thank you for your help!

Hi, can you provide the solution you've found? I'm still having the same error when I'm using generator instead of direct data. Thanks!

**Comment by saranyaprakash2012** [comment]
Hi, I am trying to do something similar. I would like to use a data generator and tune epochs and batch size of a BLSTM Model.  How do I pass the generator to the trial function?

Batch Generator :
```
def batch_generator(ids, batch_size = BATCH_SIZE):
        batch=[]
        while True:
                np.random.shuffle(ids) 
                for i in ids:
                    batch.append(i)
                    if len(batch)==batch_size:
                        print(f"No ids in batch:{len(batch)}")
                        yield load_data(batch)
                        batch=[]
```

Model : 
```
def create_model_with_param(units=100,dropout=0.01,dense_units=600,dense2_units=90,dense3_units=10,learning_rate=0.0001):
    K.clear_session()
    inputs_eGeMAPS = Input(EGEMAPS_INPUT_SHAPE)
    inputs_MFCC = Input(MFCC_INPUT_SHAPE)
    inputs_Densenet = Input(DENSENET201_INPUT_SHAPE)

    blstm1_eGeMAPS = Bidirectional(LSTM(units=units,return_sequences=True,recurrent_dropout =0,activation='tanh'))(inputs_eGeMAPS)
   # print(f"blstm1_eGeMAPS:{blstm1_eGeMAPS}")

    blstm2_eGeMAPS= Bidirectional(LSTM(units=units,recurrent_dropout =0,activation='tanh'))(blstm1_eGeMAPS)
  # print(f"blstm1_eGeMAPS:{blstm1_eGeMAPS}")
    eGeMAPS_dropout = Dropout(rate= dropout)(blstm2_eGeMAPS)

    blstm1_MFCC = Bidirectional(LSTM(units=units,return_sequences=True,recurrent_dropout =0,activation='tanh'))(inputs_MFCC)
  # print(f"blstm1_MFCC:{blstm1_MFCC}")

    blstm2_MFCC= Bidirectional(LSTM(units=units,recurrent_dropout =0,activation='tanh'))(blstm1_MFCC)
  # print(f"blstm1_MFCC:{blstm1_MFCC}")
    MFCC_dropout = Dropout(rate= dropout)(blstm2_MFCC)
  # blstm1_Densenet = Bidirectional(LSTM(100,return_sequences=True,recurrent_dropout =0.2,activation='relu'))(inputs_Densenet)
    blstm1_Densenet = Bidirectional(LSTM(200,return_sequences=True,recurrent_dropout =0,activation='tanh'))(inputs_Densenet)

    print(f"blstm1_Densenet:{blstm1_Densenet}")

  # blstm2_Densenet= Bidirectional(LSTM(100,recurrent_dropout =0.2,activation='relu'))(blstm1_Densenet)
    blstm2_Densenet= Bidirectional(LSTM(units=units,recurrent_dropout =0,activation='tanh'))(blstm1_Densenet)
    print(f"blstm1_Densenet:{blstm2_Densenet}")

    Densenet_Dropout = Dropout(rate= dropout)(blstm2_Densenet)
    audio_lstm_output = concatenate([eGeMAPS_dropout,MFCC_dropout,Densenet_Dropout])
      
    dense1= Dense(units=dense_units,activation='relu')(audio_lstm_output)
  #     dense1= Dense(500,activation='relu')(blstm2_eGeMAPS)

    print(f"dense:{dense1}")

    dense2= Dense(units=dense2_units,activation='relu')(dense1)
    print(f"dense:{dense2}")

    dense3= Dense(units=dense3_units,activation='relu')(dense2)
    print(f"dense:{dense3}")

    output = Dense(1,activation='sigmoid')(dense3)
    print(f"output:{output}")
      
  #     run_opts = tf.RunOptions(report_tensor_allocations_upon_oom = True)

    model = Model(inputs=[inputs_eGeMAPS,inputs_MFCC,inputs_Densenet], outputs=output)
  #     model = Model(inputs=[inputs_eGeMAPS], outputs=output)

 
    METRICS = [
        metrics.TruePositives(name='tp'),
        metrics.FalsePositives(name='fp'),
        metrics.TrueNegatives(name='tn'),
        metrics.FalseNegatives(name='fn'), 
        metrics.BinaryAccuracy(name='accuracy'),
        metrics.Precision(name='precision'),
        metrics.Recall(name='recall'),
        metrics.AUC(name='auc'),
    ]

    model.compile(optimizer=optimizers.Adam(learning_rate),
                loss=losses.BinaryCrossentropy(),
                metrics=METRICS)
    print(model.summary())
    return model
```

Tuner : 
```
class MyTuner(BayesianOptimization):
  def run_trial(self, trial, *args, **kwargs):
    # You can add additional HyperParameters for preprocessing and custom training loops
    # via overriding `run_trial`
    kwargs['batch_size'] = trial.hyperparameters.Int('batch_size', 4, 16, step=4)
    kwargs['epochs'] = trial.hyperparameters.Int('epochs', 10, 30,step=5)
    super(MyTuner, self).run_trial(trial, *args, **kwargs)

# Uses same arguments as the BayesianOptimization Tuner.
tuner = MyTuner(create_model_with_param,
    objective='recall',
    max_trials=3,
    executions_per_trial=1,
    directory=os.path.normpath('keras_tuning_blstm_audio'),
    project_name='kerastuner_bayesian_lstm_audio',overwrite=True)
# Don't pass epochs or batch_size here, let the Tuner tune them.
```


Usual tuner call for epoch training - where full dataset is passed to the search function 

**tuner.search(X_train, Y_train,validation_split=0.2,verbose=1)**

 

Tuner call when training other params  where the epochs and batch size is fixed, data is passed as a generator 
```
train_data_gen= batch_generator(train_upsample_files,BATCH_SIZE)
val_data_gen= batch_generator(val_files,VAL_BATCH_SIZE)

steps_per_epoch= math.floor(len(train_upsample_files)/BATCH_SIZE) 
val_steps_per_epoch= math.floor(len(val_files)/VAL_BATCH_SIZE)
bayesian_opt_tuner.search(train_data_gen,epochs=n_epochs,steps_per_epoch=steps_per_epoch,validation_data= val_data_gen,validation_steps=val_steps_per_epoch)

```
