### ISSUE TITLE
View hyperparameters for top trials

### ISSUE THREAD

**Issue by geohitt** [keras-team/keras-tuner#193]
After completing a round of trial/epoch optimization I would like to view the best hyperparameters, architecture, etc. from the 5 or 10 best trials.  

From reading previous threads get_best_hyperparameters was exposed to pull the best hp's from get_best_model.  However if i try to expand this to pull hp's s from the ten best models/trials the function returns an error.  From what i can tell the get_best_hyperparmaters only returns a list from the top model and there is no argument to specify grabbing from x # of models.  In my example I am running a couple thousand trials with 10 or so epochs per. 

How can i view a results summary at the end of my search for my specified best hp's from the top 10 models. 

b_tuner.results_summary()
#Retrieve the best model and display its architecture
best_model = b_tuner.get_best_models()[0]
best_model.summary()

#tuner.get_best_hyperparameters(num_trials=1)
hps = b_tuner.oracle.get_best_trials(num_trials=1)[0].hyperparameters.values
print('HyperParameters: {}'.format(hps))

**Comment by omalleyt12** [comment]
@geohitt Thanks for the issue!

I think the code you posted should work, please let me know if you're still experiencing this problem

**Comment by geohitt** [comment]
Hello,  

I have not been able to resolve this.  The code above still pulls only one best trial.  Is there a way to list top ten trials?

**Comment by omalleyt12** [comment]
`tuner.oracle.get_best_trials(10)` should work, in the code above it looks like it is only asking for `1` trial
