### ISSUE TITLE
Code to import results from keras-tuner

### ISSUE THREAD

**Issue by Bigf-sha** [keras-team/keras-tuner#197]
_Originally posted by @ppurwar in https://github.com/keras-team/keras-tuner/issues/41#issuecomment-517650571_

I was able to comeup with a workaround.  Use the attached code to import results in another script 
`

    import os
    import json
    import kerastuner.engine.hyperparameters as hp_module
    import kerastuner.engine.trial as trial_module
    import kerastuner.engine.metrics_tracking as metrics_tracking
    from kerastuner.abstractions.tensorflow import TENSORFLOW_UTILS as tf_utils
    import tensorflow as tf
    from tensorflow.keras.models import model_from_json

    class SearchResults(object):
        def __init__(self, directory, project_name, objective):
            self.directory = directory
            self.project_name = project_name
            self.objective = objective
            
        def reload(self):
            """Populate `self.trials` and `self.oracle` state."""
            fname = os.path.join(self.directory, self.project_name, 'tuner.json')
            state_data = tf_utils.read_file(fname)
            state = json.loads(state_data)

            self.hyperparameters = hp_module.HyperParameters.from_config(
                state['hyperparameters'])
            self.best_metrics = metrics_tracking.MetricsTracker.from_config(
                state['best_metrics'])
            self.trials = [trial_module.Trial.load(f) for f in state['trials']]
            self.start_time = state['start_time']
        
        def _get_best_trials(self, num_trials=1):
            if not self.best_metrics.exists(self.objective):
                return []
            trials = []
            for x in self.trials:
                if x.score is not None:
                    trials.append(x)
            if not trials:
                return []
            direction = self.best_metrics.directions[self.objective]
            sorted_trials = sorted(trials,
                                   key=lambda x: x.score,
                                   reverse=direction == 'max')
            return sorted_trials[:num_trials]
        
        def get_best_models(self, num_models = 1):
            best_trials = self._get_best_trials(num_models)
            models = []
            for trial in best_trials:
                hp = trial.hyperparameters.copy()
                # Get best execution.
                direction = self.best_metrics.directions[self.objective]
                executions = sorted(
                    trial.executions,
                    key=lambda x: x.per_epoch_metrics.get_best_value(
                        self.objective),
                    reverse=direction == 'max')
                
                # Reload best checkpoint.
                ckpt = executions[0].best_checkpoint
                model_graph = ckpt + '-config.json'
                model_wts = ckpt + '-weights.h5'
                with open(model_graph, 'r') as f:
                    model = model_from_json(f.read())
                model.load_weights(model_wts)
                models.append(model)
            return models
`
#### example usage:
        res = SearchResults(directory='./multiclass_classifier/training',
                        project_name='search_bs2000',
                        objective='val_accuracy'                    
                       )
        res.reload()
        model = res.get_best_models()[0]

_Originally posted by @ppurwar in https://github.com/keras-team/keras-tuner/issues/41#issuecomment-517650571_

There is someone that can guess why I have an error in the code? 
Line of code that fail:
 from kerastuner.abstractions.tensorflow import TENSORFLOW_UTILS as tf_utils
Error:
 ModuleNotFoundError: No module named 'kerastuner.abstractions.tensorflow'

**Comment by zutron** [comment]
I came across that code too, and am having the same problem. Did you manage to solve this?

**Comment by omalleyt12** [comment]
@Bigf-sha Thanks for the issue!

We removed the TensorFlow abstractions recently. It looks like that code is only using `tf_utils` to read a file, you should be able to replace that code with [TF GFile code](https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile?version=stable) to read the file. Please reopen if that doesn't work

**Comment by acegilz** [comment]
My code crashed after few days of tuningand I had no change to have the tuner object returned after it.

When I run the above code, I was expecting it to load from the tuner directory the results obtained while tuning. 

What it does is it starts training the model instantly, Amm I  doing something wrong? Does this code still works?

**Comment by phiwei** [comment]
@acegilz did you figure this out? Do you know how to load models directly from generated checkpoint files? I created an issue for this question here:
https://github.com/keras-team/keras-tuner/issues/300

**Comment by acegilz** [comment]
@phiwei Unfortunately I didn't.. if you find a way please let me know

**Comment by phiwei** [comment]
@acegilz what I end up doing now is that after I finish a tuner search, I just use the get_best_models method to load the number of models that I want and save them to a .h5 file manually, not elegant but works well enough for me. I sort of could validate that the method actually returns the best models / model performance is in line with what I expect from the saved scores if I run on validation data again.

**Comment by Bigf-sha** [comment]
Sorry no time to mess around with the code, so I end up doing the same as @phiwei. I save the model and weight in two diferent files just in case I want to update the weight but keeping the desing model as the best obtain by keras-tunner.
