### ISSUE TITLE
tuner.search does not work in Windows

### ISSUE THREAD

**Issue by Bill-Fujimoto** [keras-team/keras-tuner#198]
I didn't see any comments in the documentation re: Windows installation, but tuner.search function appears to not work in windows, it throws a complex error..  I then tested the same script in Linux and the problem was not there.  Please clarify in the documentation if in fact Windows is not compatible.

**Comment by algit123** [comment]
I am also experiencing an issue on Windows (Anaconda IDE). The Tuner Search runs for 1 epoch and fails to save logs to the Checkpoint subdirectory, with the following error:

"NotFoundError: Failed to create a NewWriteableFile: Keras_Tuner_Logs\pfs\trial_cfc1b9a8c32d1333fdd14d4dbdf2ad38\checkpoints\epoch_0\checkpoint_temp_fab24d6bc6114dfb85b42165baf39067/part-00000-of-00001.data-00000-of-00001.tempstate9468928427011482805 : The system cannot find the path specified.
; No such process [Op:SaveV2]"

Apparently, it spawns many processes which come into conflict when accessing the "checkpoints" sub-directory (the sub-directory seems locked ny one of the proceeses, preventing "write" access by another.

**Comment by Bill-Fujimoto** [comment]
> I am also experiencing an issue on Windows (Anaconda IDE). The Tuner Search runs for 1 epoch and fails to save logs to the Checkpoint subdirectory, with the following error:
> 
> "NotFoundError: Failed to create a NewWriteableFile: Keras_Tuner_Logs\pfs\trial_cfc1b9a8c32d1333fdd14d4dbdf2ad38\checkpoints\epoch_0\checkpoint_temp_fab24d6bc6114dfb85b42165baf39067/part-00000-of-00001.data-00000-of-00001.tempstate9468928427011482805 : The system cannot find the path specified.
> ; No such process [Op:SaveV2]"
> 
> Apparently, it spawns many processes which come into conflict when accessing the "checkpoints" sub-directory (the sub-directory seems locked ny one of the proceeses, preventing "write" access by another.

This is the same error as I get, I also posted the issue on Stackoverflow here: https://stackoverflow.com/q/59439124/9447938

**Comment by omalleyt12** [comment]
@Bill-Fujimoto Thanks for the issue!

Hm, this seems like a problem with TensorFlow's SaveV2 Op in Windows, could you file a bug in the TensorFlow repo? You can cc me in the bug. Thanks!

**Comment by Bill-Fujimoto** [comment]
Since I'm not a software engineer, I know nothing about the TF SaveV2 Op nor even how to describe the bug.  I would presume you are part of the keras-tuner team, so it would be better for you or a member of team to pursue this matter with the Tensorflow team.  The original stackoverflow post is linked above.

**Comment by algit123** [comment]
OK. I will pursue this issue with the Tensorflow team.

**Comment by jayasindhura** [comment]
Even I faced the similar issue,When I reduced the length of the LOG_DIR path it started working in windows.

**Comment by VicaR** [comment]
I've finally solved the problem!!!
1. The first one was that @jayasindhura described.
2. But the second issue is that python (or tf) doens't work in Windows with mixed slashes. But kerastuner forms the path with backslashes. So I should provide the path with backslashes. I've done this with os.path.normpath() method:

tuner=RandomSearch(build_model,objective='val_accuracy',max_trials=10,directory=os.path.normpath('C:/'))
tuner.search(x_train,y_train,batch_size=256,epochs=30,validation_split=0.2,verbose=1)

**Comment by ryq99** [comment]
@jayasindhura @VicaR Thank you so much! It's really helpful!

**Comment by alvarado1984** [comment]
The fix in windows is ​​changing this value=1 to this property LongPathsEnabled.
![corrige_largo_keras_tuner](https://github.com/keras-team/keras-tuner/assets/136759700/57ca43e2-44bb-4146-b9b1-bd6d9376655f)

**Comment by paumazcu** [comment]
> I've finally solved the problem!!!
> 1. The first one was that @jayasindhura described.
> 2. But the second issue is that python (or tf) doens't work in Windows with mixed slashes. But kerastuner forms the path with backslashes. So I should provide the path with backslashes. I've done this with os.path.normpath() method:
> 
> tuner=RandomSearch(build_model,objective='val_accuracy',max_trials=10,directory=os.path.normpath('C:/'))
> tuner.search(x_train,y_train,batch_size=256,epochs=30,validation_split=0.2,verbose=1)
>  

I would like the directory to be the current working directory. Is it possible to set the cwd using a relative path?
