### ISSUE TITLE
Cannot import Hyperband from kerastuner

### ISSUE THREAD

**Issue by tondji** [keras-team/keras-tuner#20]
Hi everyone,

I am on tensorflow-2.0.0-beta1 and Google Colab with the GPU environment turned on. Here is the minimal set of ways to reproduce what I am getting as errors:

I tried to install kerastuner on Google Colab using ** !pip install kerastuner** from my empirical intuition and I also tried **!pip install keras-tuner**  from (https://pypi.org/project/keras-tuner/).
Both the times the library gets successfully installed. I did restart the runtime after the installations were complete
When I do a **from kerastuner.tuners import Hyperband**  or **from kerastuner import Hyperband**. I got the following errors.

" ImportError: cannot import name 'Hyperband' "

" ModuleNotFoundError: No module named 'kerastuner.tuners' "

Looking forward to hear from the team.

**Comment by fchollet** [comment]
You need to install from the Github source. I added instructions in the README:

```
git clone https://github.com/keras-team/keras-tuner.git
cd keras-tuner
pip install .
```

Don't install from PyPI :)

**Comment by kenkyusha** [comment]
Similar error but all done as instructed. on Win7 system I get such error:

![ScreenHunter_323 Jul  05 00 11](https://user-images.githubusercontent.com/22096048/60689009-70cafb80-9eb9-11e9-9a92-c8c0fe680fbe.jpg)

**Comment by tondji** [comment]
Me I have done that correctly and everything was fine.
I have done it on colab.

**Comment by didataai** [comment]
pip install keras-hypetune

**Comment by sowmyah22** [comment]
> Hi, I still have this problem!
> 
> Would you please clarify more?

from keras_tuner.tuners import hyperband
try this might work
