### ISSUE TITLE
problem with list representation of keras model and applying keras tuner

### ISSUE THREAD

**Issue by Tonytony123474** [keras-team/keras-tuner#200]
I need to save 2 different models of a single supermodel... encoder , encoder+classifier separately.. 
But I have some issues with using from kerastuner.engine import hyperparameters as hp

Model script:-

def build_model2_tuner(hp):

    enc_block1 = [
        Conv2D(hp.Int("input_units",min_value=32,max_value=356,step=32), kernel_size=(3, 3), activation='relu', padding='same', name='c_input1', input_shape=(256,256,1)),
        MaxPooling2D(pool_size=(2,2), name = "max_pool_input1"),
        BatchNormalization(name="bn_input1")
    ]

     # for number of layers hidden varies from 1 to 6
    enc_block2 = [ ]
    for i in range(hp.Int("n_layers",1,6)):
        enc_block2.extend([
            Conv2D(hp.Int(f"hidden_{i}_units",min_value=32,max_value=356,step=32), kernel_size=(3, 3), activation='relu', padding='same', name=f"conv_hidden_layer_{i}"),
            MaxPooling2D(pool_size=(2,2), name = f"max_pool_hidden_{i}"),
            BatchNormalization(name= f"bn_hidden_{i}") 
        ])

    enc_block3 =  [
        Dropout(0.2),
        Flatten(name='f')
    ]

    classifier_layers = [
        Dense(256, activation='relu', name='dense_1'),
        Dropout(0.2),
        Dense(128, activation='relu', name='dense_2'),
        Dense( 2, activation='sigmoid')
    ]
    
    enc = enc_block1 + enc_block2 + enc_block3
    encoder = Sequential(enc)
    classifier = Sequential(enc + classifier_layers)
    encoder.summary()
    classifier.summary()
    encoder.compile(optimizer='Adam', loss=losses.binary_crossentropy, metrics=['accuracy',])
    classifier.compile(optimizer='Adam', loss=losses.binary_crossentropy, metrics=['accuracy',])
    return encoder, classifier
tuner = RandomSearch( build_model2_tuner,
                      objective= "val_accuracy", # target validation accuracy
                      max_trials= 1,
                      executions_per_trial= 1,
                      directory=LOG_DIR_tune)
tuner.search( 
              x=x_train, 
              y=y_train,
              epochs=2,
              validation_data =(x_test, y_test))

While running this I get this error...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-83-4a30c5ac3528> in <module>
      4                       max_trials= 1,
      5                       executions_per_trial= 1,
----> 6                       directory=LOG_DIR_tune)
      7 tuner.search( 
      8               x=x_train,

~\Anaconda3\lib\site-packages\kerastuner\tuners\randomsearch.py in __init__(self, hypermodel, objective, max_trials, seed, hyperparameters, tune_new_entries, allow_new_entries, **kwargs)
    173             oracle,
    174             hypermodel,
--> 175             **kwargs)
-------------------------------------------------------------------------
RuntimeError: Model-building function did not return a valid Keras Model instance, found (<tensorflow.python.keras.engine.sequential.Sequential object at 0x0000022394F769B0>, <tensorflow.python.keras.engine.sequential.Sequential object at 0x000002224AA00748>)

**Comment by omalleyt12** [comment]
@Tonytony123474 If you want to return more than one Keras Model, you'll have to override `Tuner` or `BaseTuner`. In this case I recommend overriding `BaseTuner`, since `Tuner` assumes a single Keras Model but `BaseTuner` works for any arbitrary object(s). 

The methods you'll need to override are `BaseTuner.run_trial`, `BaseTuner.save_model`, and `BaseTuner.load_model`

The docstring of `BaseTuner.run_trial` should have enough info to get you started with how to do this, if not please let me know:

https://github.com/keras-team/keras-tuner/blob/master/kerastuner/engine/base_tuner.py#L134

**Comment by omalleyt12** [comment]
Please reopen if that doesn't work

**Comment by rao208** [comment]
Hello, I've imported keras from tensorflow i.e. from tensorflow import keras, but it still isn't working. 
I am getting the same error message.

My function looks like this:

```
def global_average_pooling(x):
    return k.mean(x, axis = (1, 2))

def global_average_pooling_shape(input_shape):
    return tuple((input_shape[0], input_shape[-1]))

def build_model(hp):

    model = Sequential()
    model.add(Conv2D(filters = 64, kernel_size = (3, 3), input_shape = (None, None, 3), activation = "relu"))
    model.add(Conv2D(filters = 64, kernel_size = (3, 3), activation = "relu"))

    model.add(MaxPooling2D(pool_size = (2, 2)))
    model.add(Dropout(rate=hp.Float('dropout', min_value=0.0, max_value=0.5, default=0.25, step=0.05,)))
    model.add(BatchNormalization())
    model.add(Conv2D(filters=hp.Choice('num_filters1', values=[64, 128], default=128,), kernel_size = (3, 3), activation = 'relu', name = "convolution_layer_3"))
    model.add(Conv2D(filters=hp.Choice('num_filters2', values=[64, 128], default=128,), kernel_size = (3, 3), activation = 'relu', name = "convolution_layer_4"))
    model.add(MaxPooling2D(pool_size = (2, 2), name = "max_pooling_2"))
    model.add(Dropout(rate=hp.Float('dropout_1', min_value=0.0, max_value=0.5, default=0.25, step=0.05,)))
    model.add(BatchNormalization())

    model.add(Conv2D(filters = 512, kernel_size = (3, 3), activation = 'relu', name = "convolution_layer_6"))
    model.add(Lambda(global_average_pooling, output_shape = global_average_pooling_shape))

    model.add(Dense(10, activation = 'softmax', name = "output_layer"))
    model.compile(optimizer= hp.Choice('optimizer', values=['adam', 'adadelta', 'RMSprop'], default='adam') , loss='categorical_crossentropy', metrics=['accuracy'])
    
    return model

```
I don't quite get what are you trying to say @omalleyt12 

Please help. Thank you
