### ISSUE TITLE
Dynamic number of layers always uses max

### ISSUE THREAD

**Issue by kyleskom** [keras-team/keras-tuner#203]
`    for i in range(hp.Int('n_hidden_layers', min_value=1, max_value=3, step=1)):`

Will always use 3 for hidden layers.

**Comment by BDANG** [comment]
I think it's just a print-statement issue. But I could be wrong. I've seen models with variable number of layers, exactly how you have it with your for-loop. You can view your model architectures with:

```
models = tuner.get_best_models(num_models=3)

for model in models:
    print(model.summary())
```

**Comment by omalleyt12** [comment]
@kyleskom Could you provide a minimal example that reproduces the error?

**Comment by omalleyt12** [comment]
@kyleskom I'm not able to reproduce this issue, the HyperParameter seems to be able to take on all values:

```python
import kerastuner as kt

hp = kt.HyperParameters()
hp.Int('a', 1, 3, step=1)
a = hp.space[0]

for _ in range(10):
  print(a.random_sample())
```

 Please reopen if you are still seeing this issue, and provide code including which Tuner subclass you are using, etc
