### ISSUE TITLE
How to work with parameters supplied at train time?

### ISSUE THREAD

**Issue by yogi-dmt** [keras-team/keras-tuner#205]
Ie. batch size or Callback params. I see that the design is based on a build model function. Is there any support for training params as well?

**Comment by omalleyt12** [comment]
@yogi-dmt Thanks for the issue!

Yes, this can be done via subclassing the `Tuner` class. Please see the guide [here](https://keras-team.github.io/keras-tuner/tutorials/subclass-tuner/)
