### ISSUE TITLE
Does fine tune is compatible with kerastuner?

### ISSUE THREAD

**Issue by RomainCendre** [keras-team/keras-tuner#219]
Hi everyone,

I was wondering if Fine tune was something that can work with this tool.

So I made somthing in this way:

```
from keras.applications import InceptionResNetV2, VGG16
from tensorflow.keras import Sequential, Model
from tensorflow.keras.layers import Dense, Flatten
import kerastuner
from kerastuner.tuners import RandomSearch
from kerastuner.engine.hypermodel import HyperModel
from kerastuner.engine.hyperparameters import HyperParameters
from toolbox.classification.common import Folds, IO, Tools
from toolbox.classification.parameters import Dermatology
from toolbox.models.generators import ResourcesGenerator
from toolbox.transforms.labels import OrderedEncoder

train = inputs[0:2000]
test = inputs[2001:]

gen_train = ResourcesGenerator()
gen_train.flow_from_paths(train['Datum'].values, train['LabelEncode'])

gen_test = ResourcesGenerator()
gen_test.flow_from_paths(test['Datum'].values, test['LabelEncode'])


def model_test(hp):
    base_model = VGG16(weights='imagenet', pooling='avg', include_top=False)
    x = base_model.output
    for i in range(hp.Int('num_layers', 2, 20)):
        x = Dense(units=hp.Int('units_' + str(i), 32, 512, 32), activation='relu')(x)
    x = Dense(2, activation='softmax')(x) 
    model = Model(inputs=base_model.inputs, outputs=x)
    model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

tuner = RandomSearch(
    model_test,
    objective=kerastuner.Objective("val_accuracy", direction="min"),
    max_trials=5,
    executions_per_trial=3,
    directory='test_dir')

tuner.search_space_summary()
tuner.search(gen_train, validation_data=gen_test)
```

But it endup with: 
`Traceback (most recent call last):
  File "/home/rcendre/anaconda3/envs/PythonGPU/lib/python3.7/site-packages/kerastuner/engine/hypermodel.py", line 105, in build
    model = self.hypermodel.build(hp)
  File "<ipython-input-23-b1f68933ee1f>", line 27, in model_test
    x = Dense(units=hp.Int('units_' + str(i), 32, 512, 32), activation='relu')(x)
  File "/home/rcendre/anaconda3/envs/PythonGPU/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 874, in __call__
    inputs, outputs, args, kwargs)
  File "/home/rcendre/anaconda3/envs/PythonGPU/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2038, in _set_connectivity_metadata_
    input_tensors=inputs, output_tensors=outputs, arguments=arguments)
  File "/home/rcendre/anaconda3/envs/PythonGPU/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2054, in _add_inbound_node
    input_tensors)
  File "/home/rcendre/anaconda3/envs/PythonGPU/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 535, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/home/rcendre/anaconda3/envs/PythonGPU/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 535, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/home/rcendre/anaconda3/envs/PythonGPU/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2053, in <lambda>
    inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
AttributeError: 'tuple' object has no attribute 'layer'`

Any ideas on best pratices using existing models?
Best regards

**Comment by omalleyt12** [comment]
@RomainCendre Thanks for the issue!

Yes, this is supported. IMO the best way to do this in TF Keras is to call the `base_model` as though it's any other layer, e.g.:

```python
def model_test(hp):
    base_model = VGG16(weights='imagenet', pooling='avg', include_top=False)
    inputs = tf.keras.Input(shape=(224, 224, 3))
    x = base_model(inputs)
    for i in range(hp.Int('num_layers', 2, 20)):
        x = Dense(units=hp.Int('units_' + str(i), 32, 512, 32), activation='relu')(x)
    x = Dense(2, activation='softmax')(x) 
    model = Model(inputs=inputs, outputs=x)
    model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model
```

Please reopen and let me know if you're still running into issues
