### ISSUE TITLE
ModuleNotFoundError: No module named 'kerastuner.tuners'

### ISSUE THREAD

**Issue by swainsubrat** [keras-team/keras-tuner#22]
Can't import tuners from kerastuner in google colab. The code given in the Readme is also showing attribute error.

**Comment by mohitsharma294** [comment]
Hi swainsubrat,
Please follow below steps:
!git clone https://github.com/keras-team/keras-tuner
cd keras-tuner
!pip install .

from kerastuner import tuners

PFA Zip of colab ipynb file with evidence.
[kerastuner.zip](https://github.com/keras-team/keras-tuner/files/3323789/kerastuner.zip)

**Comment by swainsubrat** [comment]
I'm using it in colab. Will it be usefull?

**Comment by swainsubrat** [comment]
@mohitsharma294 
Read my above comment.

**Comment by mohitsharma294** [comment]
@swainsubrat ,
It would be useful with colab as you will get access to gpu.

**Comment by m-ali-awan** [comment]
> Hi swainsubrat,
> Please follow below steps:
> !git clone https://github.com/keras-team/keras-tuner
> cd keras-tuner
> !pip install .
> 
> from kerastuner import tuners
> 
> PFA Zip of colab ipynb file with evidence.
> [kerastuner.zip](https://github.com/keras-team/keras-tuner/files/3323789/kerastuner.zip)



> Hi swainsubrat,
> Please follow below steps:
> !git clone https://github.com/keras-team/keras-tuner
> cd keras-tuner
> !pip install .
> 
> from kerastuner import tuners
> 
> PFA Zip of colab ipynb file with evidence.
> [kerastuner.zip](https://github.com/keras-team/keras-tuner/files/3323789/kerastuner.zip)

Thanks alot
