### ISSUE TITLE
Parallelize on one machine

### ISSUE THREAD

**Issue by phiwei** [keras-team/keras-tuner#220]
Hi, 

if I have one machine with 4 gpus, can I run the tuner such that it will optimize 4 hyperparameter combinations in parallel, one using each gpu? If so, how?

Thanks!

**Comment by omalleyt12** [comment]
@phiwei Thanks for the issue!

You could do this by running 5 separate processes (4 workers + 1 chief Oracle). You'll have to find a way to specify on each of the 4 workers which GPU it should be using (maybe via a command flag or environment variable is easiest)

Other than that, you can follow the guideline for [distributed tuning](https://keras-team.github.io/keras-tuner/tutorials/distributed-tuning/), setting the `KERASTUNER_ORACLE_IP` env variable to "localhost"

Alternatively, you could also run each trial on 4 GPUs by running one process and passing `distribution_strategy=tf.distribute.MirroredStrategy()` to the `Tuner`

Please reopen and let me know if you have difficulties

**Comment by julia-account** [comment]
Do you have an example of this? I don't really understand how to run it from the help page. I'm also trying to run on local machine using multiple cores/threads. I want to try on CPU first, not sure how good my graphics card actually is.
