### ISSUE TITLE
Hypermodel from hyperparameter config dictionary using deserialize

### ISSUE THREAD

**Issue by sibyjackgrove** [keras-team/keras-tuner#222]
I saw that you can use `kt.engine.hyperparameters.deserialize` to create hyperparameter objects.
For e.g. I can build an Int hyperparameter object as shown below:
`hp_int = kt.engine.hyperparameters.deserialize({'class_name': 'Int', 'config': {'name': 'layers','min_value': 20,'max_value': 30,'step': 1}})`

However, when I include the object in my build hypermodel method, I get an invalid model error as shown below.
```
def build_model(hp):
     ....     
     model.add(layers.Dense(units=hp_int , activation='relu'))
     ....

tuner = RandomSearch(build_model,....)
```

> TypeError: int() argument must be a string, a bytes-like object or a number, not 'Int'
> [Warning] Invalid model 0/5

Is there any way to build a hyper model from a config dictionary similar to how we can do it for layers in Keras?

**Comment by sibyjackgrove** [comment]
@omalleyt12 @fchollet could you please provide a comment on this. I am trying to incorporate keras-tuner into our package that uses .json files for specifying the NN model architecture. If keras-tuner hyperparameters can also be specified through .json files (as shown below), it will be perfect for our application. 

```
"layers": [{"class_name":"Dense","config":{"units": 10,"activation": "relu"}},
 {"class_name":"Dense","config":{"units": {"class_name": 'Int','config': {'name': 
'layers','min_value': 20,'max_value': 30,'step': 1}},"activation": "relu"}},
{"class_name":"Dense","config":{"units": 1}}]
```

Any update from your side on whether this is possible or not would be much appreciated.

**Comment by omalleyt12** [comment]
@sibyjackgrove Thanks for the issue!

My recommendation would be to use `HyperParameters.get_config()` and `HyperParameters.from_config(config)`, which return dicts:

```python
import json
import kerastuner as kt
import tensorflow as tf

hp = kt.HyperParameters()
hp.Int('a', 0, 10, default=5)
config = hp.get_config()

with open('file.json', 'w') as f:
  json.dump(config, f)

with open('file.json', 'r') as f:
  saved_config = json.load(f)

saved_hp = kt.HyperParameters.from_config(saved_config)
assert saved_hp['a'] == 5

def build_model(hp):
  ...

model = build_model(saved_hp)
```

Note that it's probably simpler for your use case to serialize the whole `HyperParameters` container class rather than each `HyperParameter` individually.

Please reopen and let me know if that doesn't work for your needs

**Comment by sibyjackgrove** [comment]
Thank you for the suggestion @omalleyt12 . Unfortunately, it doesn't seem to be working. I created the saved_hp object as you described and passed it to the build_model() method. But I am getting a `TypeError `as show below at `model.add(layers.Dense(units=hp, activation='relu'))`. Could you suggest a solution?

```
hp = kt.HyperParameters()
hp.Int('a', 0, 10, default=5)
config = hp.get_config()

with open('file.json', 'w') as f:
    json.dump(config, f)

with open('file.json', 'r') as f:
    saved_config = json.load(f)

saved_hp = kt.HyperParameters.from_config(saved_config)
assert saved_hp['a'] == 5

def build_model(hp):
    model = keras.Sequential()
    model.add(layers.Input(shape=(5,)))
    model.add(layers.Dense(units=hp, activation='relu'))
    model.add(layers.Dense(1, activation='linear'))
    model.compile(optimizer=keras.optimizers.Adam(1e-3), loss='mse', metrics=['accuracy'])
    return model

model = build_model(saved_hp)
model.summary()    
```

> TypeError: int() argument must be a string, a bytes-like object or a number, not 'HyperParameters'

**Comment by omalleyt12** [comment]
@sibyjackgrove You're passing the entire `HyperParameters` object to `units`, instead try:

```
units=hp.get('a')
```

or 

```
units=hp.Int('a', 0, 10, default=5)
```

**Comment by sibyjackgrove** [comment]
@omalleyt12 I added `units=hp.get('a')` to the build_model() method. Now `model = build_model(saved_hp)` does work. But when I build the tuner object using `build_model()`, I am getting a value error. How do I update the hp object with the required config when it is being to create the tuner object.

```
hp = kt.HyperParameters()
hp.Int('a', 0, 10, default=5)
config = hp.get_config()

with open('file.json', 'w') as f:
    json.dump(config, f)

with open('file.json', 'r') as f:
    saved_config = json.load(f)

saved_hp = kt.HyperParameters.from_config(saved_config)
assert saved_hp['a'] == 5

def build_model(hp):
    model = keras.Sequential()
    model.add(layers.Input(shape=(5,)))
    model.add(layers.Dense(units=hp.get('a'), activation='relu'))
    model.add(layers.Dense(1, activation='linear'))
    model.compile(optimizer=keras.optimizers.Adam(1e-3), loss='mse', metrics=['mse'])
    return model

tuner = kt.Hyperband(
    build_model,
    objective='val_mse',
    max_epochs=30,
    hyperband_iterations=2)
```

> Traceback (most recent call last):
>   File "C:\Users\splathottam\AppData\Roaming\Python\Python37\site-packages\kerastuner\engine\hypermodel.py", line 105, in build
>     model = self.hypermodel.build(hp)
>   File "<ipython-input-8-b9ebe249a443>", line 5, in build_model
>     model.add(layers.Dense(units=hp.get('a'), activation='relu'))
>   File "C:\Users\splathottam\AppData\Roaming\Python\Python37\site-packages\kerastuner\engine\hyperparameters.py", line 617, in get
>     'Unknown parameter: {}'.format(full_name))
> ValueError: Unknown parameter: a
