### ISSUE TITLE
GPR for Bayesian Opt initializes with Matern kernel but loads a different one?

### ISSUE THREAD

**Issue by ben-arnao** [keras-team/keras-tuner#224]
Looks like the Bayesian Oracle is initialized with the following kernel for GPR

`kernel=gaussian_process.kernels.Matern(nu=2.5)`

But then if we load back up the Oracle the a different kernel is loaded

`kernel=gaussian_process.kernels.ConstantKernel(1.0)`

Is there a reason for this?

**Comment by omalleyt12** [comment]
@yogi-dmt Thanks for the issue!

This looks like an oversight from when we changed kernels. Would you be able to submit a PR that changes this to use the Matern kernel when loading?

**Comment by omalleyt12** [comment]
Fixed now
