### ISSUE TITLE
How to optimize learning rate and optimizer in Keras Tuner? 

### ISSUE THREAD

**Issue by selihadji** [keras-team/keras-tuner#226]
Is it possible to optimize learning rate AND the optimizer?

Given that the optimizer can be selected as follows:   
```
optimizer = hp.Choice('optimizer', ['adam', 'sgd'])    
model.compile(optimizer=optimizer, 
                        loss='sparse_categorical_crossentropy', 
                        metrics=['accuracy'])
```
and the learning rate as follows:
```
model.compile(optimizer=tf.keras.optimizers.Adam(
                        hp.Float('learning_rate', 1e-4, 1e-2, sampling='log')),
                        loss='sparse_categorical_crossentropy', metrics=['accuracy'])
```
I tried to include in the model definition the following:
```
lr = hp.Choice('lr', values=[0.08, 0.1, 0.11, 0.14, 0.18])
optimizer = hp.Choice('optimizer', 
     values=[tensorflow.keras.optimizers.Adam(learning_rate=lr),
                  tensorflow.keras.optimizers.RMSprop(learning_rate=lr),
                  tensorflow.keras.optimizers.SGD(learning_rate=lr)])
```
but I got this error:

> TypeError: A `Choice` can contain only one type of value

**Comment by yogi-dmt** [comment]
I believe you will need to create a wrapper function to accomplish this.

```
def get_optimizer(optimizer, lr):
    if optimizer == 'adam':
        return tensorflow.keras.optimizers.Adam(learning_rate=lr)
    elif
        ....

lr = hp.Choice('lr', values=[0.08, 0.1, 0.11, 0.14, 0.18])
optimizer = hp.Choice('optimizer', values=['adam', 'rmsprop', 'sgd'])

optimizer = get_optimizer(optimizer, lr)
```

**Comment by selihadji** [comment]
> I believe you will need to create a wrapper function to accomplish this.
> 
> ```
> def get_optimizer(optimizer, lr):
>     if optimizer == 'adam':
>         return tensorflow.keras.optimizers.Adam(learning_rate=lr)
>     elif
>         ....
> 
> lr = hp.Choice('lr', values=[0.08, 0.1, 0.11, 0.14, 0.18])
> optimizer = hp.Choice('optimizer', values=['adam', 'rmsprop', 'sgd'])
> 
> optimizer = get_optimizer(optimizer, lr)
> ```
