### ISSUE TITLE
Only random trials are collision aware, Bayesian tuning will test the same config multiple times?

### ISSUE THREAD

**Issue by ben-arnao** [keras-team/keras-tuner#227]
I don't think we ever want to be testing the same config more than once right? Is there a way to give Bayesian tuning the same awareness of previously tested configs so we don't waste an iteration on an already tested config?

**Comment by ben-arnao** [comment]
I solved this by flagging when a param is retrieved during the build model process. Basically all params defined in your model building function, should be automatically conditional.

```
    hyperparameters.py

    def is_active(self, name):
        return name in self.active_params

    def _retrieve(self,
                  name,
                  type,
                  config,
                  overwrite=False):
        """Gets or creates a `HyperParameter`."""
        self.active_params.append(name)
        return self._retrieve_helper(name, type, config, overwrite)
    
    oracle.py
   
    def get_active_params(self, hps):
        return {name: val for name, val in hps.values.items() if hps.is_active(name)}

    def _compute_values_hash(self, hps):
        values = self.get_active_params(hps)
        keys = sorted(values.keys())
        s = ''.join(str(k) + '=' + str(values[k]) for k in keys)
        return hashlib.sha256(s.encode('utf-8')).hexdigest()[:32]
```

This does require you to build the model before you compute the hash but i believe the cost of pre building the model is far less than testing the same config twice for no gain. For me, building the model doesn't take long at all.

**Comment by LavertuJS** [comment]
@ben-arnao 
If you dont mind, could you share a bit more about how you implemented this?
I'm having the same issue (Bayesian tuning trying the same configuration several times), but I haven't been able to successfully implement the code you provided.

For example, I can't find any method called _retrieve_helper() in the code... I tried looking for something like it in  previous versions, but no success there.
