### ISSUE TITLE
Mixed input networks with combined X_trains

### ISSUE THREAD

**Issue by csepreghy** [keras-team/keras-tuner#232]
Hey, I'm trying to implement keras-tuner in my mixed input network. It has a CNN and a MLP which is combines into a final dense layer. In the original implementation I'm passing a list of inputs: 
```
history = model.fit(x=[X_train_cnn, X_train_mlp],
                                 y=y_train,
                                 validation_data=([X_test_cnn, X_test_mlp], y_test),
                                 epochs=10,
                                 callbacks=callbacks)
```
When trying to run `tuner.search()` I get an error saying that "Expected to see 2 array(s), but instead got the following list of 1 arrays"

Is there a current workaround or this is something that's not yet supported?

**Comment by omalleyt12** [comment]
@csepreghy Thanks for the issue! 

Could you provide a minimal, self-contained example that reproduces the error?

You should be able to pass the same arguments to `tuner.search` as to `model.fit`

**Comment by omalleyt12** [comment]
Please re-open if you can provide a repro
