### ISSUE TITLE
Continue after one training iteration

### ISSUE THREAD

**Issue by michaelmior** [keras-team/keras-tuner#234]
I performed optimization using Hyperband and I'd like to continue optimizations for more iterations. I tried just changing the value of `hyperband_iterations` and running again, but the `search` method just returns immediately. Is there any way to make use of previous results without starting over?

**Comment by ben-arnao** [comment]
Can you just set the variable after u load the tuner?

```
#load tuner

tuner.oracle.hyperband_iterations = 10

tuner.search()
```

When the tuner saves next time, the variable should be committed into the existing oracle.

**Comment by michaelmior** [comment]
Thanks! That seems to be working. It would be nice if this were not necessary, or at least documented somewhere, but it seems to have solved my problem.
