### ISSUE TITLE
Custom Keras optimizers aren't accepted

### ISSUE THREAD

**Issue by rlh1994** [keras-team/keras-tuner#244]
When creating and using a custom keras optimizer the tuner fails to run due to expecting the methods required by the tensorflow optimizer_v2 instead. This makes it very difficult to use this to tune on custom optimizers as you first have to rewrite the keras implementation into the tensorflow implementation instead.

**Comment by omalleyt12** [comment]
@rlh1994 Thanks for the issue!

Keras Tuner works with the Keras imported like `from tensorflow import keras`

If you're creating a custom optimizer, it should subclass `tf.keras.optimizers.Optimizer`

Note that the Keras code imported via `import keras` is deprecated in favor of the native TensorFlow Keras, which is built by the same team and contains many more features
