### ISSUE TITLE
Use UniOpt for optimization

### ISSUE THREAD

**Issue by KOLANICH** [keras-team/keras-tuner#25]
Hi. I have created https://gitlab.com/KOLANICH/UniOpt.py - it is the similar solution and it has a framework for wrapping optimizers. It may make sense to remove all the optimizer wrappers from this lib and use UniOpt for it.

**Comment by omalleyt12** [comment]
@KOLANICH Thanks for the issue! This library is used internally at Google and so we need to have our own optimizers. But if you think there are optimizers that would be useful to add to this repo, please create a subclass of the `Oracle` class and benchmark the optimization algorithm against some common neural network datasets
