### ISSUE TITLE
Distributed hyperband tuner runs continuously

### ISSUE THREAD

**Issue by durrantmm** [keras-team/keras-tuner#256]
Hello,

I ran the distributed tuner tutorial on google cloud virtual machines with a shared filesystem. One chief instance with no GPU, multiple worker instances with a single GPU. When I run the tutorial with a single worker and for one complete hyperband iteration, it runs successfully. When I run it with two workers, it looks like the workers share the workload initially, but then one exits, and the other worker keeps going and starts running through earlier brackets of the hyperband algorithm.

Has anybody seen anything like this? Is there something I am missing?

**Comment by Tomer23** [comment]
I ran into that problem as well, its a simple typo. The first worker exits but the others go over the bound and create brackets endlessly. See the linked pr

**Comment by sim-san** [comment]
I have the same problem. It would be good if this bugfix could be merged quickly

**Comment by vuhoangminh** [comment]
I have the same problem.

**Comment by ag-tcm** [comment]
I had 8 tuners running across multiple machines. One of them quit gracefully with the message
"tensorflow.runHyperBacktest(backtest.py:151) INFO: Oracle triggered exit"
the others kept on running...for a day. Thankful I came here and saw this and thanks to Tomer23 for the fix. Luckily I was running the tuning locally and didn't rack up a huge AWS bill with this endless loop bug :-)
