### ISSUE TITLE
Trial summary: Best step always zero - impact on checkpoints?

### ISSUE THREAD

**Issue by phiwei** [keras-team/keras-tuner#261]
Hi, 

I noticed that in the trial summary, the "Best step" is always 0. This happens both for my own code as well as if I run any case from the Hello world example (https://keras-team.github.io/keras-tuner/examples/helloworld/)

You mention that this is expected behaviour in this issue: #164 

What implications does this have regarding checkpoints? I noticed that only a checkpoint folder called "epoch_0" is created, independent of the number of epochs that the models run through and independent of whether there is better objective scores in a later epoch. Does that mean that only a checkpoint for the first epoch is saved? Or is the checkpoint of the best model saved in the epoch_0 folder?

**Comment by minesh1291** [comment]
Hi @phiwei, did you found any explanation on the topic? I am also wondering about the same issue.

**Comment by phiwei** [comment]
Hi, this is a very long time ago now so I unfortunately do not remember it clearly... If I recall correctly, this checkpoint was indeed the best model weights. However, I had a lot of further issues with this package and therefore decided to switch to PyTorch + RayTune, very happy with that combination so far.
