### ISSUE TITLE
activity regularizer in keras tuner

### ISSUE THREAD

**Issue by Luma12** [keras-team/keras-tuner#266]
Hi!

How can include the activity_regularizer l2 in the keras tuner?
This is the function, but it doesn't compile
```py

from keras import regularizers
from tensorflow import keras
from keras.regularizers import l2, activity_l2

def tune_nn_model(hp):
    model = keras.Sequential()
    drop_rate = hp.Choice('drop_rate',
                            [ 0.0, 0.1, 0.2, 0.3, 0.4,0.5 ])
    model.add(keras.layers.Dense(hp.Choice('units',[5,10,12,14,15,17,18,20,25,30,35,40]),
                        activation="relu",
                                 input_shape=[XX_train.shape[1]],
                             hp.Choice('l2',[0.01,0.001,0.1,0.005,0.05])   ))

    model.add(keras.layers.Dropout(rate=drop_rate))
    model.add(keras.layers.Dense(1, activation='sigmoid'))
    lr = hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])
    
    model.compile(
        optimizer=keras.optimizers.SGD(lr),
        loss = 'binary_crossentropy',
        metrics = ['accuracy'] )#[tf.keras.metrics.AUC()])
    return model
```

**Comment by ben-arnao** [comment]
`hp.Choice('l2',[0.01,0.001,0.1,0.005,0.05])   )`

I'm not sure your code here does what you want it to. Any param you define here is just a placeholder for the param value. So in this line of code you're just supply a float as an un-named variable to the function. Ie.

`Dense(10, activation='relu', 0.05)`

You need to do something like the following...

`Dense(10, activation='relu', kernel_regularizer=hp.Choice('reg_value', [0.01,0.001,0.1,0.005,0.05]))`

If you want to optimize on type of regularization you can create a wrapper...

```
def reg_wrapper(type, value):
    if type == 'l2':
        return regularizers.l2(value)
    if type == 'l1':
        return regularizers.l1(value)
```

Then in Dense:

reg = reg_wrapper((hp.Choice('type', ['l1', 'l2'], hp.Choice('reg_value', [0.01,0.001,0.1,0.005,0.05])))
`Dense(10, activation='relu', kernel_regularizer=reg)`

**Comment by Luma12** [comment]
Hi!
I tried to do what u suggest but I found this error:

ValueError: ('Could not interpret regularizer identifier:', 0.01)

**Comment by oluwayetty** [comment]
from keras import regularizers
from tensorflow import keras
from keras.regularizers import l2, activity_l2

def tune_nn_model(hp):
    model = keras.Sequential()
    drop_rate = hp.Choice('drop_rate', [ 0.0, 0.1, 0.2, 0.3, 0.4,0.5 ])
    kernels = hp.Choice('l2', values=[0.01,0.001,0.1,0.005,0.05])
    model.add(keras.layers.Dense(hp.Choice('units',[5,10,12,14,15,17,18,20,25,30,35,40]),
                        activation="relu",
                                 input_shape=[XX_train.shape[1]], kernel_regularizer=tf.keras.regularizers.l1(kernels))
                             activity_regularizer=tf.keras.regularizers.l2(kernels) ))

    model.add(keras.layers.Dropout(rate=drop_rate))
    model.add(keras.layers.Dense(1, activation='sigmoid'))
    lr = hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])
    
    model.compile(
        optimizer=keras.optimizers.SGD(lr),
        loss = 'binary_crossentropy',
        metrics = ['accuracy'] )#[tf.keras.metrics.AUC()])
    return model

I know the issue has been posted for a long time but I had the same issue and was able to get through. This works.
