### ISSUE TITLE
What is the best way to accomplish: historys = tuner.search() just like history = model.fit()

### ISSUE THREAD

**Issue by ryq99** [keras-team/keras-tuner#271]
It's a follow up from issue #120, Extracting history from best trained model and viewing progress. 

I want to get the history for each model so that I can create epochs vs. train/val loss plots. In Keras Tuner document, it says as follows:
![image](https://user-images.githubusercontent.com/29682534/78411437-7ed2b780-75c4-11ea-8119-182f39d4aa1e.png)
I'm wondering how can I get them?

**Comment by damhurmuller** [comment]
Same question!

**Comment by ben-arnao** [comment]
```
 def run_trial(self, trial, *args):
        model = self.hypermodel.build(trial.hyperparameters)
        history = train(...)
        trial.metrics.set_history('loss', history.history['loss'])
...

for trial in tuner.oracle.trials:
    trial.metrics.get_history('loss')
```

Set the history on each trial and then later you can iterate over your trials and grab the recorded history.

**Comment by damhurmuller** [comment]
@ben-arnao I'm still try figure out how to do this

```
class MyTuner(kerastuner.engine.tuner.Tuner):
  
  def run_trial(self, trial, train_generator, validation_data=valid_generator, *args, **kwargs):
    model = self.hypermodel.build(trial.hyperparameters)
    reduce_lr = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=4, min_lr=4e-05, verbose=1)
    early_stopping = tf.keras.callbacks.EarlyStopping(monitor="val_loss", verbose=1, patience=10, restore_best_weights=True)
  
    STEP_SIZE_TRAIN=train_generator.n//train_generator.batch_size
    STEP_SIZE_VALID=valid_generator.n//valid_generator.batch_size

    history = model.fit(train_generator, steps_per_epoch=STEP_SIZE_TRAIN,
                        validation_data=valid_generator, validation_steps=STEP_SIZE_VALID, epochs=1, callbacks=[early_stopping, reduce_lr])

    trial.metrics.set_history('loss', history.history['loss'])



tuner = MyTuner(hypermodel=build_model, oracle=kerastuner.oracles.Hyperband(
                                        objective='val_loss',
                                        max_epochs=1,
                                        seed=1), project_name='some_dir')

tuner.search(train_generator, validation_data=valid_generator)
```


After the end of the first epoch I received this error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-51-e77c38c4a905> in <module>()
      5 STEP_SIZE_VALID=valid_generator.n//valid_generator.batch_size
      6 
----> 7 tuner.search(train_generator, steps_per_epoch=STEP_SIZE_TRAIN, validation_data=valid_generator, validation_steps=STEP_SIZE_VALID, epochs=2, callbacks=[early_stopping, reduce_lr])

3 frames
/usr/local/lib/python3.6/dist-packages/kerastuner/engine/metrics_tracking.py in set_history(self, observations)
    107     def set_history(self, observations):
    108         for obs in observations:
--> 109             self.update(obs.value, step=obs.step)
    110 
    111     def get_statistics(self):

AttributeError: 'numpy.float64' object has no attribute 'value'
```

**Comment by ryq99** [comment]
@damhurmuller Thanks for the solution!
@damhurmuller In your code `trial.metrics.set_history('loss', history.history['loss'])`, according to kerastuner source code, the second part should be a list of MetricObservation() objects instead of a list of loss values. One way I think of is to pass something like `trial.metrics.set_history('loss', [MetricObservation(value, step) for step, value in zip(range(len(history.history['loss']), history.history['loss'])])`. I haven't tried out yet, please let me know your updates!

**Comment by damhurmuller** [comment]
@ryq99 Thanks for the feedback!
I ended up changing my approach. I used the tensorboard callback and extracted the logs direct from the directory with a function and it worked for me. Well, this is another approach if anyone wants to know. Thanks!

```
from tensorboard.backend.event_processing import event_accumulator

best_trial = tuner.oracle.get_best_trials()[0].trial_id

def extract_history(best_trial):

  acc = []
  val_acc = []
  loss = []
  val_loss = []

  for set_data in ['train', 'validation']:
    if set_data == 'train':
      ea = event_accumulator.EventAccumulator(logdir + best_trial + '/execution0/' + set_data)
      ea.Reload()
      for i in range(len(ea.Scalars('epoch_loss'))):
        acc.append(ea.Scalars('epoch_acc')[i][2])
        loss.append(ea.Scalars('epoch_loss')[i][2])
        #lr.append(ea.Scalars('epoch_lr')[i][2])

  if set_data == 'validation':
      ea = event_accumulator.EventAccumulator('logs/scalars/' + best_trial + '/execution0/' + set_data)
      ea.Reload()
      for i in range(len(ea.Scalars('epoch_loss'))):
        val_acc.append(ea.Scalars('epoch_acc')[i][2])
        val_loss.append(ea.Scalars('epoch_loss')[i][2])

  return acc, val_acc, loss, val_loss
```

**Comment by Temweka** [comment]
@damhurmuller 

I attempted to follow your method but got the following error message. 

```
NotFoundError                             Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorboard/backend/event_processing/directory_watcher.py in Load(self)
     89         try:
---> 90             for event in self._LoadInternal():
     91                 yield event

8 frames
NotFoundError: Could not find directory logs/scalars/e55e2fb63d3766f38b1fa19c391bc666/execution0/validation

During handling of the above exception, another exception occurred:

DirectoryDeletedError                     Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorboard/backend/event_processing/directory_watcher.py in Load(self)
     94                 raise DirectoryDeletedError(
     95                     "Directory %s has been permanently deleted"
---> 96                     % self._directory
     97                 )
     98 

DirectoryDeletedError: Directory logs/scalars/e55e2fb63d3766f38b1fa19c391bc666/execution0/validation has been permanently deleted
```

Is there a way to ensure the directory is not deleted?

> @ryq99 Thanks for the feedback!
> I ended up changing my approach. I used the tensorboard callback and extracted the logs direct from the directory with a function and it worked for me. Well, this is another approach if anyone wants to know. Thanks!
> 
> ```
> from tensorboard.backend.event_processing import event_accumulator
> 
> best_trial = tuner.oracle.get_best_trials()[0].trial_id
> 
> def extract_history(best_trial):
> 
>   acc = []
>   val_acc = []
>   loss = []
>   val_loss = []
> 
>   for set_data in ['train', 'validation']:
>     if set_data == 'train':
>       ea = event_accumulator.EventAccumulator(logdir + best_trial + '/execution0/' + set_data)
>       ea.Reload()
>       for i in range(len(ea.Scalars('epoch_loss'))):
>         acc.append(ea.Scalars('epoch_acc')[i][2])
>         loss.append(ea.Scalars('epoch_loss')[i][2])
>         #lr.append(ea.Scalars('epoch_lr')[i][2])
> 
>   if set_data == 'validation':
>       ea = event_accumulator.EventAccumulator('logs/scalars/' + best_trial + '/execution0/' + set_data)
>       ea.Reload()
>       for i in range(len(ea.Scalars('epoch_loss'))):
>         val_acc.append(ea.Scalars('epoch_acc')[i][2])
>         val_loss.append(ea.Scalars('epoch_loss')[i][2])
> 
>   return acc, val_acc, loss, val_loss
> ```

**Comment by fantauzzi** [comment]
Writing callbacks or reading from the file systems is unnecessarily convoluted. The `search()` method should save the training history, at least for the optimal hyperparameters, and make it readily available once the optimisation process is complete. 

This functionality would align it more closely with the usability of Keras models, where training and validation histories for the best model are effortlessly accessible after calling `fit()`. Such capability is sorely absent in Keras Tuner.
