### ISSUE TITLE
Tuning input data pipeline built with tf.data

### ISSUE THREAD

**Issue by haifeng-jin** [keras-team/keras-tuner#274]
To support searching the tf.data input pipeline,
I propose a workflow as shown in the following code.

```python
class MyDataPipeline(HyperPipeline):
  def build(self, hp, x, y=None, validation_data=None):
    if isinstance(x, np.array):
      x = tf.data.Dataset.from_tensor_slices(x)
    x = x.map(func1)
    x = x.map(func2)
    return x

tuner = RandomSearch(hypermodel=MyHyperModel, hyperpipeline=MyDataPipeline, ...)
```

One use case of this feature would be people want to search how to slice the timeseries data before feeding into the neural network, which cannot be done with Keras preprocessing layers since it changes the number of instances in the dataset.

**Comment by opokualbert** [comment]
@haifeng-jin I see this issue is closed, does that  mean what you proposed is adopted in keras tuner now? I am facing this kind of problem now. Thank you for bringing this up to the community

**Comment by haifeng-jin** [comment]
It is not. We decided to first make it a AutoKeras feature.
