### ISSUE TITLE
Dynamic number of Layers

### ISSUE THREAD

**Issue by acegilz** [keras-team/keras-tuner#280]
I am trying to optimise a network composed by multiple LSTM layers, using the following code:

```python
def build_model(hp):
    model = Sequential()

    layers = hp.Int("n_layers",0,3)
       
    if layers == 0:
        model.add(LSTM(hp.Int(f"layer_first",32,256,32), input_shape=(train_x.shape[1:])))
    else:
        model.add(LSTM(hp.Int(f"layer_first",32,256,32), input_shape=(train_x.shape[1:]), return_sequences=True))
        
    model.add(Dropout(hp.Float('dropout_first',0,0.5,0.1)))
    model.add(BatchNormalization())

    for i in range(layers):

        if len(range(layers)) > i+1:
            model.add(LSTM(hp.Int(f"layer_{i}",32,256,32), return_sequences=True))
        else:
            model.add(LSTM(hp.Int(f"layer_{i}",32,256,32)))
                      
        model.add(Dropout(hp.Float(f"dropout_{i}",0,0.5,0.1)))
        model.add(BatchNormalization())
        
 

    model.add(Dense(hp.Int(f"relu_neurons",32,256,32), activation='relu'))
    model.add(Dropout(hp.Float('relu_dropout',0,0.5,0.1)))

    model.add(Dense(2, activation='softmax'))

    opt = tf.keras.optimizers.Adam(lr=hp.Float('learning_rate', 1e-4, 1e-2, sampling='log'), decay=1e-6)

    # Compile model
    model.compile(
        loss='sparse_categorical_crossentropy',
        optimizer=opt,
        metrics=['accuracy']
    )

    return model
```

Output:
<img width="334" alt="Screenshot 2020-04-26 04 16 53" src="https://user-images.githubusercontent.com/4284362/80296773-a78a3f00-8775-11ea-9d4f-0525ca008b4a.png">

The problem I have is that it is only defining the weights for layer_0 and layer_1, when there are more layers (n_layers=3 in case of attached summary).

I was expecting layer_2, and layer_3 to also be defined and displayed on the summary results. What values did it assume for those in this trial?? 

The same layer_0 and layer_1 are displayed on trials where no additional lstm layers exist (n_layers = 0).

Another question I have is, is this the more optimised way of handling lstm layers (return_sequences=True)? 
I find this approach very messy (checking the dimension of layers), but was the only way I found to put this working.

**Comment by ben-arnao** [comment]
I'm not sure if this answers your questions but by default any registered parameter (a parameter gets registered when it is first accessed) will have a value assigned for every trial regardless of whether or not that parameter is actually accessed in your model building function. As far as keras-tuner/bayesian optimization is concerned this is a parameter that is used to generate a score.

KT does have the ability to manually define conditional scopes:

https://keras-team.github.io/keras-tuner/documentation/hyperparameters/#conditional_scope-method

which is what you'd need to do if you wanted KT to know if a parameter is active or not.

**Comment by acegilz** [comment]
Thank you for the helpful reply.
