### ISSUE TITLE
 `HyperParameter` not defined.

### ISSUE THREAD

**Issue by pavlexander** [keras-team/keras-tuner#284]
I am building model generator that uses 3 levels of parameters

1. Decides how many **additional LSTM layers** to be added:

```
hp.Int(name='Additional_LSTM_n', min_value=0, max_value=2, step=1)
```

0 = zero layers, 1= one layer, 2 = 2 layers

2. Decides if the LSTM level should have a **Dropout** layer added. **Depends on previous parameter** value. **It  should either be 1 or 2.**
```
hp.Boolean(name=f'Droupout_LSTM_1', parent_name='Additional_LSTM_n', parent_values=[1, 2])
```
3. Decides what kind of **rate** should be used for the dropout layer. **Depends on the previous parameter.** Should only be used if previous parent value is **True**.

```
hp.Choice(name='Dropout_1_rate', values=[0.1, 0.2], default=0.2, parent_name=f'Droupout_LSTM_1', parent_values=True)
```

Upon execution I get following error:

> ValueError: `HyperParameter` named: Droupout_LSTM_1 not defined.

the code to reproduce the issue is:

```
    hp = hp_module.HyperParameters()

    hp.Int(name='Additional_LSTM_n', min_value=0, max_value=2, step=1)
    hp.Boolean(name=f'Droupout_LSTM_1', parent_name='Additional_LSTM_n', parent_values=[1, 2])
    hp.Choice(name='Dropout_1_rate', values=[0.1, 0.2, 0.3, 0.4, 0.5], default=0.2, parent_name=f'Droupout_LSTM_1', parent_values=True)

    print(hp.values)
```

What am I doing wrong? Are the 3-level nested parameters not supported? 

**It is important that step 3. is not run if the step 2. is False. I don't want to end up in a situation when the tuner generates the value for 3. but it is never used because 2. is false.. Otherwise some executions will be duplicated, wasting the GPU usage, time, and not producing any "true" new models.**

**Comment by haifeng-jin** [comment]
```py
import keras_tuner as kt
hp = kt.HyperParameters()

hp.Int(name='Additional_LSTM_n', min_value=0, max_value=2, step=1)
with hp.conditional_scope(parent_name='Additional_LSTM_n', parent_values=[1, 2]):
  hp.Boolean(name=f'Droupout_LSTM_1')
  with hp.conditional_scope(parent_name=f'Droupout_LSTM_1', parent_values=True):
    hp.Choice(name='Dropout_1_rate', values=[0.1, 0.2, 0.3, 0.4, 0.5], default=0.2)

print(hp.values)
```

We did not expect the user would use the `parent_name` or `parent_values` of `hp.Boolean()`.
They are reserved for conditional scopes.

@pavlexander @ssavale-entrata
Does this work for your use case?

**Comment by WhyNotRecord** [comment]
Suggestion with conditional_scope is not working for me in situation:
```
def build(self, param):
....................................
    use_conv = param.Choice('convolution', [True])
....................................
    recurrent_conv = param.Choice('conv_rec', [True, False], parent_name='convolution', parent_values=[True])
....................................
    if use_conv:
....................................
      if recurrent_conv:
        with param.conditional_scope(parent_name='conv_rec', parent_values=True):
          cl_size = param.Int('lrc_size', 32, 64, 32)
          cnorm = param.Choice('conv_rec_norm', ['lnorm', 'no'])
```
I'm still getting the error 
ValueError: `HyperParameter` named: conv_rec not defined.
