### ISSUE TITLE
Callback after each trial

### ISSUE THREAD

**Issue by hadim** [keras-team/keras-tuner#29]
In the same spirit as for `tf.keras.callbacks`, it would be nice to callbacks called at the end of each trial and/or executions.

My use case would be to send a notification to myself but I am sure plenty of other use-cases exist.

I can draft a PR if interested.

**Comment by omalleyt12** [comment]
@hadim the current workflow for this is to subclass the `Tuner` class you are using and override `on_trial_end`

One of the difficulties with having Tuner callbacks in `tuner.search` like with `model.fit` is that `search` has to be able to work with an arbitrary signature. 

Maybe we could have a `tuner_callbacks` argument in Tuner.__init__` though. I think we'd have to determine if there are enough generic use cases to justify this. Thoughts?

**Comment by omalleyt12** [comment]
Closing this out as I think we should standardize on the existing `Tuner.on_trial_end` methods
