### ISSUE TITLE
fix known test failures 

### ISSUE THREAD

**Issue by carchrae** [keras-team/keras-tuner#293]
trying to be a good oss citizen, i spent time to try and understand why my PR was causing a test failure ( `test_override_compile fails` ) .  it turns out that it isn't my code change at all and this test has been failing for a while.

to avoid wasting people's time, i suggest skipping this test.  or fixing it.  fixing it is not feasible for me right this moment, so i submit a pr to put your build back to passing.

update: i found a second test that fails intermittently (due to randomness) and so i have also submitted a PR to make these failures less likely.  (see below)

**Comment by carchrae** [comment]
it appears the trouble started here: https://travis-ci.org/github/keras-team/keras-tuner/jobs/663621018

**Comment by carchrae** [comment]
ok, and more fun.  it seems like a new test condition failed on my pr 

https://github.com/keras-team/keras-tuner/commit/8033a3f656b17634390b367b9c1e94d4646cbede#diff-3aed5876402f6157fe38b07c05b719f2R316

the test result is close: https://github.com/keras-team/keras-tuner/pull/294/checks?sha=c376417ca1792d5eb1a8452399d2cf91280fae83#step:5:187

but then when i re-run the test (with no changes), it passes.  https://github.com/keras-team/keras-tuner/pull/294/checks?check_run_id=658000646

it is challenging testing when there is randomness involved.  there are a few approaches.  

1. widen the test condition (it uses some magic numbers, make them more tolerant), 
2. if the value doesn't meet the test criteria, make the test loop until it does pass

i'm going to go with 1 and hope this makes the test tolerant enough.  my impression is this is a really rough test criteria in the first place.

**Comment by haifeng-jin** [comment]
All the failure in the tests has already been fixed.
I am closing the PR.
Thank you again for your contribution!
