### ISSUE TITLE
How can I manually load a model from a checkpoint?

### ISSUE THREAD

**Issue by phiwei** [keras-team/keras-tuner#300]
My checkpoint directories contain the following files:
- checkpoint
- checkpoint.data-00000-of-00002
- checkpoint.data-00001-of-00002
- checkpoint.index

How can I use these files to manually load the best-step-model?

Thanks!

**Comment by Abhijit-2592** [comment]
@phiwei Did you figure this out?

**Comment by phiwei** [comment]
I ended up just getting the best models in the python process that run the search and saving them again manually.

**Comment by Abhijit-2592** [comment]
@phiwei Oh ok I also did something similar. But I think the problem is the graph is not stored and only the weights are. So if we construct the graph from config we can load the weights
