### ISSUE TITLE
"num_layers" does not match the actual number of layers

### ISSUE THREAD

**Issue by keewawa** [keras-team/keras-tuner#302]
I've tested all the three tuners with the number of layers as a paramter being tuned. However, the num_layers showing in summary seems random, often not equivant to the actual number of layers counted from the entires of number of units. I've also run case 1 in "Hello World" example, it had the same issue - below is the summary of one of the models. Clearly there are more than 4 layers.

```
`[Trial summary]
 |-Trial ID: bb97a37bc6904de12d200f2a98212f20
 |-Score: 0.9328333735466003
 |-Best step: 0
 > Hyperparameters:
 |-learning_rate: 0.001
 |-num_layers: 4
 |-units_0: 64
 |-units_1: 192
 |-units_10: 416
 |-units_11: 160
 |-units_12: 192
 |-units_13: 64
 |-units_14: 512
 |-units_2: 256
 |-units_3: 480
 |-units_4: 512
 |-units_5: 256
 |-units_6: 448
 |-units_7: 320
 |-units_8: 64
 |-units_9: 64`
```

I was wondering if this is a bug or just me misunderstanding the meaning of the "num_layers" here?  thanks!

**Comment by yixingfu** [comment]
I assume you think num_layers=4 to be wrong based on counting the number of units_* hyperparameters.  If a units_* hyperparameter is added before the tuner reaches the best model, it stays in the tuner whether it is actually relevant to the best model or not. 

If you try printing the summary of the model, you will find num_layers actually matches the number of dense layers. For example after running case#1 you can run
```
best_models = tuner.get_best_models()
print(best_models[0].summary())
```

**Comment by keewawa** [comment]
Thanks!

**Comment by rafaelstevenson** [comment]
I have the same issue 
![image](https://user-images.githubusercontent.com/67007111/115365020-2f225680-a1ee-11eb-8ce6-4bad9471c6d7.png)

**Comment by haifeng-jin** [comment]
redirect to:
https://github.com/keras-team/keras-tuner/discussions/521

**Comment by HamedFarahani89** [comment]
I did how you said:

best_model = tuner.get_best_models(num_models=1)[0]
best_hps = tuner.get_best_hyperparameters(1)[0]
print(f"Best Hyperparameters: {best_hps.values}")

the result is Best Hyperparameters: {'num_layers': 1, 'units_0': 96, 'learning_rate': 0.0001, 'units_1': 32, 'units_2': 64, 'units_3': 64, 'units_4': 64} since I feel it means 5 layers of 96, 32, 64, 64, 64 since I have tested between 1 to 5 layers and from 32 nodes to 128 with 32 steps. I am confused.
