### ISSUE TITLE
Allowing ImageDataGenerator Iterator as Input for search

### ISSUE THREAD

**Issue by anirudh-challa** [keras-team/keras-tuner#31]
Currently, x and y are expected as inputs for the `.search` function. Instead could the ImageDataGenerator Iterator be used as input similar to the `fit_model` function of Keras?

**Comment by rodrigocardoso92** [comment]
> Currently, x and y are expected as inputs for the `.search` function. Instead could the ImageDataGenerator Iterator be used as input similar to the `fit_model` function of Keras?

I have the same question

**Comment by sydeaka** [comment]
I'd like to cast another vote to add this feature. Are you guys working on this?

**Comment by puffofsmoke** [comment]
The same bur similar to fit_generator pls.

**Comment by renatovanbeek** [comment]
Is there still a search_generator (or equivalent) as mentioned in the change log of v0.5?
`Added the ability to use generator via the search_generator function`

**Comment by omalleyt12** [comment]
@anirudh-challa The search function should now work with any input that Keras accepts (make sure you are using the [tf.keras version of ImageDataGenerator](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/ImageDataGenerator). This includes generators, etc

Example:

```python
tuner = ...
tuner.search(my_generator(), steps_per_epoch=100, epochs=10)
```

Please reopen if you still see any issues

**Comment by EgorFollia** [comment]
Hello! I am using `from tensorflow.keras.preprocessing.image import ImageDataGenerator`
Here is the code :
>(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train, x_test = x_train.astype('float32') / 255, x_test.astype('float32') / 255
y_train, y_test = to_categorical(y_train), to_categorical(y_test)

>img_gen = ImageDataGenerator(
    rotation_range=10,
    width_shift_range=.1,
    height_shift_range=.1,
    horizontal_flip=True,
    vertical_flip=True,
    fill_mode="nearest"
)

>img_gen_train = img_gen.flow(x_train, y_train, batch_size=128, shuffle=True)

then I am building a model using keras tuner HyperModel:
>def hypermodel(hp):
    units_choice = hp.Int('units', min_value=32, max_value=512, step=32, default=128)
    lr_choice = hp.Float('learning_rate', 1e-5, 1e-2, sampling='LOG', default=1e-3)
    dropout_rate_choice = hp.Float('rate', 0, .5, step=.1, default=.2)
    filters_choice = hp.Choice('num_filters', values=[32, 64], default=64)

>    model = Sequential()
    model.add(Conv2D(filters=16, kernel_size=3, 
                            activation='relu', input_shape=input_shape))
    model.add(Dropout(rate=dropout_rate_choice))
    model.add(Flatten())
    model.add(Dense(units=units_choice, activation='relu'))
    model.add(Dense(num_labels, activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy',
                optimizer=Adam(lr_choice),
                metrics=['accuracy'])

>    return model

After that, in an attempt to search best params :
> rand_tuner.search(img_gen_train, steps_per_epoch=100, epochs=15)

### I got an error : 
Epoch 1/15
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-82-920d6a000f3f> in <module>()
----> 1 rand_tuner.search(img_gen_train, steps_per_epoch=100, epochs=15)

7 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in __call__(self, *args, **kwargs)
   1470         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1471                                                self._handle, args,
-> 1472                                                run_metadata_ptr)
   1473         if run_metadata:
   1474           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Can not squeeze dim[1], expected a dimension of 1, got 10
	 [[{{node metrics/acc/Squeeze}}]]
	 [[loss/mul/_123]]
  (1) Invalid argument: Can not squeeze dim[1], expected a dimension of 1, got 10
	 [[{{node metrics/acc/Squeeze}}]]
0 successful operations.
0 derived errors ignored.

**Comment by rodrigocardoso92** [comment]
Hi dear fellow @EgorFollia, try to generate data inside of hypermodel function and use fit_generator too inside of this function.
