### ISSUE TITLE
ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by OliverFaust** [keras-team/keras-tuner#317]
Hi,

Importing kerastuner fails on my my Jetson TX2. 
Here is the complete trace:
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kerastuner
2020-06-06 15:41:05.390226: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
2020-06-06 15:41:07.658713: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libnvinfer.so.7
2020-06-06 15:41:07.660570: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libnvinfer_plugin.so.7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oliver/Python/keras-tuner/kerastuner/__init__.py", line 20, in <module>
    from . import oracles
  File "/home/oliver/Python/keras-tuner/kerastuner/oracles/__init__.py", line 16, in <module>
    from ..tuners.bayesian import BayesianOptimizationOracle as BayesianOptimization
  File "/home/oliver/Python/keras-tuner/kerastuner/tuners/__init__.py", line 17, in <module>
    from .bayesian import BayesianOptimization
  File "/home/oliver/Python/keras-tuner/kerastuner/tuners/bayesian.py", line 5, in <module>
    from sklearn import exceptions
  File "/home/oliver/.local/lib/python3.6/site-packages/sklearn/__init__.py", line 81, in <module>
    from .utils._show_versions import show_versions
  File "/home/oliver/.local/lib/python3.6/site-packages/sklearn/utils/_show_versions.py", line 12, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
>>> 

Oliver

**Comment by OliverFaust** [comment]
Executing the following, prior to the keras-tuner, prevented the error:
 export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1

**Comment by jxfruit** [comment]
> 
> 
> Executing the following, prior to the keras-tuner, prevented the error:
> export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1

super NB！ TKS buddy！

**Comment by nhochamvui** [comment]
> Executing the following, prior to the keras-tuner, prevented the error:
> export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1

I have to login and +1 for you, many thanks!!!

**Comment by chenxingqiang** [comment]
> LD_PRELOAD

/usr/lib/aarch64-linux-gnu/

**Comment by aurelien-m** [comment]
> Executing the following, prior to the keras-tuner, prevented the error: export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1

In my case I had:

```python
Traceback (most recent call last):
  File "/home/aurelien/.local/lib/python3.6/site-packages/sklearn/__check_build/__init__.py", line 44, in <module>
    from ._check_build import check_build  # noqa
ImportError: /home/aurelien/.local/lib/python3.6/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block
```

So exporting this path `export LD_PRELOAD=/home/aurelien/.local/lib/python3.6/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0` worked

**Comment by Samuel-wei** [comment]
> > Executing the following, prior to the keras-tuner, prevented the error: export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
> 
> In my case I had:
> 
> ```python
> Traceback (most recent call last):
>   File "/home/aurelien/.local/lib/python3.6/site-packages/sklearn/__check_build/__init__.py", line 44, in <module>
>     from ._check_build import check_build  # noqa
> ImportError: /home/aurelien/.local/lib/python3.6/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block
> ```
> 
> So exporting this path `export LD_PRELOAD=/home/aurelien/.local/lib/python3.6/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0` worked

I have got the similar error, don't worked in my case.
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 16
     14 import shutil
     15 import imp
---> 16 import cv2
     17 import sys
     18 import os

ImportError: [/opt/conda/envs/yoltv4/lib/python3.8/site-packages/../.././libgomp.so.1](https://vscode-remote+ssh-002dremote-002bo312y60925-002egoho-002eco.vscode-resource.vscode-cdn.net/opt/conda/envs/yoltv4/lib/libgomp.so.1): cannot allocate memory in static TLS block
```

**Comment by Potabk** [comment]
> Executing the following, prior to the keras-tuner, prevented the error: export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1

nuibility!!!!
