### ISSUE TITLE
Request for roadmap / projects for contributions

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [keras-team/keras-tuner#32]
Thank you for building this yet another awesome software for humans :-)
Can I request issues / projects listing roadmap / call for contributions? This would help many of us to get involved easily by starting with tasks that is necessary for the project.

Thanks,

**Comment by omalleyt12** [comment]
@sandeep-krishnamurthy Thanks, yes definitely! There is a monthly Keras community meeting you can get invited to by joining the [mailing list](https://groups.google.com/a/tensorflow.org/forum/#!forum/keras-meetings). Project roadmaps are discussed extensively there. The [Keras governance charter](https://github.com/keras-team/governance/blob/master/README.md) has some good info as well.

Also we'll make sure to mark issues in this repo with the "good first issue" where appropriate
