### ISSUE TITLE
Behavior of bayesian tuner when initial points have same score

### ISSUE THREAD

**Issue by yixingfu** [keras-team/keras-tuner#326]
This test case `test_bayesian_oracle_with_zero_y` (https://github.com/keras-team/keras-tuner/blob/master/tests/kerastuner/tuners/bayesian_test.py#L51) fails not necessarily with y=0; but whenever the randomly chosen initial points have the same score. Having identical `y` makes normalization of `y` vector singular and produce NaN. 

This should be a simple fix.  But what behavior should we expect when such situation happens? I can think of a few possibilities:
1. Do one more random trial until the Gaussian regression works;
2. Not normalizing y, either (a) for all cases or (b) whenever the singular situation happens;
3. Perturb score slightly for the initial points to avoid identical scores.

**Comment by ben-arnao** [comment]
I mean the real question is why do all of your initialization points have the same score. I think that is usually indicative of something being wrong with the target function. However if you do have a reason to believe this is normal and fine, we can make a slight adjust to continue generating random points until all scores are not equal.

In `kerastuner/tuners/bayesian.py`

```
if len(completed_trials) < num_initial_points or len(set([trial.score for trial in self.trials])) <= 1:
    return self._random_populate_space()
```

**Comment by yixingfu** [comment]
@ben-arnao Yes I agree with you, and that is why I think this test case is highly unnatural.
I just thought removing a test case because it fails sounds like a bad practice, so I tried to come up a more consistent way to get around the test case. As far as I see, what you suggest is similar to approach (1) I mentioned.
