### ISSUE TITLE
HyperResNet compilation failure during tuner.search()

### ISSUE THREAD

**Issue by rahulroynit** [keras-team/keras-tuner#333]
![image](https://user-images.githubusercontent.com/42096686/85431905-d0755780-b59f-11ea-9971-588bdc69cb95.png)

**Comment by rahulroynit** [comment]
I'm using the HyperResNet class for image classification. I've used the ImageDataGenerator() to generate training and validation generators and then passing them to tuner.search() when it throws this error.

**Comment by yixingfu** [comment]
When `include_top=False` it is indeed not compiled because more layers are expected to be added as top. You can override the `build` method to (maybe add layers and) compile. 

I think you can do 
```
class MyHyperResNet(HyperResNet):
    def build(self, hp):
        model = super().build(hp)
        ## then add some top layers to the model, if needed
        # model = Sequential([model, Dense(10)])
        ## compile
        model.compile(optimizer=optimizer,
                loss='categorical_crossentropy',
                metrics=['accuracy'])
```

**Comment by rahulroynit** [comment]
Thanks! I totally missed the final section of the code.
