### ISSUE TITLE
Hyperparameter in Data?

### ISSUE THREAD

**Issue by dgrahn** [keras-team/keras-tuner#335]
All,

It does not appear that keras-tuner support hyperparameters outside of the model. For instance, adjusting image augmentation hyperparams.

Is this correct?

**Comment by ben-arnao** [comment]
You can subclass to create your own training routines. You define all your params within your build model function. You can then access your params from elsewhere.

```
def build_model(hp):
    # here i define a parameter to later be used in training
    hp.Choice('batch_size', [64, 128, 256])
    
    # here i build and return a model
    """build model"""
    return model


class MyTuner(kt.Tuner):

    def run_trial(self, trial, ...):
        model = self.hypermodel.build(trial.hyperparameters)
        
        # here i can access params and use them in my training logic
        # all that KT really requires us to do is given a model, return a score
        batch_size = trial.hyperparameters.values['batch_size']
        
        score = ...
        self.oracle.update_trial(trial.trial_id, {'score': score})
        self.oracle.save_model(trail.trial_id, model)
```

**Comment by yixingfu** [comment]
Another option is incorporating image augmentation into the model. You can implement some Lambda layer, or try out data preprocessing layers (https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/PreprocessingLayer, keep in mind they are still experimental though).

**Comment by dgrahn** [comment]
@ben-arnao That will work. Thank you.
