### ISSUE TITLE
Contributing to Keras-Tuner

### ISSUE THREAD

**Issue by mikkokotila** [keras-team/keras-tuner#34]
Great to see hyperparameter tuning is handled at the source going forward :) 

I've spent some years working on the problem specifically focused on Keras models, some of which is visible in [Talos](http://github.com/autonomio/talos). Related with this, I have two questions: 

1) Is there something I can help with? 

2) Can I learn more about Keras-Tuner roadmap/strategy somewhere, as it will help us align our development efforts better with Talos, where the focus is more broadly the automation / workflow improvements as opposed to strictly finding hyperparameters for a Keras model

**Comment by omalleyt12** [comment]
@mikkokotila Thanks, yes definitely! There is a monthly Keras community meeting you can get invited to by joining the [mailing list.](https://groups.google.com/a/tensorflow.org/forum/#!forum/keras-meetings) Project roadmaps are discussed extensively there. The [Keras governance charter](https://github.com/keras-team/governance/blob/master/README.md) has some good info as well.

Also we'll make sure to mark issues in this repo with the "good first issue" where appropriate
