### ISSUE TITLE
BayesianOptimization does not allow for custom alpha & beta values

### ISSUE THREAD

**Issue by MariaPoliti** [keras-team/keras-tuner#347]
I was trying to use the `BayesianOptimization` search function and wanted to use user-defined values for alpha and beta. 
However, when values were passed as keyword arguments, the `multi_execution_tuner` produces error of "__init__ got an unexpected keyword argument _'alpha'_ "

Upon analysis of the code, we found that the `BayesianOptimization` function passes all its argument but _alpha_ or _beta_ to the `multi_execution_tuner` function. 

[ Check build # 380 on the 'kt_issue' branch of the [repo] (https://github.com/EISy-as-Py/hardy/tree/kt_issue) ]

Thank you in advance for the help!

**Comment by yixingfu** [comment]
I opened a PR to fix this. 

Temporarily you can initiate bayesian oracle first and use it to construct tuner. An example would be:
```
tuner = multi_execution_tuner.MultiExecutionTuner(
        oracle=Bayesian(
            objective='accuracy',
            max_trials=1,
            alpha=0.1),
        hypermodel=build_model)
```
