### ISSUE TITLE
Tuner stopping unexpectedly with "Oracle triggered exit"

### ISSUE THREAD

**Issue by ppurwar** [keras-team/keras-tuner#35]
I am using keras-tuner with tf2.0_beta version. Its works perfectly for small number (5-10) of trials.
But when I use a large number of trials, it stops.

bs = batch_sizes[0]
tuner = RandomSearch(mymodel,
                     objective='val_accuracy',
                     max_trials=60,
                     executions_per_trial=3,
                     directory='./multiclass_classifier/training',
                     project_name='search_bs{}'.format(bs))

tuner.search(x=ds_train['pixels'], y=train_labels, batch_size=bs, epochs=10, 
              validation_data=(ds_val['pixels'], val_labels))

The tuner optimizes for around 13 trials and then exit showing this error "Oracle triggered exit".
I tried running it but it exists every time.

![Screenshot from 2019-07-18 11-02-10](https://user-images.githubusercontent.com/15076532/61444396-9d682400-a94b-11e9-8c16-e776174983bf.png)

**Comment by ppurwar** [comment]
I figured out that due to a small search space the RandomSearch had more than 5 collisons and thus triggered 'exit'. I think this is the limitation of RandomSearch. Is there any option to avoid collisions?

**Comment by Anas-coder** [comment]
dealing with the same issue

**Comment by miladce** [comment]
> https://stackoverflow.com/a/62371179/9076044

Try adding the **`directory`** kwarg where you have defined your tuner, or if you have already added **`directory`** kwarg, try changing the value of that kwarg. regard the last line in the below example of `RandomSearch` tuner:

```
    tuner = RandomSearch(
        tune_rnn_model,
        objective='val_accuracy',
        seed=SEED,
        max_trials=MAX_TRIALS,
        directory='**change-this-value**',
    )
```

**Comment by AlexanderLauf** [comment]
I am dealing with the same issue.

```
Search space summary
Default search space size: 4
dimension (Int)
{'default': None, 'conditions': [], 'min_value': 8, 'max_value': 32, 'step': 1, 'sampling': None}
optimizer (Choice)
{'default': 'adam', 'conditions': [], 'values': ['adam', 'sgd', 'rmsprop'], 'ordered': False}
learning_rate (Choice)
{'default': 0.01, 'conditions': [], 'values': [0.01, 0.001, 0.0001], 'ordered': True}
depth (Int)
{'default': None, 'conditions': [], 'min_value': 0, 'max_value': 5, 'step': 1, 'sampling': None}
```
Hyperband Search stops after 94 trials with the following information:
_INFO:tensorflow:Oracle triggered exit_

Actually, the performance of the selected model is good enough for me.
But **what** exactly triggers the exit? What is the meaning of the message?
Unfortunately, there is no information available...

**Comment by haifeng-jin** [comment]
To my understanding, the reason is when the oracle cannot generate a different set of hyperparameters, it is triggered exit.
The oracle cannot generate new hyperparameters is because, for most of the algorithms, the new hyperparameters are generated randomly. When most of the search space is already evaluated, the newly generated ones are likely to be the old ones. After exceeding a certain limit, the oracle gives up.
