### ISSUE TITLE
Handling division by zero

### ISSUE THREAD

**Issue by SHASHANK-PRO-05** [keras-team/keras-tuner#381]
https://github.com/keras-team/keras-tuner/blob/a17321428a55975f55acb5b9270d6d73ea11dcc9/kerastuner/engine/hyperparameters.py#L1064

Hey team,
There should be the handling of division by zero here.

**Comment by yixingfu** [comment]
@haifeng-jin @omalleyt12 
I can think of a few solutions of this:
1. automatically turn anything with same min/max to `Fixed`
2. since this is only used in bayesian, we can make `_nonfixed_space` in bayesian tuner to recognize it as fixed space
3. assign 1 (or any number) to this
What do you think?

**Comment by haifeng-jin** [comment]
@yixingfu I think the third solution would be the best.
For the first one, it would confuse the user if we change the hp type under the hood.
For the second one, we may use in other tuners in the future as well, not only bayesian.

Thanks.

**Comment by yixingfu** [comment]
@haifeng-jin Thanks for the input. BTW should we also check `value` to be between min and max here?

**Comment by haifeng-jin** [comment]
@yixingfu That would be even better. The check should be done when creating the hyperparam.

**Comment by yixingfu** [comment]
> @yixingfu That would be even better. The check should be done when creating the hyperparam.

That is still not safe, Bayesian oracle may potentially create a trial with value out of bound (or am I missing anything?) and these values are set into `hps.values` without going through hyperparam creation.

**Comment by yixingfu** [comment]
I'd say we can throw an error here if value is not in bound, wdyt

**Comment by PiotrAntoniak** [comment]
In case if someone is wondering if it has been fixed - it just happened to me a second ago. However, overwriting  the project fixes that.
