### ISSUE TITLE
RuntimeError: You must compile your model before training/testing. Use `model.compile(optimizer, loss)` with RandomSearch

### ISSUE THREAD

**Issue by CamilleBV** [keras-team/keras-tuner#397]
Hello, 

I am trying to use hyperparameters for my LSTM model.
I got an error when I am calling tuner.search after using RandomSearch (but not when I am using Hyperband). 
Do you have any idea about the reason ? 

![image](https://user-images.githubusercontent.com/70316872/91416820-34dabe80-e850-11ea-9b86-72eddc444f38.png)
![image](https://user-images.githubusercontent.com/70316872/91416874-46bc6180-e850-11ea-80a4-678b2ac81bce.png)
![image](https://user-images.githubusercontent.com/70316872/91416908-50de6000-e850-11ea-873c-30cff1367ca7.png)
![image](https://user-images.githubusercontent.com/70316872/91416947-5e93e580-e850-11ea-884f-e01eb9805aa3.png)
![image](https://user-images.githubusercontent.com/70316872/91416983-69e71100-e850-11ea-923e-cd6c3b403fa9.png)
![image](https://user-images.githubusercontent.com/70316872/91417006-74090f80-e850-11ea-8927-773f43a0573f.png)

If you need anything else, please let me know

Thank you

**Comment by yixingfu** [comment]
You need to include `model.compile()` in your `build_model` function.  But I am curious why hyperband does not have the problem

**Comment by brennenhuang** [comment]
In RandomSearch, you should replace build_model to model
