### ISSUE TITLE
Reusing my existing model code in Keras Tuner

### ISSUE THREAD

**Issue by relativeflux** [keras-team/keras-tuner#407]
Thanks for what seems to be an amazing tool for productivity in ML/Keras/TF, which I'm looking forward to using. I just have one concern... All of the examples I have seen involve defining a model insde the build function. I guess many users will already have model code they wish to tune, but is there any way to reuse such code inside the build function? My own model lives in 3 separate source files, and it seems a daunting prospect (as well as wasteful and potentially error-prone) to have to redefine all of that again. What I was hoping to be able to do was pass hyperparameters in through the top-level arguments of my existing model, somewhat like this:

```
def build_model(hp):
    model = MyExistingModel(
        batch_size=hp.Choice('batch_size', [16, 32, 64, 128]),
        seq_len=hp.Choice('seq_len', [1024, 2048]),
        rnn_hidden_units=hp.Choice('hidden_units', 512, 1024),
        rnn_type='gru',
        num_rnn_layers=hp.Choice('num_rnn_layers', [2,4,8])
    )
    optimizer = optimizer_factory['adam'](
        learning_rate=hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])
    )
    model.compile(
        optimizer=optimizer,
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy'],
    )
    return model
```

Is this an accepatable pattern in Keras Tuner? I mean I just don't know, I've never seen it... If not, is the only alternative to rewrite all my code?

**Comment by yixingfu** [comment]
Yes you can do that. As long as the usage of `hp` is passed through `build_model` function, you can use these as argument to functions already defined elsewhere.

**Comment by relativeflux** [comment]
@yixingfu Thank you, as I suspected - just thought I'd check!

Chris
