### ISSUE TITLE
how to do exhaustive search of all possible combinations?

### ISSUE THREAD

**Issue by peacej** [keras-team/keras-tuner#408]
Let's say I'm only using `hp.Choice()`. Is there any way to ensure exhaustively trying all possible combinations of hyperparameter values? Of course sometimes I want to use more advanced/efficient techniques, but not always. Thanks~

**Comment by yixingfu** [comment]
Random search with a rather large `max_trial` does the job. Random search ensures non repeating search, and will exit if not possible to populate next search space

**Comment by edumucelli** [comment]
I have made a PR to add an exhaustive search tuner #712 to do exactly what you are looking for @peacej. If the maintainers are positive about it will be possible out of the box.
