### ISSUE TITLE
HyperParameters.get(): should raise KeyError rather than ValueError when name is not Found

### ISSUE THREAD

**Issue by alexandrehuat** [keras-team/keras-tuner#411]
Let ``hp`` be an empty ``HyperParameters`` container. When calling ``hp.get('anything')`` or ``hp['anything']``, a ``ValueError`` is raised. It would be more pythonic if it raised a ``KeyError``.

``HyperParameters`` objects are ``dict``-like containers . A ``dict`` would raise a ``KeyError``.

*keras-tuner version: 1.0.1*

**Comment by meteoDaniel** [comment]
@alexandrehuat and @jpodivin @haifeng-jin , I am having a strange problem with the `HyperParameter` class.
This problem occurs only on my machine and I do not know why. 

We are creating a `HyperParameters` class instance and defining some `Fixed` and `Choice` values. 
Somehow the class lost these values and I receive: 

```python
  File "/usr/local/lib/python3.8/dist-packages/keras_tuner/engine/hypermodel.py", line 127, in build
    model = self.hypermodel.build(hp)
  File "/usr/local/lib/python3.8/dist-packages/generic_model/modules/modelling/algorithms.py", line 68, in linear_regression
    optimizer=TF_OPTIMIZER_DICT[parameter_optimization.get(TUNER_KEY_OPTIMIZER)](
  File "/usr/local/lib/python3.8/dist-packages/keras_tuner/engine/hyperparameters.py", line 744, in get
    raise KeyError("{} does not exist.".format(name))
KeyError: 'optimizer does not exist.'
```
`TUNER_KEY_OPTIMIZER='optimizer' ` and TF_OPTIMIZER_DICT is just a mapping between a string and a tensorflow optimizer (here we use `Adam`) 

Do you have any ideas where I have to search for the origin of this issue?
At least the images are identically between the machine of my colleague and mine.  But my run is failing.
