### ISSUE TITLE
KerasTuner doesn't work with LSTM

### ISSUE THREAD

**Issue by TheRed86** [keras-team/keras-tuner#443]
First of all, I want to thank everybody for this amazing repository! 

I am trying to tune a Recurrent network with LSTM kernel. I get the following error:
`RuntimeError: Too many failed attempts to build model.`
I am only trying to tune the number of layers and number of neurons for layers. The same works with Dense layer.

Is it possible to use KerasTuner with LSTM layers?

Thanks

**Comment by beansrowning** [comment]
Not a maintainer, but how did you handle the `return_sequences` parameter in your LSTM layers?

Adding recurrent layers dynamically will require you to also dynamically determine which ones need to return sequences and which should return the final output, or the shape will be incorrect. I.e. LSTM->LSTM requires `return_sequences=True`

**Comment by my-hub30** [comment]
> Not a maintainer, but how did you handle the `return_sequences` parameter in your LSTM layers?
> 
> Adding recurrent layers dynamically will require you to also dynamically determine which ones need to return sequences and which should return the final output, or the shape will be incorrect. I.e. LSTM->LSTM requires `return_sequences=True`

Hello. My network is LSTM->LSTM->LSTM->Dense layer.  Between LSTM->LSTM, I add ''return_sequences=True''.
But it shows ''ValueError: Objective value missing in metrics reported to the Oracle, expected: ['accuracy'], found: dict_keys(['loss', 'val_loss']) '' 
Do you have this problem? Thx.

**Comment by HoneyHY** [comment]
> > Not a maintainer, but how did you handle the `return_sequences` parameter in your LSTM layers?
> > Adding recurrent layers dynamically will require you to also dynamically determine which ones need to return sequences and which should return the final output, or the shape will be incorrect. I.e. LSTM->LSTM requires `return_sequences=True`
> 
> Hello. My network is LSTM->LSTM->LSTM->Dense layer. Between LSTM->LSTM, I add ''return_sequences=True''.
> But it shows ''ValueError: Objective value missing in metrics reported to the Oracle, expected: ['accuracy'], found: dict_keys(['loss', 'val_loss']) ''
> Do you have this problem? Thx.

The metrics are inconsistent with dict_key. Maybe you can change metrics to 'loss', or change dict_keys to 'accuracy'.

**Comment by haifeng-jin** [comment]
I think this is related to wrong usage of Keras API.
If you are able to implement it in Keras but not KerasTuner, please reopen this issue.
