### ISSUE TITLE
Readability of tuner summaries with dark theme

### ISSUE THREAD

**Issue by philosofool** [keras-team/keras-tuner#444]
It is hard to read the output of a tuner .results_summary() or .search_space_summary() in jupyter notebook with a dark theme. I looked though some of the to figure out how to configure the formatting but didn't find it. 

(I would be glad to contribute fixes if I can make any that work, but a tip on where to start would be helpful)

**Comment by haifeng-jin** [comment]
This problem is resolved with the latest release of Keras Tuner 1.0.2.
