### ISSUE TITLE
How Do I Use HyperEfficientNet

### ISSUE THREAD

**Issue by impulsecorp** [keras-team/keras-tuner#445]
I can use HyperResNet and HyperXception fine by loading them like:
from kerastuner.applications import HyperResNet, HyperXception
but it gives an error when I load:
from kerastuner.applications import HyperEfficientNet

I am using your latest V1.02 in Google Colab.

**Comment by haifeng-jin** [comment]
Thanks for the issue.
I don't see an error. Would you paste your error message?

**Comment by impulsecorp** [comment]
It was 3 months ago so I am not sure what the error was, but it is probably fixed by now.
