### ISSUE TITLE
Objective value missing in metrics - Error arises while optimization procedure is already running since minutes

### ISSUE THREAD

**Issue by tobilab** [keras-team/keras-tuner#464]
Using KerasTuners `BayesianOptimization` with the objective `val_categorical_accuracy` runs optimization procedure for some minutes in a expected way (looking the optimization progress at console prints) Than the following error occurs:
`ValueError: Objective value missing in metrics reported to the Oracle, expected: ['val_categorical_accuracy'], found: dict_keys(['loss', 'source_classification_loss', 'shared_dense1_layers_loss', 'shared_dense2_layers_loss', 'shared_dense3_layers_loss', 'source_classification_categorical_accuracy', 'val_loss', 'val_source_classification_loss', 'val_shared_dense1_layers_loss', 'val_shared_dense2_layers_loss', 'val_shared_dense3_layers_loss', **'val_source_classification_categorical_accuracy'**])` 

I can not understand how the error can be fixed since the procedure seems to work well for some time. In the HyperparameterModel the corresponding metric is defined as:
`myModel.compile(optimizer=optimizers.Adam(1e-3),
                       loss=['categorical_crossentropy'],
                       loss_weights = [classification_weight],
                       metrics={"source_classification":"categorical_accuracy"})`

Can anyone please give help?

**Comment by tobilab** [comment]
Setting the following as the `objective` argument of the tuner: kerastuner.Objective("val_**layername**_accuracy", direction="min") is a workaround to avoid the above error.

**Comment by my-hub30** [comment]
> Setting the following as the `objective` argument of the tuner: kerastuner.Objective("val_**layername**_accuracy", direction="min") is a workaround to avoid the above error.

Hi, may I know how you solve the problem? I have the same error.

But I add ''kerastuner.Objective("val_layername_accuracy", direction="min")'' after tuner, this error is still there.
Thx very much!


def model_builder(hp):
    model = Sequential()
    hp_units1 = hp.Int('units', min_value=30, max_value=50, step=5, default=40)
    model.add(LSTM(units = hp_units1, return_sequences = True, input_shape = (X.shape[1], 1)))
    model.add(Dropout(0.2))
    hp_units3 = hp.Int('units', min_value=20, max_value=50, step=5, default=30)
    model.add(LSTM(units = hp_units3,return_sequences = False))
    model.add(Dropout(0.2))
    model.add(Dense(units = 1))
    hp_learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4, 1e-5, 1e-6])
    model.compile(optimizer = Adam(learning_rate=hp_learning_rate),
                  loss = 'mean_squared_error')
    print(model.summary())
    return model

tuner = kt.Hyperband(model_builder,
                     objective='accuracy',
                     max_epochs=10,
                     factor=3,
                     overwrite=True)

kt.Objective("val_layername_accuracy", direction="min")

**Comment by jeshan-coder** [comment]
Hello, i was facing same problem . Here is solution:-
step 1:- Add metrics in compile eg:- metrics=['accuracy']
step2:-Inside Hyperband add objective=kt.Objective('accuracy',direction='max')
