### ISSUE TITLE
Keras tuner mismatch in the output

### ISSUE THREAD

**Issue by LinusJ79** [keras-team/keras-tuner#465]
I know this has been brought up before but i thought it was solved.

What does this mean?
How do i read this? It says num_layers = 2 but lists 5 dense layers with units.

Results summary
Objective(name='val_accuracy', direction='max')
Trial summary
Hyperparameters:
num_layers: 2
units0: 512
dropout0: 0.15
learning_rate: 0.001
units1: 512
dropout1: 0.5
units2: 144
dropout2: 0.5
units3: 416
dropout3: 0.5
units4: 80
dropout4: 0.5
Score: 0.8911564548810323

**Comment by rafaelstevenson** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/67007111/115362105-6a6f5600-a1eb-11eb-8235-0caba695531a.png)

**Comment by haifeng-jin** [comment]
Redicrect to:
https://github.com/keras-team/keras-tuner/discussions/521
