### ISSUE TITLE
The model to be optimized cannot contain two or more layers of LSTM

### ISSUE THREAD

**Issue by guang7400613** [keras-team/keras-tuner#470]
When I use LSTM to do regression problems, I use keras tuner to optimize the parameters. I find that the model can not contain two or more LSTM layers, only one LSTM layer. If it is more than one LSTM layer, an error will be reported

**Comment by my-hub30** [comment]
Hello, have you fixed the problem already?  I also have the same problem. Stuck for a long time = =#

**Comment by haifeng-jin** [comment]
Are you able to build the model with plain Keras without hyperparameters?
