### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.distribute' has no attribute 'TPUStrategy'

### ISSUE THREAD

**Issue by pshrini** [keras-team/keras-tuner#471]
I am running Tensorflow 2.2 and Kerastuner 1.0.2. I am trying to implement it on LSTM model.

I get this error during search.

Search: Running Trial #1

Hyperparameter    |Value             |Best Value So Far 
units             |608               |?                 
learning_rate     |0.0013            |?                 
dropout           |0.2               |?                 

Traceback (most recent call last):
  File "pd_path_create_lstm_modeldev_kt.py", line 97, in <module>
    **tuner_rs.search(X_train,Y_train,epochs=10,validation_split=0.2)**
  File "/software/python/sles12/lib/python3.8/site-packages/kerastuner/engine/base_tuner.py", line 131, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/software/python/3.8.3/lib/python3.8/site-packages/kerastuner/engine/multi_execution_tuner.py", line 77, in run_trial
    filepath=self._get_checkpoint_fname(
  File "/software/python/3.8.3/lib/python3.8/site-packages/kerastuner/engine/tuner.py", line 317, in _get_checkpoint_fname
    if (isinstance(self.distribution_strategy, tf.distribute.TPUStrategy) and
**AttributeError: module 'tensorflow._api.v2.distribute' has no attribute 'TPUStrategy'**

**Comment by pshrini** [comment]
I probably need to update to Tensorflow 2.4 for getting this error out. But is there a way I can manage with 2.2 and still run this. Thanks

**Comment by pshrini** [comment]
I was able to install tf 2.4 and this solved the case. But kerastuner 1.0.2 won't work without tf 2.4 since looks for TPUStrategy attribute present only in tf 2.3 and later.

**Comment by Mrmdzz** [comment]
strategy = tf.distribute.**experimental**.TPUStrategy(tpu)

**Comment by YALE-Neuro-Genetics** [comment]
I did update tf and I still have the same problem. Any ideas ?
