### ISSUE TITLE
Random search Oracle exits

### ISSUE THREAD

**Issue by MateiG** [keras-team/keras-tuner#486]
I believe this is a similar issue to #35 - in that using Random Search has a problem with the number of "collisions". Could someone explain to me how to properly address this problem? Random search doesn't check configs that it has already tested, right?  It was my undertanding that, should "max_trials" be set high enough, all possible configurations would be tested with this method.

**Comment by haifeng-jin** [comment]
It randomly generates new hyperparameter value combinations. If the generated values are already tried before, it is a collision.

**Comment by MateiG** [comment]
Thanks for the explanation. That being said I imagine it might be a better package overall if it avoided having the collision exit feature and instead kept going. In practice the next random hyperparameter configuration should only be taken from the remaining search space.
