### ISSUE TITLE
BayesianOptimization Error about indexing

### ISSUE THREAD

**Issue by tykimos** [keras-team/keras-tuner#49]
I got a error at second trial owing to index.

### Source Code

from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
(x, y), (val_x, val_y) = keras.datasets.mnist.load_data()
x = x.astype('float32') / 255.
val_x = val_x.astype('float32') / 255.
x = x[:10000]
y = y[:10000]

def build_model(hp):
    model = keras.Sequential()
    model.add(layers.Flatten(input_shape=(28, 28)))
    for i in range(hp.Range('num_layers', 2, 20)):
        model.add(layers.Dense(units=hp.Range('units_' + str(i), 32, 512, 32),
                               activation='relu'))
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(
        optimizer=keras.optimizers.Adam(
            hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy'])
    return model

from kerastuner.tuners import BayesianOptimization
tuner = BayesianOptimization(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    executions_per_trial=3,
    directory='test_dir')
tuner.search_space_summary()
tuner.search(x=x,
             y=y,
             epochs=3,
             validation_data=(val_x, val_y))
tuner.results_summary()

### Output
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-a6f27713d7fd> in <module>()
     13              y=y,
     14              epochs=3,
---> 15              validation_data=(val_x, val_y))
     16 
     17 tuner.results_summary()

3 frames
/usr/local/lib/python3.6/dist-packages/kerastuner/tuners/bayesian.py in _get_training_data(self)
    160             for name, value in values.items():
    161                 index = self._get_hp_index(name)
--> 162                 hp = self.space[index]
    163                 if isinstance(hp, hp_module.Choice):
    164                     value = hp.values.index(value)

TypeError: list indices must be integers or slices, not NoneType

**Comment by rcmagic1** [comment]
I'm seeing the same thing.
I'm also getting errors because hp.Int() appears to be returning float64 type instead of int sometimes:

```
num_fc_layers_min  = 1
num_fc_layers_max  = 4
for i in range( hp.Int('num_fc_layers',min_value=num_fc_layers_min,max_value=num_fc_layers_max+1) )
```

TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by omalleyt12** [comment]
@rcmagic1 @tykimos are you still seeing these errors with the version on the master branch?

**Comment by speekflayder** [comment]
> @rcmagic1 @tykimos are you still seeing these errors with the version on the master branch?

yep, still have it

**Comment by omalleyt12** [comment]
This should be fixed in the master branch now, the code below ran for me (note that `Range` has been changed to `Int` for v1, but other than that I made no changes in the code below):

```python
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

(x, y), (val_x, val_y) = keras.datasets.mnist.load_data()
x = x.astype('float32') / 255.
val_x = val_x.astype('float32') / 255.
x = x[:10000]
y = y[:10000]

def build_model(hp):
    model = keras.Sequential()
    model.add(layers.Flatten(input_shape=(28, 28)))
    for i in range(hp.Int('num_layers', 2, 20)):
        model.add(layers.Dense(units=hp.Int('units_' + str(i), 32, 512, 32),
                            activation='relu'))
    model.add(layers.Dense(10, activation='softmax'))
    model.compile(
        optimizer=keras.optimizers.Adam(
        hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy'])
    return model

from kerastuner.tuners import BayesianOptimization

tuner = BayesianOptimization(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    executions_per_trial=3,
    directory='test_dir')
tuner.search_space_summary()
tuner.search(x=x,
    y=y,
    epochs=3,
    validation_data=(val_x, val_y))
tuner.results_summary()
```

**Comment by rcmagic1** [comment]
Hi @omalleyt12 
This issue appears to be fixed for me on master now.
Thank you.
