### ISSUE TITLE
Specifing multiple layers in model 

### ISSUE THREAD

**Issue by OriAlpha** [keras-team/keras-tuner#504]
I am tried to keras-tune LSTM model but i can only see that the first layer units are defined so is this is a correct way of defining model 

```py
    model = keras.models.Sequential()

    for i in range(hp.Int('layers', 3, 16)):
        model.add(layers.Bidirectional(layers.LSTM(units=hp.Int('units_' + str(i), 16, 64, step=16),activation='relu',return_sequences=True)))
        model.add(layers.Bidirectional(layers.LSTM(units=hp.Int('units_' + str(i), 126, 256, step=16), activation='relu', return_sequences=True)))
        model.add(layers.Bidirectional(layers.LSTM(units=hp.Int('units_' + str(i), 256, 512, step=16), activation='relu',return_sequences=True)))
    model.add(layers.Dropout(hp.Float("dropout", 0.4, 0.5, step=0.1)))
    model.add(layers.Dense(num_classes,activation='softmax'))

    model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate',values=[1e-2, 1e-3, 1e-4])),
                    loss='binary_crossentropy',
                    metrics=['accuracy'])
```

**Comment by haifeng-jin** [comment]
The name would have to be different.
You can try the following.

```py
 model = keras.models.Sequential()

    for i in range(hp.Int('layers', 3, 16)):
        model.add(layers.Bidirectional(layers.LSTM(units=hp.Int('units_1_' + str(i), 16, 64, step=16),activation='relu',return_sequences=True)))
        model.add(layers.Bidirectional(layers.LSTM(units=hp.Int('units_2_' + str(i), 126, 256, step=16), activation='relu', return_sequences=True)))
        model.add(layers.Bidirectional(layers.LSTM(units=hp.Int('units_3_' + str(i), 256, 512, step=16), activation='relu',return_sequences=True)))
    model.add(layers.Dropout(hp.Float("dropout", 0.4, 0.5, step=0.1)))
    model.add(layers.Dense(num_classes,activation='softmax'))

    model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate',values=[1e-2, 1e-3, 1e-4])),
                    loss='binary_crossentropy',
                    metrics=['accuracy'])
```

**Comment by OriAlpha** [comment]
Thanks for your answer it worked

**Comment by my-hub30** [comment]
> The name would have to be different.
> You can try the following.
> 
> ```python
>  model = keras.models.Sequential()
> 
>     for i in range(hp.Int('layers', 3, 16)):
>         model.add(layers.Bidirectional(layers.LSTM(units=hp.Int('units_1_' + str(i), 16, 64, step=16),activation='relu',return_sequences=True)))
>         model.add(layers.Bidirectional(layers.LSTM(units=hp.Int('units_2_' + str(i), 126, 256, step=16), activation='relu', return_sequences=True)))
>         model.add(layers.Bidirectional(layers.LSTM(units=hp.Int('units_3_' + str(i), 256, 512, step=16), activation='relu',return_sequences=True)))
>     model.add(layers.Dropout(hp.Float("dropout", 0.4, 0.5, step=0.1)))
>     model.add(layers.Dense(num_classes,activation='softmax'))
> 
>     model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate',values=[1e-2, 1e-3, 1e-4])),
>                     loss='binary_crossentropy',
>                     metrics=['accuracy'])
> ```
> 
> I changed 'units_' to 'units_1_'.


hello, I also build a multi LSTM network. But it shows ''ValueError: Objective value missing in metrics reported to the Oracle, expected: ['accuracy'], found: dict_keys(['loss', 'val_loss'])''. 
Do you know what's wrong? Thx very much! I'm stuck for a long time 😭


def model_builder(hp):
    model = Sequential()
    hp_units1 = hp.Int('units', min_value=30, max_value=50, step=5, default=40)
    model.add(LSTM(units = hp_units1, return_sequences = True, input_shape = (X.shape[1], 1)))
    model.add(Dropout(0.2))
    hp_units2 = hp.Int('units', min_value=20, max_value=50, step=5, default=30)
    model.add(LSTM(units = hp_units2,return_sequences = False))
    model.add(Dropout(0.2))
    model.add(Dense(units = 1))
    hp_learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4, 1e-5, 1e-6])
    model.compile(optimizer = Adam(learning_rate=hp_learning_rate),
                  loss = 'mean_squared_error')
    return model

tuner = kt.Hyperband(model_builder,
                     objective='accuracy',
                     max_epochs=10,
                     factor=3,
                     overwrite=True)
