### ISSUE TITLE
Keras-tuner is restricted to Single Input Models is not mentioned in Documentation

### ISSUE THREAD

**Issue by Sanjaykrishnamurthy** [keras-team/keras-tuner#508]
It would great if the limitations are stated explicitly beforehand on the documentation page as I learned after much difficulty that Keras-tuner can work with single Inputs. Tensorflow throws errors that are not intuitive so finding out the real reason becomes much harder.

**Comment by hadrienj** [comment]
Hi @Sanjaykrishnamurthy,

I have an issue with a model using two inputs and I get a `InvalidArgumentError`. Is it because keras-tuner can't deal with more than one input? Any idea for a solution?

Thanks!

**Comment by Sanjaykrishnamurthy** [comment]
@hadrienj  Even I am facing the same issue and I suspect the error is because Keras-tuner can handle only one input at the moment. If you get to know the answer let me know.

**Comment by haifeng-jin** [comment]
I didn't know this. Anyone can paste any code for reproducing the issue? It is a bug I think.

**Comment by mandar2812** [comment]
@Sanjaykrishnamurthy @hadrienj It works just fine if you create your input handles with names and provide your data batches as a dictionary.

```python
import tensorflow as tf

def model_fn(hp):
    input_1 = tf.keras.layers.Input(name="input_1", shape=(2,))
    input_2 = tf.keras.layers.Input(name="input_2", shape=(3,))

    size_l = hp.Choice("size", [2, 3])
    output_1 = tf.keras.layers.Dense(size)(input_1)
    output_2 = tf.keras.layers.Dense(size)(input_2)

    ft_concat = tf.keras.layers.Concatenate()([output_1, output_2])
    output_final = tf.keras.layers.Dense(2, name="output_final")

    model = tf.keras.Model(inputs=[input_1, input_2], outputs=output)
    # model compile steps here.
    return model


train_batch = {
    "input_1": tf.convert_to_tensor([[1., 2.]]),
    "input_2": tf.convert_to_tensor([[1., 2., 3.]]) 
    "output_final": tf.convert_to_tensor([[2.0, 3.0]])
}
```
