### ISSUE TITLE
How to carry the best model forward and question about future implementation

### ISSUE THREAD

**Issue by amjass12** [keras-team/keras-tuner#51]
Hi all, 

thanks for this tool it is incredibly useful! A few follow up questions for clarification as they are not immediately clear. 

After hyper-optimisation, is there a way to carry the best model forward as the working model to then save the model etc and do further downstream analysis (plots, evaluation deployment etc)..

and is there planned integration with tensor board for easy visualisation of hyper-optimisation?

thanks!

**Comment by floscha** [comment]
Hi @amjass12 

You can simply get the best model like so:
```python
best_model = tuner.get_best_models(num_models=1)[0]
```

Also, when running the hyperparameter optimization, you can use the [TensorBoard callback](https://keras.io/callbacks/#tensorboard) like with Keras:
```python
tuner.search(x, y,
             epochs=5,
             validation_data=(val_x, val_y),
             callbacks=[keras.callbacks.TensorBoard()]
)
```

I hope this helps.

**Comment by amjass12** [comment]
YES!! thank you, this is exactly what i was looking for :)

Just a sanity check, please may i confirm a couple of things: I have looped through layers in order to find the best model with optimal layers as folows:

```
def build_model(hp):
    model = keras.Sequential()
    for i in range(hp.Range('num_layers', 2, 20)):
        model.add(layers.Dense(input_dim=5078,units=hp.Range('units_' + str(i),
                                              min_value=32,
                                              max_value=512,
                                              step=32), **etc etc etc**

```
For **'num_layers', 2, 20** it will iterate through all models that contain 2,3,4,5,6,7,8....20 layers and then find the optimised number of layers? 

For units: **min_value=32, max_value=512** For EACH layer, it will iterate through 32,33,34,35,36....512 units PER layer and find the optimum number of units per layer to reach the best performance it can?

And finally (i should just try this instead of ask [laziness :(]: is it possible to run keras tuner with a fixed layer in the model?

So i would like to tune two dense layer but have a final fixed dense layer (before sigmoid)of for example 100 units. Can I simply call model.add(dense etc) within the function so that the only tuning is taking place in the layer prior to this final fixed layer?

many thanks again!

**Comment by floscha** [comment]
First of all, Keras Tuner will only try ALL possible combinations of values if you use the `GridSearch` strategy which can be really computationally expensive as it often requires you to train 100s or 1000s of neural networks. `RandomSearch` on the other hand, will only try a number of random values from the ranges you've provided.

Of course, you can also use fixed layers like with regular Keras.

Another note: Your `input_dim=5078` only applies to the first dense layer and not the following ones.

**Comment by amjass12** [comment]
Thank you so much for clarifying! yes that makes perfect sense! RandomSearch should be sufficient!

thank you for confirming the fixed layer!

And for a model whereby the input layer is defined at the beginning and then all tensors are automatically re-shaped downstream (as in manually building a model), this is where the input dimension would be specified. I am guessing you are confirming it should not be in the following layer which it is not!

```
model= Sequential()
model.add(Dense(units=64, input_dim=5078, activation="relu"))
model.add(Dense(units=32, activation="relu"))
model.add(Dense(units=100, activation="relu"))
model.add(Dense(units=24, activation="sigmoid"))
```
and for keras tuner:

```
for i in range(hp.Range('num_layers', 2, 20)):
        model.add(layers.Dense(input_dim=5078,units=hp.Range('units_' + str(i),
                                              min_value=32,
                                              max_value=512,
                                              step=32),
                               activation='relu'))
    model.add(layers.Dense(24, activation='sigmoid'))
```
As the models are not 'layered' in construction (because of the for loop), is keras tuner only applying this input_dim to the first layer? this is important ha! it makes sense that it should be doing this?

**Comment by floscha** [comment]
I guess the easiest way would be to move the dense layer with the `input_dim` argument before the loop and change the range to `hp.Range('num_layers', 1, 19)`. Alternatively, you could also drop `input_dim` and let Keras infer the input shape automatically.

**Comment by amjass12** [comment]
Thank you! Yes that makes sense! only one way works (unless i am missing something): 

```
def build_model(hp):
    model = keras.Sequential()
    model.add(layers.Dense(units=64, input_dim=5078))
    for i in range(hp.Range('num_layers', 1, 19)):
        model.add(layers.Dense(units=hp.Range('units_' + str(i),
                                              min_value=32,
                                              max_value=512,
                                              step=32),
                               activation='relu'))
    model.add(layers.Dense(24, activation='sigmoid'))
```
This forces me to add a unit number to the input layer (same if i attempt to add model.add(Input)

If i completely omit the input layer as follows:

def build_model(hp):
    model = keras.Sequential()
    for i in range(hp.Range('num_layers', 2, 20)):
        model.add(layers.Dense(units=hp.Range('units_' + str(i),
                                              min_value=32,
                                              max_value=512,
                                              step=32),
                               activation='relu'))
    model.add(layers.Dense(24, activation='sigmoid'))
```

I get an error, 

**ValueError: Weights for model sequential have not yet been created. Weights are created when the Model is first called on inputs or `build()` is called with an `input_shape`.**

arghh, im sorry i feel like something is not clicking here!

**Comment by floscha** [comment]
As the error suggests, you have to build the model before returning it. So in your case, you'd have to call `model.build(input_shape=(None, 5078))` where 5078 is the size of your input data and `None` is a placeholder for the batch size which you do not want to set here as Keras Tuner will set it automatically later.

**Comment by amjass12** [comment]
Thank you!!  so my finaly structure looks as follows:

```
def build_model(hp):
    model = keras.Sequential()
    for i in range(hp.Range('num_layers', 1, 19)):
        model.add(layers.Dense(units=hp.Range('units_' + str(i),
                                              min_value=32,
                                              max_value=512,
                                              step=32),
                               activation='relu'))
    model.add(layers.Dense(24, activation='sigmoid'))
    model.compile(
        optimizer=keras.optimizers.Adam(
            hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])),
        loss='binary_crossentropy',
        metrics=['accuracy'])
    **model.build(input_shape=(None, 5078))**
 return model
```

Everything else downstream works fine although I am getting ambiguous model summary and validation_accuracy where i wasn't before!

```
tuner = RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=20,
    executions_per_trial=5,
    directory='/Users/jassim01/Desktop/CRUK Cambridge/R/Amir/',
    project_name='Optimal model')

tuner.search_space_summary()

tuner.search(X_train.values, y_train,
             epochs=50,
             validation_data=(X_test.values, y_test),shuffle=True)
```
tuner.results_summary()= best val acc 0.6912 (this was different to when i ran it the first time with the input_dim in the first dense layer (model.add(layers.Dense(input_dim=5078,units=hp.Range( etc...

and certainly the training (and test val) is in the 90's% when i compile the model manually (as above)..

Also when I call model.summary, again a different result to when the input dim was in the first dense layer: I am now getting a multiple output shape where i was not before:

ayer (type)                 Output Shape              Param #   
=================================================================
dense_11 (Dense)             multiple                  487584    
_________________________________________________________________
dense_12 (Dense)             multiple                  3104      
_________________________________________________________________
dense_13 (Dense)             multiple                  1056      etc... 

Also, best val_acc is reported as 0.69, if i look at the history of the iterations, there are models that perform significantly better: i.e, 

loss=0.0178, accuracy=0.998, val_loss=0.262, val_accuracy=0.921]

So i am unsure about why it is outputting the the best model as 0.69. 

Also, just to clarify, was the method of:

def build_model(hp):
    model = keras.Sequential()
    for i in range(hp.Range('num_layers', 2, 20)):
        model.add(layers.Dense(input_dim=5078,units=hp.Range('units_' + str(i),
                                              min_value=32,
                                              max_value=512,
                                              step=32), **etc etc etc**

wrong? as this seemed to work fine...is this not applying the input_dim only to the first layer?

thanks! sorry for dragging on!

**Comment by omalleyt12** [comment]
Thanks for the issue! The val_acc issue should be fixed, please file a new bug if you find another issue

**Comment by hollowgalaxy** [comment]
if `build_model` func is suppose to have `model.compile(...)`, is it safe to use compile the model returned by `tuner.get_best_models()[0]`?
with something like this...
```
model = tuner.get_best_models()[0]
hp = tuner.get_best_hyperparameters()[0]
model.compile(loss='categorical_crossenthropy', optimizer=SGD(learning_rate=hp['learning_rate'], nesterov=True, metrics=['categorical_accuracy'])
model.fit(...)
```

Asking this because `get_best_model` part doesn't persist the metrics used in `build_model` function.
