### ISSUE TITLE
Get Hyperparameter Random Search as integer

### ISSUE THREAD

**Issue by axelpfennig3000** [keras-team/keras-tuner#512]
Hello.

I have a random Search Problem. I need the hyperparameter.
```py
  z_mean = Dense(units=hp.Int('unitsBottle',min_value=8,max_value=48,step=8))(h)
  latentVariable = hp.get('unitsBottle')
  z_log_var = Dense(units=latentVariable)(h)
```
latentVariable is a tensor. I can print it:
` tf.Tensor(16, shape=(), dtype=int32)`

But I need the number 16. Not as a tensor. As a integer number (scalar) so I can put it into

` z = Lambda(sampling, output_shape=(latenteVariable,))([z_mean, z_log_var, latenteVariable])`

How can I only get the number?

Thank you

**Comment by haifeng-jin** [comment]
```py
  units = hp.Int('unitsBottle',min_value=8,max_value=48,step=8)
  z_mean = Dense(units=units)(h)
  z_log_var = Dense(units=units)(h)
```
This should work.

**Comment by axelpfennig3000** [comment]
Thank you. I hoped this was the problem. The problem must be somewhere else. I have to open a new questions.
