### ISSUE TITLE
Keras Tuner Optimization Search Space intended does not agree with the Results Summary

### ISSUE THREAD

**Issue by rafaelstevenson** [keras-team/keras-tuner#522]
Hello, I am currently using keras tuner, and it seems there is a problem where i used a for loop to define the number of hidden layers as a search space, but the model results summary does not agree with the given 'num_layers' as when 'num_layers'==3 for example, why there are still hyper parameters for 6 hidden layers as i show in the screenshot.

![image](https://user-images.githubusercontent.com/67007111/115361361-b4a40780-a1ea-11eb-9bde-cc339f1454f1.png)
![image](https://user-images.githubusercontent.com/67007111/115361389-bc63ac00-a1ea-11eb-88ea-8bad302b59d9.png)

**Comment by haifeng-jin** [comment]
Answered in the Discussion : )
