### ISSUE TITLE
Support multi-objective optimization

### ISSUE THREAD

**Issue by brethvoice** [keras-team/keras-tuner#556]
Line 160 [here](https://github.com/keras-team/keras-tuner/blob/64c547621230f43b9d68e5ef95537d9efbc0b293/keras_tuner/engine/oracle.py#L150) suggests that :

"# Assumes single objective, subclasses can override."

Please provide a working example so we can see how to do this.

**Comment by haifeng-jin** [comment]
Thanks for the issue. We need to support this feature first before providing an example.
