### ISSUE TITLE
Syntax error comming on 4th layer when using keras tuner 

### ISSUE THREAD

**Issue by doyeljoseph** [keras-team/keras-tuner#566]
Hi ,
When I am trying to use te keras tuner for hyperparameter tuning for LSTM regression problem, I am getting a syntax error on the 4th layer. It is very akward that when i put the same layer on 3rd layer the syntax error is not shown and that implies that the syntax error is not on that particular line. Kindly some one help me out with the issue. Here is the code on the following lines.

def build_model(hp):
model = keras.Sequential()
model.add(LSTM(hp.Int("input_units",min_value = 16, max_value= 256, step = 16),
activation='relu',input_shape = (trainX.shape[1],trainX.shape[2]),return_sequences = True))

for i in range (hp.Int("num_layers", 1,4)):
    model.add(LSTM(hp.Int(f"LSTM_{i}_units",min_value = 16, max_value= 256, step = 16),activation='relu',return_sequences = 
    False))
    model.add(Dropout(hp.Int(f"Dropout_{i}_units",min_value = 0.1, max_value= 0.9, step = 0.1))
    model.add( Dense(hp.Int(f"Dense_{i}_units",min_value = 1, max_value= 60, step = 2))
              
model.compile(optimizer=keras.optimizers.Adam(
        hp.Choice("learning_rate", values=[1e-2, 1e-3, 1e-4])),
        loss="categorical_crossentropy", metrics=["accuracy"])
model.summary()
return model
The error come on the 4th layer here in that case it comes on the Dense layer. Is it some common issue with keras tuner or is it some error in the syntax i have written.Kindly help me out

**Comment by my-hub30** [comment]
Hello, do you already work it out? 
I also build a multi-LSTM layer network just like you. But when I tuner the hyperparameters,  it says '' Too many failed attempts to build model.')
RuntimeError: Too many failed attempts to build model. ''
Do you have the same problem?
Thx!

**Comment by doyeljoseph** [comment]
Hello,  I also got that error but now i am getting different error 

ValueError: in user code:

    /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
        outputs = model.train_step(data)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:755 train_step
        loss = self.compiled_loss(
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:203 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:152 __call__
        losses = call_fn(y_true, y_pred)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:256 call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:1537 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:4833 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py:1134 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 1) and (None, 14, 8) are incompatible

**Comment by my-hub30** [comment]
> Hello, I also got that error but now i am getting different error
> 
> ValueError: in user code:
> 
> ```
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
>     return step_function(self, iterator)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
>     outputs = model.distribute_strategy.run(run_step, args=(data,))
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
>     return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
>     return self._call_for_each_replica(fn, args, kwargs)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
>     return fn(*args, **kwargs)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
>     outputs = model.train_step(data)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:755 train_step
>     loss = self.compiled_loss(
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/engine/compile_utils.py:203 __call__
>     loss_value = loss_obj(y_t, y_p, sample_weight=sw)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:152 __call__
>     losses = call_fn(y_true, y_pred)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:256 call  **
>     return ag_fn(y_true, y_pred, **self._fn_kwargs)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
>     return target(*args, **kwargs)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/losses.py:1537 categorical_crossentropy
>     return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
>     return target(*args, **kwargs)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:4833 categorical_crossentropy
>     target.shape.assert_is_compatible_with(output.shape)
> /opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py:1134 assert_is_compatible_with
>     raise ValueError("Shapes %s and %s are incompatible" % (self, other))
> 
> ValueError: Shapes (None, 1) and (None, 14, 8) are incompatible
> ```

I saw someone's reply. I'm not sure, but you may try this:
LSTM->LSTM  requires return_sequences=True
