### ISSUE TITLE
Why kerastuner optimizes hyperparamters that I don't define, like tuner/bracket,epochs,initial_epoch,round?

### ISSUE THREAD

**Issue by my-hub30** [keras-team/keras-tuner#570]
Hello, do you have the problem that the tuner optimizes some other hyperparameters that you don't define?

I only define 2 hyperparameters including 'units' and 'learning_rate', but Trial summary shows the following: > 
[Trial summary]
 |-Trial ID: f4637b834ecf7d94c487473599ade6fa
 |-Score: 0.013386380674989045
 |-Best step: 0
 > Hyperparameters:
 |-learning_rate: 0.0001
 |-tuner/bracket: 2
 |-tuner/epochs: 2
 |-tuner/initial_epoch: 0
 |-tuner/round: 0
 |-units: 40

I don't even define tuner/bracket,  tuner/epochs,  tuner/initial_epoch,  tuner/round.
Do any friends know why?
Thx!

**Comment by vb690** [comment]
Hello @my-hub30 :)

Those are not hyperparameters of your model but logs of of the specific tuning algorithm you are using (which I assume being Hyperband) telling you at which stage the tuner reached `Score`.

For more details
https://keras.io/api/keras_tuner/tuners/hyperband/
https://homes.cs.washington.edu/~jamieson/hyperband.html
