### ISSUE TITLE
Breaking changes in release

### ISSUE THREAD

**Issue by whitead** [keras-team/keras-tuner#572]
It appears the latest release (v1.0.3) made a breaking change of renaming the main package. This has broken some of our code. Even the README.md file for this repo has the import code which will no longer work. Is it possible to create backwards compatability for the old import? In the future, I believe breaking changes like this should warrant an increment to the major version (i.e., v1.0.2 -> v2.0.0). Many package managers rely on requirements like `keras-tuner~=1.0.0` to prevent breaking changes affecting their package. Thanks!

**Comment by haifeng-jin** [comment]
Hi @whitead ,
So sorry for breaking your code.
We tried to maintain backward compatibility.
As I tested, the code in the readme works fine.
I can help you take a look into the error if you still have them.

Thanks.

The code I ran is here:

```py
import kerastuner as kt
from tensorflow import keras

def build_model(hp):
  model = keras.Sequential()
  model.add(keras.layers.Dense(
      hp.Choice('units', [8, 16, 32]),
      activation='relu'))
  model.add(keras.layers.Dense(1, activation='relu'))
  model.compile(loss='mse')
  return model

tuner = kt.RandomSearch(
    build_model,
    objective='val_loss',
    max_trials=5)
import numpy as np

x_train = np.random.rand(100, 10)
y_train = np.random.rand(100, 1)
x_val = x_train
y_val = y_train
tuner.search(x_train, y_train, epochs=5, validation_data=(x_val, y_val))
best_model = tuner.get_best_models()[0]
```

**Comment by whitead** [comment]
Hi @haifeng-jin, yes the README works now. It did not on release. It's fine, I'll survive. Just a reminder that the smallest version change (1.0.3->1.0.4) should imply minor changes, no renaming the entire package.
