### ISSUE TITLE
Training dataset as hyperparameter for tuner

### ISSUE THREAD

**Issue by jmvericat** [keras-team/keras-tuner#590]
Hello,

I am working on a time series forecasting problem.
In this kind of problem one of the first operations is the conversion of the raw time series to a standard machine learning dataset by using some number of past observations as input or X.
The number of previous observations that constitutes a sample of the X dataset is a crucial parameter that must be determined trough some procedure, grid-searching, random-searching...
I have a custom function "series_to_supervised" that transforms a plain time series in a machine learning dataset suitable for the model that will use it, MLP, CNN or LSTM. It has the parameter "time_steps" that controls how many observations from the time series will form the a sample of the dataset and "model" that controls the shape of the dataset for the selected model.

As I see in the documentation the normal procedure with keras-tuner is:
    
    def build_model(hp):
        ...
        return model

    tuner = keras-tuner(
        build_model,
        ...
    )

    # datasets construction
    X, y, model = series_to_supervised(series, time_steps, model='MLP') 
    # X.shape (time_steps, samples), y.shape (1, samples)
    
    val = X.shape[1]//10
    x_train, y_train = X[:,:-val], y[:-val]
    x_val, y_val = X[:,-val:], y[-val:]

    tuner.search(x_train, y_train, epochs=epochs, validation_data=(x_val, y_val))

As you can see the "time_step" parameter constitutes a hyperparameter that jointly with the "model" and model topology are fundamental to get good performance.
I do not know how to "insert" the dataset construction and its parameters "time_steps" and "model" inside the tuner optimization engine:

    def build_model(hp, series):

        X, y, model = series_to_supervised(series, hp.Int("time_steps", min_value=12, max_value=36, step=2), model=hp.Choice('MLP','CNN','LSTM'))

        val = X.shape[1]//10
        x_train, y_train = X[:,:-val], y[:-val]
        x_val, y_val = X[:,-val:], y[-val:]

        if model == 'MLP':
            ...
        if model == 'CNN':
            ...
        if model == 'LSTM':
            ...

        return model

OR

    tuner.search(series, ?, epochs=epochs, validation_data=???)   

        X, y, model = series_to_supervised(series, hp.Int("time_steps", min_value=12, max_value=36, step=2), model=hp.Choice('MLP','CNN','LSTM'))

        val = X.shape[1]//10
        x_train, y_train = X[:,:-val], y[:-val]
        x_val, y_val = X[:,-val:], y[-val:]
        ...???

The use of some parameters during the dataset building can also apply to other kind of problems not related with time series, i.e. to build different datasets by effectuating a choice of some of its features or to apply different type of preprocessing as data scaling or standardizing etc.
Thank you for your time and advice
Regards

**Comment by haifeng-jin** [comment]
We are working on better supporting this feature. However, for now, you will need to override the `Tuner.run_trial` to do it.
