### ISSUE TITLE
"sample_weight" does not exist in all sklearn models' fit function 

### ISSUE THREAD

**Issue by dimoibiehg** [keras-team/keras-tuner#609]
Although `sample_weight` is an optional parameter in "sklearn" models (in the following line), it does not exist in the prototype of all `.fit` functions. 
https://github.com/keras-team/keras-tuner/blob/3a0d2c9f83eaa78b05ceb7c6c72c38f7c9f4a71b/keras_tuner/tuners/sklearn_tuner.py#L138

Hence, I got the following error code for "PassiveAggressiveRegression" model in sklearn as its 'fit' function has not `sample_weight` attribute (see this link: https://github.com/scikit-learn/scikit-learn/blob/2beed55847ee70d363bdbfe14ee4401438fba057/sklearn/linear_model/_passive_aggressive.py#L443):

> TypeError: fit() got an unexpected keyword argument 'sample_weight'

**Comment by haifeng-jin** [comment]
A fix would be check the fit function signature before passing sample_weight to it.
Contribution is welcome.
