### ISSUE TITLE
Cannot compile/fit multiple times, such as when we are doing transfer learning in tensorflow official tutorial

### ISSUE THREAD

**Issue by fzyzcjy** [keras-team/keras-tuner#629]
**Describe the bug**

I am doing transfer learning, e.g. you can think of it like this official tutorial https://www.tensorflow.org/tutorials/images/transfer_learning. However, that requires me to `compile`, `fit`, and then `compile` again and `fit` again. Therefore, I wonder how I can do this with keras tuner? It is very common, because transfer learning, as is mentioned in any textbook, is very common practice.

**To Reproduce**

see above

**Expected behavior**

see above

**Additional context**

see above

**Would you like to help us fix it?**
yes.

**Comment by TylerADavis** [comment]
I've been looking at the same scenario, and I can think of a few possible ways to address this, though I'm not sure if there's a preferred approach. I'd be interested to hear from one of the owners/maintainers to see if there's a recommended way.

1. Use Keras tuner in two phases, e.g. tune once to find the model that gives the best performance after phase one, then in phase two explore the best hyper parameters for that single best model. Your `model_builder(hp)` could load the best checkpoint from phase one.
2. Write a custom class that inherits from kt.RandomSearch, with an override of the run_trial method.

Here's an example of how my custom tuner looks:


```python
def model_builder(hp):
    """Builds an EfficientNet model with the given hyper parameters."""
    hp_learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])

    backbone = tf.keras.applications.efficientnet.EfficientNetB0(
        weights='imagenet', input_shape=IMAGE_SIZE, include_top=False)
    backbone.trainable = False

    ## Input 1

    old_inputs = layers.Input(shape=IMAGE_SIZE, name='input_oldest')
    # First input for 'data_a'
    inputs = scaler(old_inputs)
    inputs = augment_inputs(inputs)

    oldest_outputs = tf.keras.layers.GlobalAveragePooling2D()(backbone(inputs, training=False))
    x = tf.keras.layers.BatchNormalization()(oldest_outputs)

    outputs = layers.Dense(1, activation='sigmoid')(x)

    model = tf.keras.Model([old_inputs),
                           outputs,
                           name='model_head')

    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=hp_learning_rate),
                loss=tf.keras.losses.BinaryCrossentropy(),
                metrics=METRICS)
    return model, backbone

def unfreeze_and_recompile_model(model, backbone, hp):
    """Unfreezes the backbone of the model and recompiles the model, according to hyperparams."""
    hp_learning_rate = hp.Choice('p2_learning_rate', values=[1e-4, 1e-5, 1e-6])
    hp_tune_fraction = hp.Choice('tune_fraction', values=[-20, -40, -80, 0])
    backbone.trainable = True
    TRAIN_AT = hp_tune_fraction
    # We unfreeze the top 20 layers while leaving BatchNorm layers frozen
    for layer in backbone.layers[:TRAIN_AT]:
        layer.trainable = False
    for layer in backbone.layers[TRAIN_AT:]:
        # if not isinstance(layer, layers.BatchNormalization):
        layer.trainable = True

    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=hp_learning_rate),
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=METRICS)

    return model

class MyTuner(kt.RandomSearch):
    """Like random search, but we override run_trial to enable a fine-tuning phase."""
    def run_trial(self, trial, *args, **kwargs):
        hp = trial.hyperparameters
        model, backbone = model_builder(hp)

        kwargs_p1 = kwargs.copy()
        kwargs_p1['epochs'] = kwargs['epochs'] // 4

        phase_one_history =  model.fit(*args, **kwargs_p1)

        model = unfreeze_and_recompile_model(model, backbone, hp)

        return model.fit(*args, **kwargs)
```

You can then use this tuner exactly as you would use the normal RandomSearch tuner.

**Comment by TylerADavis** [comment]
@haifeng-jin Do you have a recommendation for who may be best to ask about this? I would be willing to contribute a tutorial demonstrating the use of Keras-tuner for two phase transfer learning, as described in the resources below.

https://www.tensorflow.org/tutorials/images/transfer_learning
https://keras.io/examples/vision/image_classification_efficientnet_fine_tuning/

**Comment by haifeng-jin** [comment]
@TylerADavis Thank you in advance! The tutorials are mainly managed in https://github.com/keras-team/keras-io. You can contribute an "example" there. Please request my review in your PR there.
