### ISSUE TITLE
BayesianOptimization now get "ValueError: Unknown metric: loss"

### ISSUE THREAD

**Issue by To3No7** [keras-team/keras-tuner#631]
**Describe the bug**
Running BayesianOptimization now crashes with "ValueError: Unknown metric: loss". For other code examples I get "ValueError: Unknown metric: val_accuracy"

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-2-ec3fcc4b8e7b> in <module>()
    184 mnist_train = tf.data.Dataset.from_tensor_slices((x_train, y_train))
    185 
--> 186 tuner.search(train_ds=mnist_train)
    187 
    188 best_hps = tuner.get_best_hyperparameters()[0]

5 frames

/usr/local/lib/python3.7/dist-packages/keras_tuner/engine/metrics_tracking.py in _assert_exists(self, name)
    284     def _assert_exists(self, name):
    285         if name not in self.metrics:
--> 286             raise ValueError("Unknown metric: %s" % (name,))
    287 
    288 

ValueError: Unknown metric: loss

**To Reproduce**
https://colab.research.google.com/drive/1v-RblPL4XiYY_AmGW47xLL6v5sbq2ggY?usp=sharing
But this is just your own code example: https://github.com/keras-team/keras-io/blob/master/guides/keras_tuner/custom_tuner.py  in colab.

**Expected behavior**
Continuing to do the search

**Additional context**

**Would you like to help us fix it?**
Yes! (I have a class with 60 students now crashing on my example code that worked a few months ago) So any quick workaround would be appreciated!

**Comment by To3No7** [comment]
Might be related to #627.

**Comment by MarceloCapeletti** [comment]
I having a similar issue on Colab when Rrunning BayesianOptimization

To Reproduce:
https://github.com/MarceloCapeletti/creditcard_fraud_detection/blob/main/projeto_credit_card_fraud_detection.ipynb

Error:
ValueError: Unknown metric: accuracy

**Comment by condor-cp** [comment]
+1
The same error appeared on my custom tuner built based on the end to end example in [https://keras.io/guides/keras_tuner/custom_tuner/](https://keras.io/guides/keras_tuner/custom_tuner/).

**Comment by condor-cp** [comment]
It seems that on_epoch_end has no more a built in behavior (it only passes) :
https://github.com/keras-team/keras-tuner/blob/003559cc82bc82b01480c85e51568cd4d3e5ca86/keras_tuner/engine/tuner.py#L367

Using the second method to write run_trial described in [https://keras.io/guides/keras_tuner/custom_tuner/](https://keras.io/guides/keras_tuner/custom_tuner/), ie call :
```
        self.oracle.update_trial(trial.trial_id, {'score': score})
        self.save_model(trial.trial_id, model)
```
At the end of the method worked. Warning, you also have to override the methods save_model and load_model as it is done for example here:
https://github.com/keras-team/keras-tuner/blob/003559cc82bc82b01480c85e51568cd4d3e5ca86/keras_tuner/tuners/sklearn_tuner.py#L198

**Comment by haifeng-jin** [comment]
This tutorial is not up-to-date. I will update it.
Also we need to check the case of the return value is not a float bug a np.float32. Also check if the return value is none of the supported types, throws an error.

The way to do custom training loop is like this: https://github.com/keras-team/governance/blob/master/rfcs/20210920-tune-end-to-end-ml-workflows-in-keras-tuner.md#custom-training-loop

**Comment by haifeng-jin** [comment]
tutorial updated by:
https://github.com/keras-team/keras-io/pull/780
https://github.com/keras-team/keras-io/pull/773
