### ISSUE TITLE
Unknown metric error when subclassing tuner

### ISSUE THREAD

**Issue by BIA4-course** [keras-team/keras-tuner#635]
I am trying to subclass a tuner, e.g. Hyperband, to tune batch_size using the following

```
class MyTuner(kt.tuners.Hyperband):
  def run_trial(self, trial, *args, **kwargs):
    kwargs['batch_size'] = trial.hyperparameters.Int('batch_size', 1024, 4096, step=512)
    super(MyTuner, self).run_trial(trial, *args, **kwargs)
```

With this, `tuner.search` gives the following error at the end of the first trial:

```

Epoch 1/2
59/59 [==============================] - 2s 32ms/step - loss: 5.1755 - accuracy: 0.7180 - val_loss: 0.5713 - val_accuracy: 0.9060
Epoch 2/2
59/59 [==============================] - 2s 29ms/step - loss: 0.4279 - accuracy: 0.9235 - val_loss: 0.2897 - val_accuracy: 0.9425
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: DeprecationWarning: `Tuner.run_trial()` returned None. It should return one of float, dict, keras.callbacks.History, or a list of one of these types. The use case of calling `Tuner.oracle.update_trial()` in `Tuner.run_trial()` is deprecated, and will be removed in the future.
  if sys.path[0] == '':
---------------------------------------------------------------------------

/usr/local/lib/python3.7/dist-packages/keras_tuner/engine/metrics_tracking.py in _assert_exists(self, name)
    284     def _assert_exists(self, name):
    285         if name not in self.metrics:
--> 286             raise ValueError("Unknown metric: %s" % (name,))
    287 
    288 

ValueError: Unknown metric: val_accuracy
```

The same exact code works if I use Hyperband without subclassing. This happens independently of the model type (tried with a CNN and an LSTM) or the metric used (e.g. tried with `accuracy`, `loss`, `val_loss`).

**To Reproduce**

https://colab.research.google.com/drive/1-H9PFZwObxpV5Jw04JhlqLHfuz3ncgyJ?usp=sharing

**Expected behaviour**

Tuning should continue and batch size should be tuned.

**Comment by opsxcq** [comment]
I've the same issue, tracing it got me here

https://github.com/keras-team/keras-tuner/blob/003559cc82bc82b01480c85e51568cd4d3e5ca86/keras_tuner/engine/oracle.py#L161

```python
        trial.score = trial.metrics.get_best_value(self.objective.name)
```

Maybe something is missing on the subclass ? On the parent class the only place calling `register` for a metric that I could find is here

https://github.com/keras-team/keras-tuner/blob/003559cc82bc82b01480c85e51568cd4d3e5ca86/keras_tuner/engine/oracle.py#L229

**Comment by opsxcq** [comment]
Found the problem, please change your code to

```python
class MyTuner(kt.tuners.Hyperband):
  def run_trial(self, trial, *args, **kwargs):
    kwargs['batch_size'] = trial.hyperparameters.Int('batch_size', 1024, 4096, step=512)
    return super(MyTuner, self).run_trial(trial, *args, **kwargs)

```

**Comment by darrahts** [comment]
@opsxcq , this did not work, the error still persists. Can you share a minimum working example and your keras versions if you were able to get it to work?

**Comment by opsxcq** [comment]
My code is just like the code above, just naming conventions used are different. the dependencies that I've on my project:

From `pyproject.toml`

```
[tool.poetry.dependencies]
python = "^3.7.1"
setuptools = "^51.3.3"
tensorflow = "^2.5.0"
scapy = "^2.4.4"
matplotlib = "^3.3.3"
jupyter = "^1.0.0"
loguru = "^0.5.3"
pyyaml = "^5.4.1"
toml = "^0.10.2"
keras-tuner = "^1.0.4"
```

**Comment by BIA4-course** [comment]
Just to mention that adding the return statement worked for me.

**Comment by darrahts** [comment]
@BIA4-course , thanks for pointing this out, what an oversight! Where is my rubber duck when I need him.... One word, `return`, was overlooked. Thank you both.
