### ISSUE TITLE
Missing documantation on creating custom tuner

### ISSUE THREAD

**Issue by Dianagle2** [keras-team/keras-tuner#638]
Hii 
I've looked at the documantation on ["Writing your own Tuner to support a custom training loop"](https://keras.io/guides/keras_tuner/custom_tuner/). 
I see that "save_model" is not implemented in base_tuner class. However, in the documantation nothing is written about it not being implemented. 

Maybe we should add a note about it? 
Maybe we can provide a simple implementation at base_tuner instead

Diana :)

**Comment by haifeng-jin** [comment]
We have updated the doc you mentioned. It was out-of-date.
It doesn't need to use the `save_model` any more.
