### ISSUE TITLE
Unable to use MultiObjective Functionality

### ISSUE THREAD

**Issue by ShaheenPerveen** [keras-team/keras-tuner#648]
Hi
I would like train a multitask model. On referring to #641 , the changes pushed from obj branch to master will be able to solve my use-case. However, the latest release version 1.1.0 does not contain these changes. Please guide me on how to use the changes? Is there a plan to include the above changes in next release. If yes, when is the likely date. @haifeng-jin  Could you provide instructions on how could I use this from the repo itself.

**Comment by haifeng-jin** [comment]
You can only download and install the master branch to use that case for now. You may clone the repo and cd to it and use `pip install .` to install. You may search online for more detailed instructions. Our repo is a pretty standard one.
