### ISSUE TITLE
Early Stopping Hyperband Tuner

### ISSUE THREAD

**Issue by skumarlabs** [keras-team/keras-tuner#659]
I am using Hyperband tuner. The problem I am facing is that due to my large dataset, the minimum possible Hyperband_iterations=1, total 90 trials over search space take a long time.

I am interested to know how can I stop tuner after a certain N number of trials so that whatever best parameters I have got so far I can train my final model using them.
Thanks!

**Comment by IgnacioBarroso** [comment]
https://www.youtube.com/watch?v=wkwtIeq9Ljo see this
