### ISSUE TITLE
Cross Validation

### ISSUE THREAD

**Issue by vullnetu** [keras-team/keras-tuner#663]
I would really like to use the hyperband tuner with cross validation . I have seen some similar issues open but no progress in this topic for 2 years. 

What do I need to change on run_trial to achieve this correctly ? If there is a fast answer please let me know.

**Comment by nicrie** [comment]
@vullnetu did you find a way of doing what you what? If so, how?

**Comment by vullnetu** [comment]
> @vullnetu did you find a way of doing what you what? If so, how?

I found another implementation on dask-ml. It works for my case.

**Comment by vullnetu** [comment]
Yes used the same in the past. Bayesian optimization tuner is easy to modify as it does not rely on past model weights. Hyperband is more cumbersome to change because of this issue. But, I had better convergence with hyperband on my data set this is why I wanted this.

**Comment by nicrie** [comment]
hey @vullnetu in case you got the script from the post mentioned above running, I would be very much interested in your solution. Perhaps it worked in the past, but currently (`keras-tuner==1.1.0`), the code throws an error, apparently because `save_model` is not implemented. 

```py
Traceback (most recent call last):
  File "build-model.py", line 381, in <module>
    tuner.search(X_train, y_train, batch_size=batch_size, epochs=1, cv=3)
  File "/home/nrieger/anaconda3/envs/tf26/lib/python3.8/site-packages/keras_tuner/engine/base_tuner.py", line 179, in search
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
  File "build-model.py", line 111, in run_trial
    self.save_model(trial.trial_id, model)
  File "/home/nrieger/anaconda3/envs/tf26/lib/python3.8/site-packages/keras_tuner/engine/base_tuner.py", line 215, in save_model
    raise NotImplementedError
NotImplementedError
```

Initially, I just removed `save_model` and it seemed to work, but after some hours of head scratching why my hypertuned model looked always so random, i realized that the "best model" found by `keras-tuner` is not saved properly and (without any warning) just returns a random model.

Any idea how to repair this?

**Comment by vullnetu** [comment]
Yes a lot has changed since the first implementation.

1. I think you are subclassing the wrong tuner try this one [https://github.com/keras-team/keras-tuner/blob/a9a384ab4158edb306acbc21e2c7599f79ab8424/keras_tuner/engine/tuner.py#L202](url). You can find this by just following the superclass of the bayesian optimiser. Moreover, try to understand how they implement the run_trial method. As I am not using it anymore I can not tell you in detail how to proceed. But, probably you have to override build_and_fit() to return the cv results.

2. Best model will not work as you are always training on k-1 folds and therefore saving a model trained on less training data than you have. Instead try to extract the best hp and retrain your model on your own. This leads also to the conclusion that the callback for model checkpoint in run_trial is useless, eliminate it (saves memory and time).

**Comment by vullnetu** [comment]
Yes a lot has changed since the first implementation.

1. I think you are subclassing the wrong tuner try this one [https://github.com/keras-team/keras-tuner/blob/a9a384ab4158edb306acbc21e2c7599f79ab8424/keras_tuner/engine/tuner.py#L202](url). You can find this by just following the superclass of the bayesian optimiser. Moreover, try to understand how they implement the run_trial method. As I am not using it anymore I can not tell you in detail how to proceed. But, probably you have to override build_and_fit() to return the cv results.

2. Best model will not work as you are always training on k-1 folds and therefore saving a model trained on less training data than you have. Instead try to extract the best hp and retrain your model on your own. This leads also to the conclusion that the callback for model checkpoint in run_trial is useless, eliminate it (saves memory and time).

**Comment by vullnetu** [comment]
Github deleted my previous comment for some reason...Yes a lot has changed since the first implementation.

Try to subclass from this class [link](https://github.com/keras-team/keras-tuner/blob/a9a384ab4158edb306acbc21e2c7599f79ab8424/keras_tuner/engine/tuner.py#L202).
Then, try to understand how they implemented run_trial(). I do not use this anymore so I can not tell you in detail how to proceed, but you should try to override build_and_fit() to include cv.
Best_model can not work for cv because you are always training on k-1 folds. Instead get the best hp and retrain your model on your own (easiest way). Also because of this reason you can delete the callback for model checkpoint (useless)

**Comment by Furkan-rgb** [comment]
In case anyone stumbles on this in the future, I had the same need and did my own implementation. Feedback is welcome. @vullnetu I did keep the checkpoint. Is that bad? This implementation is based on the default Tuner class, but I'm not sure if there's anything I missed.

```python
class TimeSeriesBayesianOptimization(BayesianOptimization):
    def __init__(self, time_series_splits=5, *args, **kwargs):
        super(TimeSeriesBayesianOptimization, self).__init__(*args, **kwargs)
        self.time_series_splits = time_series_splits
        self.tscv = TimeSeriesSplit(n_splits=self.time_series_splits)

    def run_trial(self, trial, *args, **kwargs):
        # Extract X_train and y_train without altering original args
        X_train, y_train, *remaining_args = args

        # Callback to save the best epoch
        model_checkpoint = tuner_utils.SaveBestEpoch(
            objective=self.oracle.objective,
            filepath=self._get_checkpoint_fname(trial.trial_id),
        )
        original_callbacks = kwargs.pop("callbacks", [])

        # Track the histories
        histories = []

        for execution in range(self.executions_per_trial):
            total_val_loss = 0.0
            total_loss = 0.0
            total_binary_accuracy = 0.0
            total_val_binary_accuracy = 0.0

            for train_index, val_index in self.tscv.split(X_train):
                X_train_split, X_val_split = X_train[train_index], X_train[val_index]
                y_train_split, y_val_split = y_train[train_index], y_train[val_index]

                # Build the model for this trial's hyperparameters
                model = self.hypermodel.build(trial.hyperparameters)

                # Set up callbacks
                copied_callbacks = self._deepcopy_callbacks(original_callbacks)
                self._configure_tensorboard_dir(copied_callbacks, trial, execution)
                copied_callbacks.append(tuner_utils.TunerCallback(self, trial))
                copied_callbacks.append(model_checkpoint)

                # Train the model for this split
                history = model.fit(
                    X_train_split,
                    y_train_split,
                    validation_data=(X_val_split, y_val_split),
                    callbacks=copied_callbacks,
                    **kwargs
                )

                # Grab the best values for each metric
                best_val_loss = min(history.history["val_loss"])
                best_loss = min(history.history["loss"])
                best_binary_accuracy = max(history.history["binary_accuracy"])
                best_val_binary_accuracy = max(history.history["val_binary_accuracy"])

                # Accumulate the best values
                total_val_loss += best_val_loss
                total_loss += best_loss
                total_binary_accuracy += best_binary_accuracy
                total_val_binary_accuracy += best_val_binary_accuracy

            # Compute the averages
            avg_val_loss = total_val_loss / self.time_series_splits
            avg_loss = total_loss / self.time_series_splits
            avg_binary_accuracy = total_binary_accuracy / self.time_series_splits
            avg_val_binary_accuracy = (
                total_val_binary_accuracy / self.time_series_splits
            )

            # Store the averages in the histories list
            histories.append(
                {
                    "val_loss": avg_val_loss,
                    "loss": avg_loss,
                    "binary_accuracy": avg_binary_accuracy,
                    "val_binary_accuracy": avg_val_binary_accuracy,
                }
            )

        return histories

    def save_model(self, trial_id, model):
        """Save the model for the given trial."""
        fname = os.path.join(self.get_trial_dir(trial_id), "model.keras")
        model.save(fname)
```
