### ISSUE TITLE
getting an error while continuing the search

### ISSUE THREAD

**Issue by ekoptra** [keras-team/keras-tuner#668]
I use bayesian optimization. While still searching my notebook died and when I started again an error appeared as shown in the picture. Yesterday my notebook died in the middle of a search but when I resumed it didn't show an error like that. Why did this happen?

![image](https://user-images.githubusercontent.com/52368104/159149321-3670c7fc-ff46-4219-bf76-76d73593b2d6.png)

**Comment by brydon** [comment]
Did you perhaps update the library between runs? There was an update in the way trial ids were stored that was released with version 1.1.1.

I'd suggest either starting the tuning process over again on 1.1.1 _or_ reverting your local library to 1.1.0 and finishing the tuning process on _that_ version of the library before updating.
