### ISSUE TITLE
what's the defference with using get_best_hyperparameters() to generate model and get_best_models()?

### ISSUE THREAD

**Issue by vivianawoo** [keras-team/keras-tuner#689]
After searching hyperparameters, i tried two way to get best model。
one way is using tuner.get_best_hyperparameters() to generate the model（A bellow），another is using tuner.get_best_models() directly.（B bellow）
and then i use these two model to predict the same data, the prediction results are quite different. why?what‘s the difference with there two model?

A：
tuner.search(x_train, y_train）
best_hps=tuner.get_best_hyperparameters(1)[0]
best_model_params = build_model(best_hps)
best_model_params.fit(X, Y)
best_model_params.save("best_model_params_2")

B:
tuner.search(x_train, y_train）
models = tuner.get_best_models(num_models=1)  
best_model = models[0]
best_model.fit(X, Y）
best_model.save("best_model_2")

**Comment by itsSrijan** [comment]
From [the website](https://keras.io/api/keras_tuner/tuners/base_tuner/)

> The models are loaded with the weights corresponding to their best checkpoint (at the end of the best epoch of best trial).
> 
> This method is for querying the models trained during the search. For best performance, it is recommended to retrain your Model on the full dataset using the best hyperparameters found during search, which can be obtained using tuner.get_best_hyperparameters().

Essentially `get_best_models()` gives the best hyperparameters + the weights stored at the best epoch, which you generally may not require. Whereas, `get_best_hyperparameters()` returns **only** the best hyperparameters using which you can then further train your model.
