### ISSUE TITLE
A standard way to report more failure status of a trial

### ISSUE THREAD

**Issue by haifeng-jin** [keras-team/keras-tuner#704]
**Is your feature request related to a problem? Please describe.**

If a model is failed at training, the whole program crashes.
A better strategy is to report the status fo this trial and skip it.

**Describe the solution you'd like**

One solution would be have a new function of Oracle just to report the failure status of a trial.
However, it requries modification to the proto files used by gRPC.
Rurther looks into the roadmap of distributed features of keras_tuner is required.

**Describe alternatives you've considered**

**Additional context**

**Comment by carlthome** [comment]
This is sorely missing.

I'm tuning both feature representation and model topology simultaneously in a keras-tuner experiment, and when the number of pooling layers is too many for the size of the input features, the whole tuning simply crashes, with no obvious way for me to catch exceptions and skip to the next trial.

**Comment by haifeng-jin** [comment]
This can now be done with `raise keras_tuner.FailedTrialError("error message.")` in `HyperModel.build()`, `HyperModel.fit()`, or your model build function.
