### ISSUE TITLE
HyperTuner min_value, max_value in for loop for number of layers

### ISSUE THREAD

**Issue by cube2022** [keras-team/keras-tuner#708]
I'm trying to construct a build_model function for hyperparameter tuning. Like in the Keras documents I use a for loop for the number of layers. Further I want to set some conditions for the min_value and max_value for the units. After one iteration I want to change the values of min_value and max_value in hp.Int("units", min_value, max_value). But sometimes it seems to be that the hp-algorithm does not except new values for min_value, max_value. Is this possible? Or is there another way to update these values?

I'm using Tensorflow 2.9.1 and  Keras_Tuner 1.1.2

**Comment by haifeng-jin** [comment]
This is currently not possible to change the search space for each trial.
