### ISSUE TITLE
Use keras-tuner with data augmentation and transfer learning. Error: expected shape=(None, 224, 224, 3), found shape=(32, 244, 244, 3)

### ISSUE THREAD

**Issue by IrynaMil** [keras-team/keras-tuner#709]
Hello,
I do not have any big programming background and I really need your help to go further with my student research. 

- [ ] **Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 224, 224, 3), found shape=(32, 244, 244, 3)**

I would like to use Random Search with keras-tuner for VGG16 model with data augmentation.  Is it an issue because of Data Augmentation? Here is how I have built my model:
```
`dataset = train_datagen.flow_from_directory(train_dir,
                                            target_size=(224,224),
                                            batch_size=32,
                                            class_mode='binary')
X,y = dataset.next()

validation_generator = train_datagen.flow_from_directory(validation_dir, 
                                          target_size=(244,244),
                                          batch_size=32,
                                          class_mode='binary')
X_val,y_val = validation_generator.next()

def build_model(hp):
    from keras.optimizers import adam_v2
    from keras.applications.vgg16 import VGG16
    input = Input(shape=(224,224,3))
    vggmodel = VGG16(weights='imagenet', include_top=False)
    for layers in (vggmodel.layers)[:19]: 
        print(layers)
        layers.trainable = False
    X = vggmodel(input)    
    X = Flatten()(X)
    X = Dense(hp.Int("dense_units_1", min_value=256, max_value=4096, step=256), activation="relu")(X)
    X = Dropout(rate=hp.Float('dropout_1', min_value=0.0,max_value=0.5, default=0.25, step=0.05))(X)
    X = Dense(hp.Int("dense_units_1", min_value=256, max_value=1024, step=256), activation="relu")(X)
    X = Dropout(rate=hp.Float('dropout_2', min_value=0.0, max_value=0.5, default=0.25, step=0.05))(X)
    X = Dense(1, activation="sigmoid")(X)
    model = Model(inputs=input, output=X) 
    opt = adam_v2.Adam(lr=0.0002)
    model.compile(loss = "binary_crossentropy", optimizer = opt, metrics=["accuracy"])
    return model`

import kerastuner
from kerastuner.tuners import RandomSearch
from kerastuner.engine.hypermodel import HyperModel
from kerastuner.engine.hyperparameters import HyperParameters

tuner = RandomSearch(
    hypermodel= build_model,
    objective=kerastuner.Objective("val_accuracy", direction="min"),
    max_trials=20,
    executions_per_trial=3)

tuner.search_space_summary()
tuner.search(X,y, validation_data=(X_val, y_val))`
```

And here is the error:
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/109559706/179633560-aa20e82a-046c-4c98-beca-53b6c9620d95.png">

- How can I reshape my data to solve the issue? 
- Will it work when I change the number of trainable layers? E.g 
`    for layers in (vggmodel.layers)[:16]: 
          layers.trainable = False`

- [ ] **ValueError: `logits` and `labels` must have the same shape, received ((32, 7, 7, 1) vs (32,))**

I also tried to remove Flatten and get another error
<img width="867" alt="image" src="https://user-images.githubusercontent.com/109559706/179636394-8a6c0923-6669-4190-b9ba-dc7547456721.png">

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/109559706/179636440-aa57112a-efe2-496b-ae21-24d594c8c434.png">

**Comment by haifeng-jin** [comment]
It seems the error is not a KerasTuner error, but the why you use Keras is wrong.
Please remove the `hp`s and use constant values instead and try to call your `build_model` function to debug.
