### ISSUE TITLE
HTML expects text

### ISSUE THREAD

**Issue by pers1307** [keras-team/keras-tuner#71]
strange error

When I execute:
tuner.search(x_train,                  # Данные для обучения
             y_train,                  # Правильные ответы
             batch_size=256,           # Размер мини-выборки
             epochs=5,                # Количество эпох обучения 
             validation_split=0.2,     # Часть данных, которая будет использоваться для проверки
             verbose=0
             )

Link on colab with example:
https://colab.research.google.com/drive/1nd3aA4BdFbncb4U2zVzwJ0Npqcc14-hA

**Comment by sockfish** [comment]
same problem

**Comment by zcoder** [comment]
have same problem
