### ISSUE TITLE
hyperband doesn't work as intended

### ISSUE THREAD

**Issue by ebursztein** [keras-team/keras-tuner#72]
There sorting of the trial is incorrect for at least two reasons:
1. line: 130 the values are not initialized so the comparison fail in line 136
2. The sort in 136: sort in ascending order so the one with the lowest score are always picked up in line 139

So the init/sort should take into account the metric direction

**Comment by jhfjhfj1** [comment]
Thanks. I will look into it.

**Comment by gabrieldemarmiesse** [comment]
I believe this issue can be closed.

**Comment by omalleyt12** [comment]
Fixed by https://github.com/keras-team/keras-tuner/pull/115
