### ISSUE TITLE
Update Community Chapter in `Readme`

### ISSUE THREAD

**Issue by Anselmoo** [keras-team/keras-tuner#783]
The Chapter about `Community` should be updated or removed because **Keras-Slack-Workspace** obviously no longer exists.

https://github.com/keras-team/keras-tuner/blob/d559fdd3a33cc5f2a4d58cf59f9636510d5e1c7d/README.md?plain=1#L89-L93

**Comment by haifeng-jin** [comment]
Good point! Let's update it to use the [GitHub Discussions](https://github.com/keras-team/keras-tuner/discussions), which is similar to AutoKeras. Would you like to make a PR?

**Comment by Anselmoo** [comment]
Will do later ...
