### ISSUE TITLE
Documentation of tuners not updated with GridSearch Tuner 

### ISSUE THREAD

**Issue by frMitola** [keras-team/keras-tuner#785]
Hello, 
I can't find GridSearch Tuner documentation at these links [1.](https://keras.io/api/keras_tuner/tuners/) [2.](https://keras.io/api/keras_tuner/) and so on although I see on Github that it's implemented

**Comment by haifeng-jin** [comment]
The documentation will be updated after the next stable release, which is 1.2.0. We are still pending another feature to make the release. If you would like to use it now. You can install from the master branch.

Thanks.

**Comment by frMitola** [comment]
Hello,
thank you for the support!
Any hints on the next release date?

**Comment by haifeng-jin** [comment]
@frMitola We are still pending on a thread safety update on the oracles. It will be in Q1 2023.
