### ISSUE TITLE
Change all Py2 style class definition to Py3 style

### ISSUE THREAD

**Issue by haifeng-jin** [keras-team/keras-tuner#812]
Change all occurance of `class SomeClass(object):` to `class SomeClass:` throughout the codebase.
This is the recommended style in Python 3.
[More details](https://stackoverflow.com/a/9448136/7910419).

For example, this:

https://github.com/keras-team/keras-tuner/blob/a7a361f9521cb1033a05aba865c86eb30784d907/keras_tuner/engine/stateful.py#L22

needs to be changed to:

```py
class Stateful:
```

Please comment on this issue before you start working on it so that others can know.

**Comment by LuNoX** [comment]
Similar to #813, this looks like a very doable issue and I would like to take it on as well, if that's ok :)

**Comment by haifeng-jin** [comment]
@LuNoX Of course. Thanks!

**Comment by LuNoX** [comment]
I opened a PR for the changes: https://github.com/keras-team/keras-tuner/pull/815. I hope this is what you were looking for :)

**Comment by LuNoX** [comment]
For future reference, if similar issues arise:

I made the changes using a regex.
`(class .*)\(object\): ` finds any sequence of characters that looks like "class <SomeCharacters>(object):" and captures "class <SomeCharacters>". You can then replace all matches with "$1:" which translates to "class <SomeCharacters>:".

Hope this helps :)
