### ISSUE TITLE
Change all Py2 style super() class call to Py3 style

### ISSUE THREAD

**Issue by haifeng-jin** [keras-team/keras-tuner#813]
Change all `super(ClassName, self).method_name()` occurance in the codebase to `super().method_name()`, which is recommended by the Python 3 documentation.

[More details](https://stackoverflow.com/a/10483204/7910419).

For example, this:

https://github.com/keras-team/keras-tuner/blob/d536635a92ca4c4177d4d77f2ee893b301ed6090/keras_tuner/engine/oracle.py#L482

needs to be changed to:

```py
super().reload(self._get_oracle_fname())
```

Please comment on this issue before you start working on it so that others can know.

**Comment by LuNoX** [comment]
This seems like a doable issue. I would like to take it on :)

**Comment by haifeng-jin** [comment]
@LuNoX Thank you!

**Comment by LuNoX** [comment]
Just for clarification:
In your example @haifeng-jin, the called method changed from save(...) to reload(...).
I'm assuming, I'm not supposed to also change all instances of save to reload but only to change the super() constructor calls to Python3 style. Am I correct in this assumption?

**Comment by LuNoX** [comment]
I created a PR for the changes: https://github.com/keras-team/keras-tuner/pull/816. I made changes under the above-mentioned assumption. I hope this is what you were looking for @haifeng-jin :)

**Comment by LuNoX** [comment]
For future reference, if similar issues arise:

I made the changes using a regex.
`super\([^)]+\)` finds any sequence of characters that looks like "super(<SomeCharacters>)". You can then replace all matches with `super()`.

Hope this helps :)
