### ISSUE TITLE
示例教程报错了

### ISSUE THREAD

**Issue by 1044197988** [keras-team/keras-tuner#84]
(x_train, y_train), (x_test, y_test) = load_data()

import autokeras as ak
import tensorflow as tf
x_train = x_train.reshape(x_train.shape + (1,))
x_test = x_test.reshape(x_test.shape + (1,))
#x_train = tf.cast(x_train.reshape(x_train.shape + (1,)),tf.float64)
#x_test = tf.cast(x_test.reshape(x_test.shape + (1,)),tf.float64)

clf = ak.ImageClassifier(max_trials=100)
clf.fit(x_train, y_train)
y = clf.predict(x_test, y_test)

  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\autokeras\auto_model.py", line 146, in prepare_data
    x_val, y_val = validation_data
TypeError: 'NoneType' object is not iterable

添加上这一句validation_split=0.05  报错需要tf.float64

转换为float64后
#x_train = tf.cast(x_train.reshape(x_train.shape + (1,)),tf.float64)
#x_test = tf.cast(x_test.reshape(x_test.shape + (1,)),tf.float64)
：

tensorflow.python.framework.errors_impl.InvalidArgumentError: Length for attr 'output_types' of 0 must be at least minimum 1
	; NodeDef: {{node ZipDataset}}; Op<name=ZipDataset; signature=input_datasets:N*variant -> handle:variant; attr=output_types:list(type),min=1; attr=output_shapes:list(shape),min=1; attr=N:int,min=1> [Op:ZipDataset]

环境tensorflow2.0.0rc1
win10
py3.6

**Comment by omalleyt12** [comment]
@1044197988 this is probably a better issue for the [AutoKeras](https://github.com/keras-team/autokeras) repo. Please post this issue over there

@jhfjhfj1 for visibility, who works on AutoKeras

**Comment by 1044197988** [comment]
抱歉，给发错了，谢谢
