### ISSUE TITLE
In 1.2.0 and 1.2.1 the call to Hyperband.search never finishes

### ISSUE THREAD

**Issue by 8192K** [keras-team/keras-tuner#844]
**Describe the bug**
Freshly migrated from 1.1.3 to 1.2.1. We have a model with two hyperparameters with three values each, which makes nine combinations. This worked fine in 1.1.3, with Hyperband.search finishing after nine trials. In 1.2.1 (and 1.2.0) the call to Hyperband.search never finishes.

**To Reproduce**
https://drive.google.com/drive/folders/1jrCYw-Tmz4qLi4v2oBq_EL2xR6gosIIA?usp=sharing
Please note the 'data' folder which is required to run the notebook.

**Expected behavior**
The call to Hyperband.search finishes after the number of hyperparameter combinations.

**Additional context**
I've uploaded two files, each one containing the content of all trial.json files which are being created in the run of Hyperband.search, one for each version. It is clear that in 1.2.1 the same combinations are being repeated again and again, never finishing.

Tensorflow 2.11 and Keras 2.11 are used on a Linux system in an anaconda environment. The output of 'conda list' is also attached.
[trial_json_files_kt_113.txt](https://github.com/keras-team/keras-tuner/files/10760268/trial_json_files_kt_113.txt)
[trial_json_files_kt_121.txt](https://github.com/keras-team/keras-tuner/files/10760269/trial_json_files_kt_121.txt)
[conda_list.txt](https://github.com/keras-team/keras-tuner/files/10760271/conda_list.txt)

**Comment by haifeng-jin** [comment]
Thanks for the issue.
I have successfully reproduced the bug.
Trying to figure out the fix now.

**Comment by haifeng-jin** [comment]
After some further inspection, I found the new behavior is the correct behavior.
The Hyperband should not finish in 9 trials.
The 9 trials are only the first round.
It should continue to select the good ones from the remaining candidates and further train.

Here is [my script](https://colab.research.google.com/github/haifeng-jin/Colabs/blob/main/keras_tuner_844.ipynb) for running Hyperband in a similar setup as yours.
It finished in 270 trials.

**Comment by 8192K** [comment]
Thank you for the clarification. It would be great if you could add this change in behavior to the release notes, though.
I will switch to GridSearch.
