### ISSUE TITLE
keras-tuner on tensorflow 2.12

### ISSUE THREAD

**Issue by imanbabaei** [keras-team/keras-tuner#879]
keras-tuner==1.3.0 returns an error after upgrading tensorflow to 2.12:

```
>>> import keras_tuner
.
.
.
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```
In tf==2.12, protobuf upgraded to 4.2 (from 3.19 in tf~=2.11)
However, downgrading to protobuf~=3.20 fixed the problem.

I'm sorry that I didn't include the full error but pretty sure that you can quickly regenerate it.

**Comment by haifeng-jin** [comment]
Thanks for the issue, @imanbabaei!
I am working on fixing it.

**Comment by haifeng-jin** [comment]
I regenerated using protobuf 3.20.
I did not use 4.22 because it would break the backward compatibility with previous TF versions.
Now the solution is:

```shell
pip install protobuf==3.20.*
```

We may wait a little bit to bump the minimum required TF version to 2.12 and use protobuf 4.22 instead.

**Comment by imanbabaei** [comment]
Thanks @haifeng-jin .
This works for me and everything is in order. I will install TF2.12 and downgrade protobuf to 3.20.x for now.

**Comment by haifeng-jin** [comment]
To avoid user confusion, we pin down the `protobuf<=3.20` in a new release `keras-tuner 1.3.2`.
So that people may avoid seeing the error by installing keras-tuner after install TF 2.12.
And it is compatible with all TF versions.

**Comment by MartinNowak** [comment]
> To avoid user confusion, we pin down the `protobuf<=3.20` in a new release `keras-tuner 1.3.2`.
> So that people may avoid seeing the error by installing keras-tuner after install TF 2.12.
> And it is compatible with all TF versions.

I'm afraid what most people end up seeing is that pip fails to resolve dependencies. Most of the google cloud libraries have updated protobuf, leading to long backtracking in the dependency resolver.

[`grpcio-status` 1.50.0](https://libraries.io/pypi/grpcio-status/1.50.0) added added `protobuf>=4.21.6`.

> Python upb requires generated code that has been generated from protoc 3.19.0 or newer.

Now that https://github.com/keras-team/keras-tuner/pull/880 regenerated the proto files, would those be compatible with protobuf 4.2 libraries?
