### ISSUE TITLE
TypeError: 'HTML' object is not subscriptable

### ISSUE THREAD

**Issue by alireza-a-hashemi** [keras-team/keras-tuner#88]
When i run the MNIST example  get this error after tuner.search:

TypeError                                 Traceback (most recent call last)
<ipython-input-26-d5f10f001cae> in <module>
      4              y=y,
      5              epochs=3,
----> 6              validation_data=(val_x, val_y))
      7 

~\Anaconda3\lib\site-packages\kerastuner\engine\tuner.py in search(self, *fit_args, **fit_kwargs)
    222             self.on_trial_begin(trial)
    223             self.run_trial(trial, hp, fit_args, fit_kwargs)
--> 224             self.on_trial_end(trial)
    225         self.on_search_end()
    226 

~\Anaconda3\lib\site-packages\kerastuner\engine\tuner.py in on_trial_end(self, trial)
    375             objective=self.objective,
    376             remaining_trials=self.remaining_trials,
--> 377             max_trials=self.max_trials)
    378 
    379     def on_search_end(self):

~\Anaconda3\lib\site-packages\kerastuner\engine\tuner_utils.py in on_trial_end(self, averaged_metrics, best_metrics, objective, remaining_trials, max_trials)
    137                     row = display.colorize_row(row, 'red')
    138             rows.append(row)
--> 139         display.display_table(rows)
    140 
    141         # Tuning budget exhausted

~\Anaconda3\lib\site-packages\kerastuner\abstractions\display.py in display_table(rows, title, indent)
    372             out.append(indent + line)
    373         table = "\n".join(out)
--> 374     display(table)
    375 
    376 

~\Anaconda3\lib\site-packages\IPython\core\display.py in __init__(self, data, url, filename, metadata)
    691             return prefix.startswith("<iframe ") and suffix.endswith("</iframe>")
    692 
--> 693         if warn():
    694             warnings.warn("Consider using IPython.display.IFrame instead")
    695         super(HTML, self).__init__(data=data, url=url, filename=filename, metadata=metadata)

~\Anaconda3\lib\site-packages\IPython\core\display.py in warn()
    687             # long string and we're only interested in its beginning and end.
    688             #
--> 689             prefix = data[:10].lower()
    690             suffix = data[-10:].lower()
    691             return prefix.startswith("<iframe ") and suffix.endswith("</iframe>")

TypeError: 'HTML' object is not subscriptable

**Comment by omalleyt12** [comment]
@alireza-a-hashemi Thanks for the issue! This should be fixed by https://github.com/keras-team/keras-tuner/pull/79

Please try again and reopen if this is still a problem
