### ISSUE TITLE
Non-sparse categorical_accuracy loss causes best model to never update

### ISSUE THREAD

**Issue by LeoVerto** [keras-team/keras-tuner#9]
I'm trying to optimize my own take on the MNIST classification problem and for some reason the best model is never updated from the initial one, even when the the `categorical_accuracy` metric has reached better values.

Here's an example statistics printout (val_categorial_accuracy is highlighted in red):
```
┌──────────────────────────┬────────────┬───────────────┐
│ Name                     │ Best model │ Current model │
├──────────────────────────┼────────────┼───────────────┤
│ categorical_accuracy     │ 0.9107     │ 0.9598        │
│ loss                     │ 0.3016     │ 0.1321        │
│ val_categorical_accuracy │ 0.9726     │ 0.9846        │
│ val_loss                 │ 0.094      │ 0.0509        │
└──────────────────────────┴────────────┴───────────────┘
```

However when remodelling the model to use `sparse_categorical_accuracy` (as is used in the example script), everything magically works just fine and better models are being selected again.

**Comment by omalleyt12** [comment]
@LeoVerto Could you try again with the master branch and if this is still an issue, provide a minimal repro?

**Comment by omalleyt12** [comment]
Closing for now, I think it's likely the Model required `sparse_categorical_accuracy`. Please feel freee to re-open if you can provide a repro with the version on the `master` branch. Thanks!
