### ISSUE TITLE
Keras Core support

### ISSUE THREAD

**Issue by aaarrti** [keras-team/keras-tuner#916]
Hi, 
when my model is defined following way: 
```python
import keras_core as keras

class EventTypesModel(keras.Model): 
...
```
I receive
```
keras_tuner.errors.FatalTypeError: Expected the model-building function, or HyperModel.build() to return a valid Keras Model instance. Received: <EventTypesModel name=event_types_model, built=False> of type <class 'mapping_model.modeling.EventTypesModel'>.
```
Changing to 
```python
import tensorflow as tf

class EventTypesModel(tf.keras.Model): 
...
```
Do you plan to support [Keras Core](https://github.com/keras-team/keras-core) models, as, e.g., [Keras NLP](https://github.com/keras-team/keras-nlp) does?

**Comment by ramakc153** [comment]
it seems keras tuner is not supported yet for keras core. I'm hoping keras core team able to implement keras tuner feature on keras core soon.

**Comment by haifeng-jin** [comment]
Keras Core is a temporary package.
The current suggestion is to use `keras-nightly`, which is an updated version of `keras-core`.
KerasTuner supports `keras-nightly`.
